; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2022-06-22 at 13:00:03

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z2.650 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X167.739 Y188.602 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X168.457 Y188.010 E2.00355 ; external perimeter
G1 X169.201 Y187.451 E2.00710 ; external perimeter
G1 X169.970 Y186.926 E2.01064 ; external perimeter
G1 X170.761 Y186.437 E2.01419 ; external perimeter
G1 X171.574 Y185.984 E2.01774 ; external perimeter
G1 X172.406 Y185.568 E2.02129 ; external perimeter
G1 X173.257 Y185.190 E2.02484 ; external perimeter
G1 X174.124 Y184.851 E2.02838 ; external perimeter
G1 X175.005 Y184.551 E2.03193 ; external perimeter
G1 X175.898 Y184.292 E2.03548 ; external perimeter
G1 X176.803 Y184.073 E2.03903 ; external perimeter
G1 X177.717 Y183.895 E2.04258 ; external perimeter
G1 X178.637 Y183.759 E2.04612 ; external perimeter
G1 X179.563 Y183.665 E2.04967 ; external perimeter
G1 X180.492 Y183.612 E2.05322 ; external perimeter
G1 X181.423 Y183.602 E2.05677 ; external perimeter
G1 X182.353 Y183.633 E2.06032 ; external perimeter
G1 X183.280 Y183.707 E2.06386 ; external perimeter
G1 X184.204 Y183.822 E2.06741 ; external perimeter
G1 X185.121 Y183.979 E2.07096 ; external perimeter
G1 X186.031 Y184.177 E2.07451 ; external perimeter
G1 X186.930 Y184.416 E2.07806 ; external perimeter
G1 X187.818 Y184.696 E2.08160 ; external perimeter
G1 X188.692 Y185.015 E2.08515 ; external perimeter
G1 X189.550 Y185.374 E2.08870 ; external perimeter
G1 X190.392 Y185.771 E2.09225 ; external perimeter
G1 X191.215 Y186.206 E2.09580 ; external perimeter
G1 X192.017 Y186.677 E2.09934 ; external perimeter
G1 X192.798 Y187.184 E2.10289 ; external perimeter
G1 X193.554 Y187.726 E2.10644 ; external perimeter
G1 X194.286 Y188.302 E2.10999 ; external perimeter
G1 X194.990 Y188.910 E2.11354 ; external perimeter
G1 X195.667 Y189.549 E2.11708 ; external perimeter
G1 X196.313 Y190.218 E2.12063 ; external perimeter
G1 X196.929 Y190.916 E2.12418 ; external perimeter
G1 X197.513 Y191.640 E2.12773 ; external perimeter
G1 X198.064 Y192.391 E2.13128 ; external perimeter
G1 X198.579 Y193.165 E2.13482 ; external perimeter
G1 X199.060 Y193.962 E2.13837 ; external perimeter
G1 X199.504 Y194.780 E2.14192 ; external perimeter
G1 X199.910 Y195.617 E2.14547 ; external perimeter
G1 X200.279 Y196.472 E2.14901 ; external perimeter
G1 X200.608 Y197.343 E2.15256 ; external perimeter
G1 X200.897 Y198.227 E2.15611 ; external perimeter
G1 X201.147 Y199.124 E2.15966 ; external perimeter
G1 X201.355 Y200.031 E2.16321 ; external perimeter
G1 X201.523 Y200.946 E2.16675 ; external perimeter
G1 X201.648 Y201.868 E2.17030 ; external perimeter
G1 X201.732 Y202.789 E2.17383 ; external perimeter
G1 X201.779 Y204.190 E2.17917 ; external perimeter
G1 X201.732 Y205.591 E2.18451 ; external perimeter
G1 X201.648 Y206.512 E2.18804 ; external perimeter
G1 X201.523 Y207.434 E2.19159 ; external perimeter
G1 X201.355 Y208.349 E2.19514 ; external perimeter
G1 X201.147 Y209.256 E2.19869 ; external perimeter
G1 X200.897 Y210.153 E2.20223 ; external perimeter
G1 X200.608 Y211.037 E2.20578 ; external perimeter
G1 X200.279 Y211.908 E2.20933 ; external perimeter
G1 X199.910 Y212.763 E2.21288 ; external perimeter
G1 X199.504 Y213.600 E2.21643 ; external perimeter
G1 X199.060 Y214.418 E2.21997 ; external perimeter
G1 X198.579 Y215.215 E2.22352 ; external perimeter
G1 X198.064 Y215.989 E2.22707 ; external perimeter
G1 X197.513 Y216.740 E2.23062 ; external perimeter
G1 X196.929 Y217.464 E2.23417 ; external perimeter
G1 X196.313 Y218.162 E2.23771 ; external perimeter
G1 X195.667 Y218.831 E2.24126 ; external perimeter
G1 X194.990 Y219.470 E2.24481 ; external perimeter
G1 X194.286 Y220.078 E2.24836 ; external perimeter
G1 X193.554 Y220.654 E2.25190 ; external perimeter
G1 X192.798 Y221.196 E2.25545 ; external perimeter
G1 X192.017 Y221.703 E2.25900 ; external perimeter
G1 X191.215 Y222.174 E2.26255 ; external perimeter
G1 X190.392 Y222.609 E2.26610 ; external perimeter
G1 X189.550 Y223.006 E2.26964 ; external perimeter
G1 X188.692 Y223.365 E2.27319 ; external perimeter
G1 X187.818 Y223.684 E2.27674 ; external perimeter
G1 X186.930 Y223.963 E2.28029 ; external perimeter
G1 X186.031 Y224.203 E2.28384 ; external perimeter
G1 X185.121 Y224.401 E2.28738 ; external perimeter
G1 X184.204 Y224.558 E2.29093 ; external perimeter
G1 X183.280 Y224.673 E2.29448 ; external perimeter
G1 X182.353 Y224.747 E2.29803 ; external perimeter
G1 X181.423 Y224.778 E2.30158 ; external perimeter
G1 X180.492 Y224.768 E2.30512 ; external perimeter
G1 X179.563 Y224.715 E2.30867 ; external perimeter
G1 X178.637 Y224.621 E2.31222 ; external perimeter
G1 X177.717 Y224.485 E2.31577 ; external perimeter
G1 X176.803 Y224.307 E2.31932 ; external perimeter
G1 X175.898 Y224.088 E2.32286 ; external perimeter
G1 X175.005 Y223.829 E2.32641 ; external perimeter
G1 X174.124 Y223.529 E2.32996 ; external perimeter
G1 X173.257 Y223.190 E2.33351 ; external perimeter
G1 X172.406 Y222.812 E2.33706 ; external perimeter
G1 X171.574 Y222.396 E2.34060 ; external perimeter
G1 X170.761 Y221.943 E2.34415 ; external perimeter
G1 X169.970 Y221.454 E2.34770 ; external perimeter
G1 X169.201 Y220.929 E2.35125 ; external perimeter
G1 X168.457 Y220.370 E2.35480 ; external perimeter
G1 X167.739 Y219.778 E2.35834 ; external perimeter
G1 X167.048 Y219.155 E2.36189 ; external perimeter
G1 X166.386 Y218.500 E2.36544 ; external perimeter
G1 X165.755 Y217.817 E2.36899 ; external perimeter
G1 X165.155 Y217.105 E2.37254 ; external perimeter
G1 X164.587 Y216.368 E2.37608 ; external perimeter
G1 X164.054 Y215.605 E2.37963 ; external perimeter
G1 X163.556 Y214.819 E2.38318 ; external perimeter
G1 X163.094 Y214.011 E2.38673 ; external perimeter
G1 X162.668 Y213.183 E2.39028 ; external perimeter
G1 X162.281 Y212.337 E2.39382 ; external perimeter
G1 X161.932 Y211.474 E2.39737 ; external perimeter
G1 X161.622 Y210.597 E2.40092 ; external perimeter
G1 X161.353 Y209.706 E2.40447 ; external perimeter
G1 X161.124 Y208.804 E2.40802 ; external perimeter
G1 X160.936 Y207.893 E2.41156 ; external perimeter
G1 X160.789 Y206.974 E2.41511 ; external perimeter
G1 X160.684 Y206.049 E2.41866 ; external perimeter
G1 X160.621 Y205.120 E2.42221 ; external perimeter
G1 X160.600 Y204.190 E2.42576 ; external perimeter
G1 X160.621 Y203.260 E2.42930 ; external perimeter
G1 X160.684 Y202.331 E2.43285 ; external perimeter
G1 X160.789 Y201.406 E2.43640 ; external perimeter
G1 X160.936 Y200.487 E2.43995 ; external perimeter
G1 X161.124 Y199.576 E2.44350 ; external perimeter
G1 X161.353 Y198.674 E2.44704 ; external perimeter
G1 X161.622 Y197.783 E2.45059 ; external perimeter
G1 X161.932 Y196.906 E2.45414 ; external perimeter
G1 X162.281 Y196.043 E2.45769 ; external perimeter
G1 X162.668 Y195.197 E2.46124 ; external perimeter
G1 X163.094 Y194.369 E2.46478 ; external perimeter
G1 X163.556 Y193.561 E2.46833 ; external perimeter
G1 X164.054 Y192.775 E2.47188 ; external perimeter
G1 X164.587 Y192.012 E2.47543 ; external perimeter
G1 X165.155 Y191.275 E2.47898 ; external perimeter
G1 X165.755 Y190.563 E2.48252 ; external perimeter
G1 X166.386 Y189.880 E2.48607 ; external perimeter
G1 X167.048 Y189.225 E2.48962 ; external perimeter
G1 X167.605 Y188.722 E2.49248 ; external perimeter
G1 E0.49248 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X167.036 Y191.952 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X167.020 Y191.969 E2.00009 ; infill
G1 X169.119 Y189.876 E2.01162 ; infill
G1 X169.745 Y189.311 E2.01491 ; infill
G1 X170.396 Y188.774 E2.01819 ; infill
G1 X171.071 Y188.268 E2.02147 ; infill
G1 X171.767 Y187.792 E2.02475 ; infill
G1 X172.485 Y187.348 E2.02803 ; infill
G1 X173.222 Y186.938 E2.03132 ; infill
G1 X173.976 Y186.561 E2.03460 ; infill
G1 X174.747 Y186.218 E2.03788 ; infill
G1 X175.533 Y185.911 E2.04116 ; infill
G1 X176.023 Y185.744 E2.04318 ; infill
G1 X162.740 Y199.026 E2.11626 ; infill
G1 X162.459 Y199.938 E2.11997 ; infill
G1 X162.252 Y200.756 E2.12326 ; infill
G1 X162.081 Y201.582 E2.12654 ; infill
G1 X161.925 Y202.620 E2.13062 ; infill
G1 X179.624 Y184.921 E2.22801 ; infill
G1 X180.464 Y184.835 E2.23130 ; infill
G1 X181.306 Y184.788 E2.23458 ; infill
G1 X182.532 Y184.791 E2.23935 ; infill
G1 X161.790 Y205.533 E2.35348 ; infill
G1 X161.853 Y206.624 E2.35773 ; infill
G1 X161.948 Y207.462 E2.36101 ; infill
G1 X162.043 Y208.058 E2.36336 ; infill
G1 X185.057 Y185.044 E2.49000 ; infill
G1 X185.502 Y185.120 E2.49175 ; infill
G1 X186.326 Y185.300 E2.49504 ; infill
G1 X187.310 Y185.570 E2.49900 ; infill
G1 X162.571 Y210.309 E2.63513 ; infill
G1 X162.704 Y210.746 E2.63691 ; infill
G1 X162.984 Y211.542 E2.64019 ; infill
G1 X163.311 Y212.347 E2.64357 ; infill
G1 X189.345 Y186.313 E2.78682 ; infill
G1 X190.280 Y186.745 E2.79083 ; infill
G1 X191.197 Y187.239 E2.79489 ; infill
G1 X164.240 Y214.196 E2.94322 ; infill
G1 X164.456 Y214.574 E2.94491 ; infill
G1 X164.908 Y215.286 E2.94819 ; infill
G1 X165.328 Y215.887 E2.95104 ; infill
G1 X192.885 Y188.329 E3.10268 ; infill
G1 X193.810 Y189.039 E3.10721 ; infill
G1 X194.424 Y189.569 E3.11037 ; infill
G1 X166.570 Y217.422 E3.26363 ; infill
G1 X167.022 Y217.911 E3.26622 ; infill
G1 X167.622 Y218.504 E3.26950 ; infill
G1 X167.961 Y218.810 E3.27128 ; infill
G1 X195.811 Y190.960 E3.42453 ; infill
G1 X196.206 Y191.408 E3.42685 ; infill
G1 X196.735 Y192.065 E3.43013 ; infill
G1 X197.052 Y192.497 E3.43222 ; infill
G1 X169.495 Y220.054 E3.58385 ; infill
G1 X170.270 Y220.588 E3.58751 ; infill
G1 X171.185 Y221.142 E3.59167 ; infill
G1 X198.144 Y194.183 E3.74002 ; infill
G1 X198.540 Y194.912 E3.74324 ; infill
G1 X199.067 Y196.039 E3.74808 ; infill
G1 X173.038 Y222.068 E3.89131 ; infill
G1 X174.036 Y222.469 E3.89550 ; infill
G1 X175.073 Y222.810 E3.89975 ; infill
G1 X199.813 Y198.071 E4.03587 ; infill
G1 X200.029 Y198.849 E4.03902 ; infill
G1 X200.218 Y199.671 E4.04230 ; infill
G1 X200.338 Y200.324 E4.04488 ; infill
G1 X177.322 Y223.340 E4.17153 ; infill
G1 X178.127 Y223.459 E4.17469 ; infill
G1 X178.966 Y223.545 E4.17798 ; infill
G1 X179.847 Y223.593 E4.18141 ; infill
G1 X200.582 Y202.858 E4.29550 ; infill
G1 X200.602 Y203.441 E4.29777 ; infill
G1 X200.559 Y204.722 E4.30276 ; infill
G1 X200.454 Y205.764 E4.30684 ; infill
G1 X182.765 Y223.453 E4.40417 ; infill
G1 X184.005 Y223.260 E4.40905 ; infill
G1 X184.829 Y223.080 E4.41233 ; infill
G1 X185.645 Y222.863 E4.41561 ; infill
G1 X186.358 Y222.638 E4.41853 ; infill
G1 X199.634 Y209.362 E4.49158 ; infill
G1 X199.242 Y210.438 E4.49603 ; infill
G1 X198.908 Y211.212 E4.49931 ; infill
G1 X198.540 Y211.971 E4.50260 ; infill
G1 X198.137 Y212.713 E4.50588 ; infill
G1 X197.702 Y213.435 E4.50916 ; infill
G1 X197.234 Y214.137 E4.51244 ; infill
G1 X196.735 Y214.817 E4.51573 ; infill
G1 X196.206 Y215.474 E4.51901 ; infill
G1 X195.648 Y216.107 E4.52229 ; infill
G1 X193.562 Y218.213 E4.53382 ; infill
G1 Z3.850 F1800.000 ; move to next layer (1)
G1 X167.511 Y188.349 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X168.246 Y187.742 E4.54071 ; external perimeter
G1 X169.003 Y187.174 E4.54753 ; external perimeter
G1 X169.784 Y186.641 E4.55436 ; external perimeter
G1 X170.589 Y186.144 E4.56118 ; external perimeter
G1 X171.415 Y185.683 E4.56801 ; external perimeter
G1 X172.261 Y185.260 E4.57483 ; external perimeter
G1 X173.126 Y184.876 E4.58166 ; external perimeter
G1 X174.007 Y184.531 E4.58848 ; external perimeter
G1 X174.903 Y184.227 E4.59531 ; external perimeter
G1 X175.811 Y183.963 E4.60213 ; external perimeter
G1 X176.731 Y183.741 E4.60896 ; external perimeter
G1 X177.659 Y183.560 E4.61578 ; external perimeter
G1 X178.595 Y183.422 E4.62261 ; external perimeter
G1 X179.536 Y183.326 E4.62943 ; external perimeter
G1 X180.481 Y183.272 E4.63626 ; external perimeter
G1 X181.427 Y183.262 E4.64309 ; external perimeter
G1 X182.372 Y183.294 E4.64991 ; external perimeter
G1 X183.315 Y183.368 E4.65674 ; external perimeter
G1 X184.254 Y183.486 E4.66356 ; external perimeter
G1 X185.186 Y183.645 E4.67039 ; external perimeter
G1 X186.110 Y183.847 E4.67721 ; external perimeter
G1 X187.025 Y184.090 E4.68404 ; external perimeter
G1 X187.927 Y184.374 E4.69086 ; external perimeter
G1 X188.816 Y184.699 E4.69769 ; external perimeter
G1 X189.689 Y185.063 E4.70451 ; external perimeter
G1 X190.544 Y185.467 E4.71134 ; external perimeter
G1 X191.381 Y185.909 E4.71816 ; external perimeter
G1 X192.196 Y186.388 E4.72499 ; external perimeter
G1 X192.989 Y186.903 E4.73181 ; external perimeter
G1 X193.759 Y187.454 E4.73864 ; external perimeter
G1 X194.502 Y188.039 E4.74546 ; external perimeter
G1 X195.218 Y188.657 E4.75229 ; external perimeter
G1 X195.906 Y189.307 E4.75912 ; external perimeter
G1 X196.563 Y189.987 E4.76594 ; external perimeter
G1 X197.189 Y190.696 E4.77277 ; external perimeter
G1 X197.783 Y191.433 E4.77959 ; external perimeter
G1 X198.342 Y192.196 E4.78642 ; external perimeter
G1 X198.867 Y192.983 E4.79324 ; external perimeter
G1 X199.355 Y193.793 E4.80007 ; external perimeter
G1 X199.806 Y194.625 E4.80689 ; external perimeter
G1 X200.220 Y195.476 E4.81372 ; external perimeter
G1 X200.594 Y196.345 E4.82054 ; external perimeter
G1 X200.929 Y197.229 E4.82737 ; external perimeter
G1 X201.223 Y198.129 E4.83419 ; external perimeter
G1 X201.476 Y199.040 E4.84102 ; external perimeter
G1 X201.688 Y199.962 E4.84784 ; external perimeter
G1 X201.858 Y200.892 E4.85467 ; external perimeter
G1 X201.986 Y201.830 E4.86150 ; external perimeter
G1 X202.072 Y202.772 E4.86832 ; external perimeter
G1 X202.114 Y203.717 E4.87515 ; external perimeter
G1 X202.114 Y204.663 E4.88197 ; external perimeter
G1 X202.072 Y205.608 E4.88880 ; external perimeter
G1 X201.986 Y206.550 E4.89562 ; external perimeter
G1 X201.858 Y207.488 E4.90245 ; external perimeter
G1 X201.688 Y208.418 E4.90927 ; external perimeter
G1 X201.476 Y209.340 E4.91610 ; external perimeter
G1 X201.223 Y210.251 E4.92292 ; external perimeter
G1 X200.929 Y211.151 E4.92975 ; external perimeter
G1 X200.594 Y212.035 E4.93657 ; external perimeter
G1 X200.220 Y212.904 E4.94340 ; external perimeter
G1 X199.806 Y213.755 E4.95022 ; external perimeter
G1 X199.355 Y214.587 E4.95705 ; external perimeter
G1 X198.867 Y215.397 E4.96387 ; external perimeter
G1 X198.342 Y216.184 E4.97070 ; external perimeter
G1 X197.783 Y216.947 E4.97753 ; external perimeter
G1 X197.189 Y217.684 E4.98435 ; external perimeter
G1 X196.563 Y218.393 E4.99118 ; external perimeter
G1 X195.906 Y219.073 E4.99800 ; external perimeter
G1 X195.218 Y219.723 E5.00483 ; external perimeter
G1 X194.502 Y220.341 E5.01165 ; external perimeter
G1 X193.759 Y220.926 E5.01848 ; external perimeter
G1 X192.989 Y221.477 E5.02530 ; external perimeter
G1 X192.196 Y221.992 E5.03213 ; external perimeter
G1 X191.381 Y222.471 E5.03895 ; external perimeter
G1 X190.544 Y222.913 E5.04578 ; external perimeter
G1 X189.689 Y223.317 E5.05260 ; external perimeter
G1 X188.816 Y223.681 E5.05943 ; external perimeter
G1 X187.927 Y224.006 E5.06625 ; external perimeter
G1 X187.025 Y224.290 E5.07308 ; external perimeter
G1 X186.110 Y224.533 E5.07991 ; external perimeter
G1 X185.186 Y224.735 E5.08673 ; external perimeter
G1 X184.254 Y224.894 E5.09356 ; external perimeter
G1 X183.315 Y225.012 E5.10038 ; external perimeter
G1 X182.372 Y225.086 E5.10721 ; external perimeter
G1 X181.427 Y225.118 E5.11403 ; external perimeter
G1 X180.481 Y225.108 E5.12086 ; external perimeter
G1 X179.536 Y225.054 E5.12768 ; external perimeter
G1 X178.595 Y224.958 E5.13451 ; external perimeter
G1 X177.659 Y224.820 E5.14133 ; external perimeter
G1 X176.731 Y224.639 E5.14816 ; external perimeter
G1 X175.811 Y224.417 E5.15498 ; external perimeter
G1 X174.903 Y224.153 E5.16181 ; external perimeter
G1 X174.007 Y223.849 E5.16863 ; external perimeter
G1 X173.126 Y223.504 E5.17546 ; external perimeter
G1 X172.261 Y223.120 E5.18228 ; external perimeter
G1 X171.415 Y222.697 E5.18911 ; external perimeter
G1 X170.589 Y222.236 E5.19594 ; external perimeter
G1 X169.784 Y221.739 E5.20276 ; external perimeter
G1 X169.003 Y221.206 E5.20959 ; external perimeter
G1 X168.246 Y220.638 E5.21641 ; external perimeter
G1 X167.516 Y220.036 E5.22324 ; external perimeter
G1 X166.814 Y219.402 E5.23006 ; external perimeter
G1 X166.142 Y218.737 E5.23689 ; external perimeter
G1 X165.500 Y218.042 E5.24371 ; external perimeter
G1 X164.890 Y217.319 E5.25054 ; external perimeter
G1 X164.313 Y216.569 E5.25736 ; external perimeter
G1 X163.771 Y215.793 E5.26419 ; external perimeter
G1 X163.265 Y214.994 E5.27101 ; external perimeter
G1 X162.795 Y214.173 E5.27784 ; external perimeter
G1 X162.362 Y213.332 E5.28466 ; external perimeter
G1 X161.968 Y212.472 E5.29149 ; external perimeter
G1 X161.614 Y211.595 E5.29832 ; external perimeter
G1 X161.299 Y210.703 E5.30514 ; external perimeter
G1 X161.025 Y209.797 E5.31197 ; external perimeter
G1 X160.792 Y208.880 E5.31879 ; external perimeter
G1 X160.601 Y207.954 E5.32562 ; external perimeter
G1 X160.452 Y207.020 E5.33244 ; external perimeter
G1 X160.346 Y206.080 E5.33927 ; external perimeter
G1 X160.282 Y205.136 E5.34609 ; external perimeter
G1 X160.260 Y204.190 E5.35292 ; external perimeter
G1 X160.282 Y203.244 E5.35974 ; external perimeter
G1 X160.346 Y202.300 E5.36657 ; external perimeter
G1 X160.452 Y201.360 E5.37339 ; external perimeter
G1 X160.601 Y200.426 E5.38022 ; external perimeter
G1 X160.792 Y199.500 E5.38704 ; external perimeter
G1 X161.025 Y198.583 E5.39387 ; external perimeter
G1 X161.299 Y197.677 E5.40069 ; external perimeter
G1 X161.614 Y196.785 E5.40752 ; external perimeter
G1 X161.968 Y195.908 E5.41435 ; external perimeter
G1 X162.362 Y195.048 E5.42117 ; external perimeter
G1 X162.795 Y194.207 E5.42800 ; external perimeter
G1 X163.265 Y193.386 E5.43482 ; external perimeter
G1 X163.771 Y192.587 E5.44165 ; external perimeter
G1 X164.313 Y191.811 E5.44847 ; external perimeter
G1 X164.890 Y191.061 E5.45530 ; external perimeter
G1 X165.500 Y190.338 E5.46212 ; external perimeter
G1 X166.142 Y189.643 E5.46895 ; external perimeter
G1 X166.814 Y188.978 E5.47577 ; external perimeter
G1 X167.377 Y188.470 E5.48124 ; external perimeter
G1 X195.468 Y190.832 F1800.000 ; move to first infill point
G1 F1200.000
G1 X194.394 Y189.758 E5.49957 ; infill
G1 X193.754 Y189.153 E5.51018 ; infill
G1 X193.086 Y188.576 E5.52084 ; infill
G1 X192.391 Y188.030 E5.53149 ; infill
G1 X191.673 Y187.516 E5.54215 ; infill
G1 X190.933 Y187.034 E5.55280 ; infill
G1 X190.171 Y186.587 E5.56346 ; infill
G1 X189.390 Y186.175 E5.57411 ; infill
G1 X188.591 Y185.798 E5.58477 ; infill
G1 X187.469 Y185.345 E5.59936 ; infill
G1 X200.035 Y197.911 E5.81373 ; infill
G1 X200.428 Y199.064 E5.82843 ; infill
G1 X200.665 Y199.915 E5.83908 ; infill
G1 X200.863 Y200.776 E5.84974 ; infill
G1 X200.969 Y201.358 E5.85687 ; infill
G1 X184.023 Y184.411 E6.14596 ; infill
G1 X183.517 Y184.325 E6.15216 ; infill
G1 X182.640 Y184.215 E6.16281 ; infill
G1 X181.760 Y184.145 E6.17347 ; infill
G1 X181.227 Y184.127 E6.17990 ; infill
G1 X201.255 Y204.156 E6.52157 ; infill
G1 X201.261 Y205.165 E6.53375 ; infill
G1 X201.221 Y206.048 E6.54441 ; infill
G1 X201.172 Y206.585 E6.55091 ; infill
G1 X178.795 Y184.208 E6.93266 ; infill
G1 X178.233 Y184.265 E6.93947 ; infill
G1 X177.359 Y184.394 E6.95012 ; infill
G1 X176.614 Y184.539 E6.95928 ; infill
G1 X200.841 Y208.766 E7.37258 ; infill
G1 X200.665 Y209.532 E7.38206 ; infill
G1 X200.309 Y210.747 E7.39732 ; infill
G1 X174.632 Y185.069 E7.83537 ; infill
G1 X173.949 Y185.301 E7.84406 ; infill
G1 X172.813 Y185.762 E7.85886 ; infill
G1 X199.618 Y212.567 E8.31613 ; infill
G1 X199.106 Y213.655 E8.33063 ; infill
G1 X198.785 Y214.246 E8.33875 ; infill
G1 X171.135 Y186.596 E8.81044 ; infill
G1 X170.758 Y186.806 E8.81564 ; infill
G1 X170.007 Y187.271 E8.82630 ; infill
G1 X169.585 Y187.559 E8.83246 ; infill
G1 X197.823 Y215.796 E9.31417 ; infill
G1 X197.216 Y216.635 E9.32665 ; infill
G1 X196.740 Y217.226 E9.33581 ; infill
G1 X168.156 Y188.642 E9.82345 ; infill
G1 X167.234 Y189.453 E9.83826 ; infill
G1 X166.842 Y189.840 E9.84491 ; infill
G1 X195.541 Y218.540 E10.33450 ; infill
G1 X194.822 Y219.227 E10.34650 ; infill
G1 X194.228 Y219.739 E10.35596 ; infill
G1 X165.643 Y191.154 E10.84360 ; infill
G1 X164.898 Y192.098 E10.85811 ; infill
G1 X164.560 Y192.583 E10.86524 ; infill
G1 X192.800 Y220.822 E11.34699 ; infill
G1 X192.000 Y221.346 E11.35852 ; infill
G1 X191.251 Y221.786 E11.36900 ; infill
G1 X163.597 Y194.132 E11.84076 ; infill
G1 X163.077 Y195.120 E11.85424 ; infill
G1 X162.762 Y195.809 E11.86337 ; infill
G1 X189.572 Y222.619 E12.32073 ; infill
G1 X188.844 Y222.923 E12.33025 ; infill
G1 X187.750 Y223.309 E12.34424 ; infill
G1 X162.069 Y197.628 E12.78235 ; infill
G1 X161.829 Y198.421 E12.79234 ; infill
G1 X161.542 Y199.613 E12.80714 ; infill
G1 X185.767 Y223.838 E13.22040 ; infill
G1 X184.584 Y224.055 E13.23490 ; infill
G1 X183.590 Y224.174 E13.24698 ; infill
G1 X161.206 Y201.789 E13.62885 ; infill
G1 X161.134 Y202.773 E13.64075 ; infill
G1 X161.114 Y203.656 E13.65140 ; infill
G1 X161.127 Y204.223 E13.65824 ; infill
G1 X181.160 Y224.256 E13.99999 ; infill
G1 X180.180 Y224.205 E14.01183 ; infill
G1 X179.301 Y224.115 E14.02248 ; infill
G1 X178.366 Y223.974 E14.03389 ; infill
G1 X161.408 Y207.016 E14.32318 ; infill
G1 X161.611 Y208.035 E14.33571 ; infill
G1 X161.829 Y208.892 E14.34637 ; infill
G1 X162.084 Y209.737 E14.35702 ; infill
G1 X162.339 Y210.459 E14.36626 ; infill
G1 X174.921 Y223.041 E14.58090 ; infill
G1 X174.194 Y222.757 E14.59032 ; infill
G1 X173.387 Y222.398 E14.60097 ; infill
G1 X172.597 Y222.004 E14.61163 ; infill
G1 X171.826 Y221.574 E14.62228 ; infill
G1 X171.074 Y221.109 E14.63294 ; infill
G1 X170.345 Y220.611 E14.64359 ; infill
G1 X169.638 Y220.081 E14.65425 ; infill
G1 X168.957 Y219.519 E14.66490 ; infill
G1 X168.301 Y218.927 E14.67556 ; infill
G1 X166.604 Y217.236 E14.70446 ; infill
G1 Z5.050 F1800.000 ; move to next layer (2)
G1 E12.70446 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X167.511 Y188.349 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X168.246 Y187.742 E2.00688 ; external perimeter
G1 X169.003 Y187.174 E2.01371 ; external perimeter
G1 X169.784 Y186.641 E2.02053 ; external perimeter
G1 X170.589 Y186.144 E2.02736 ; external perimeter
G1 X171.415 Y185.683 E2.03418 ; external perimeter
G1 X172.261 Y185.260 E2.04101 ; external perimeter
G1 X173.126 Y184.876 E2.04783 ; external perimeter
G1 X174.007 Y184.531 E2.05466 ; external perimeter
G1 X174.903 Y184.227 E2.06148 ; external perimeter
G1 X175.811 Y183.963 E2.06831 ; external perimeter
G1 X176.731 Y183.741 E2.07513 ; external perimeter
G1 X177.659 Y183.560 E2.08196 ; external perimeter
G1 X178.595 Y183.422 E2.08878 ; external perimeter
G1 X179.536 Y183.326 E2.09561 ; external perimeter
G1 X180.481 Y183.272 E2.10244 ; external perimeter
G1 X181.427 Y183.262 E2.10926 ; external perimeter
G1 X182.372 Y183.294 E2.11609 ; external perimeter
G1 X183.315 Y183.368 E2.12291 ; external perimeter
G1 X184.254 Y183.486 E2.12974 ; external perimeter
G1 X185.186 Y183.645 E2.13656 ; external perimeter
G1 X186.110 Y183.847 E2.14339 ; external perimeter
G1 X187.025 Y184.090 E2.15021 ; external perimeter
G1 X187.927 Y184.374 E2.15704 ; external perimeter
G1 X188.816 Y184.699 E2.16386 ; external perimeter
G1 X189.689 Y185.063 E2.17069 ; external perimeter
G1 X190.544 Y185.467 E2.17751 ; external perimeter
G1 X191.381 Y185.909 E2.18434 ; external perimeter
G1 X192.196 Y186.388 E2.19116 ; external perimeter
G1 X192.989 Y186.903 E2.19799 ; external perimeter
G1 X193.759 Y187.454 E2.20481 ; external perimeter
G1 X194.502 Y188.039 E2.21164 ; external perimeter
G1 X195.218 Y188.657 E2.21847 ; external perimeter
G1 X195.906 Y189.307 E2.22529 ; external perimeter
G1 X196.563 Y189.987 E2.23212 ; external perimeter
G1 X197.189 Y190.696 E2.23894 ; external perimeter
G1 X197.783 Y191.433 E2.24577 ; external perimeter
G1 X198.342 Y192.196 E2.25259 ; external perimeter
G1 X198.867 Y192.983 E2.25942 ; external perimeter
G1 X199.355 Y193.793 E2.26624 ; external perimeter
G1 X199.806 Y194.625 E2.27307 ; external perimeter
G1 X200.220 Y195.476 E2.27989 ; external perimeter
G1 X200.594 Y196.345 E2.28672 ; external perimeter
G1 X200.929 Y197.229 E2.29354 ; external perimeter
G1 X201.223 Y198.129 E2.30037 ; external perimeter
G1 X201.476 Y199.040 E2.30719 ; external perimeter
G1 X201.688 Y199.962 E2.31402 ; external perimeter
G1 X201.858 Y200.892 E2.32085 ; external perimeter
G1 X201.986 Y201.830 E2.32767 ; external perimeter
G1 X202.072 Y202.772 E2.33450 ; external perimeter
G1 X202.114 Y203.717 E2.34132 ; external perimeter
G1 X202.114 Y204.663 E2.34815 ; external perimeter
G1 X202.072 Y205.608 E2.35497 ; external perimeter
G1 X201.986 Y206.550 E2.36180 ; external perimeter
G1 X201.858 Y207.488 E2.36862 ; external perimeter
G1 X201.688 Y208.418 E2.37545 ; external perimeter
G1 X201.476 Y209.340 E2.38227 ; external perimeter
G1 X201.223 Y210.251 E2.38910 ; external perimeter
G1 X200.929 Y211.151 E2.39592 ; external perimeter
G1 X200.594 Y212.035 E2.40275 ; external perimeter
G1 X200.220 Y212.904 E2.40957 ; external perimeter
G1 X199.806 Y213.755 E2.41640 ; external perimeter
G1 X199.355 Y214.587 E2.42322 ; external perimeter
G1 X198.867 Y215.397 E2.43005 ; external perimeter
G1 X198.342 Y216.184 E2.43688 ; external perimeter
G1 X197.783 Y216.947 E2.44370 ; external perimeter
G1 X197.189 Y217.684 E2.45053 ; external perimeter
G1 X196.563 Y218.393 E2.45735 ; external perimeter
G1 X195.906 Y219.073 E2.46418 ; external perimeter
G1 X195.218 Y219.723 E2.47100 ; external perimeter
G1 X194.502 Y220.341 E2.47783 ; external perimeter
G1 X193.759 Y220.926 E2.48465 ; external perimeter
G1 X192.989 Y221.477 E2.49148 ; external perimeter
G1 X192.196 Y221.992 E2.49830 ; external perimeter
G1 X191.381 Y222.471 E2.50513 ; external perimeter
G1 X190.544 Y222.913 E2.51195 ; external perimeter
G1 X189.689 Y223.317 E2.51878 ; external perimeter
G1 X188.816 Y223.681 E2.52560 ; external perimeter
G1 X187.927 Y224.006 E2.53243 ; external perimeter
G1 X187.025 Y224.290 E2.53926 ; external perimeter
G1 X186.110 Y224.533 E2.54608 ; external perimeter
G1 X185.186 Y224.735 E2.55291 ; external perimeter
G1 X184.254 Y224.894 E2.55973 ; external perimeter
G1 X183.315 Y225.012 E2.56656 ; external perimeter
G1 X182.372 Y225.086 E2.57338 ; external perimeter
G1 X181.427 Y225.118 E2.58021 ; external perimeter
G1 X180.481 Y225.108 E2.58703 ; external perimeter
G1 X179.536 Y225.054 E2.59386 ; external perimeter
G1 X178.595 Y224.958 E2.60068 ; external perimeter
G1 X177.659 Y224.820 E2.60751 ; external perimeter
G1 X176.731 Y224.639 E2.61433 ; external perimeter
G1 X175.811 Y224.417 E2.62116 ; external perimeter
G1 X174.903 Y224.153 E2.62798 ; external perimeter
G1 X174.007 Y223.849 E2.63481 ; external perimeter
G1 X173.126 Y223.504 E2.64163 ; external perimeter
G1 X172.261 Y223.120 E2.64846 ; external perimeter
G1 X171.415 Y222.697 E2.65529 ; external perimeter
G1 X170.589 Y222.236 E2.66211 ; external perimeter
G1 X169.784 Y221.739 E2.66894 ; external perimeter
G1 X169.003 Y221.206 E2.67576 ; external perimeter
G1 X168.246 Y220.638 E2.68259 ; external perimeter
G1 X167.516 Y220.036 E2.68941 ; external perimeter
G1 X166.814 Y219.402 E2.69624 ; external perimeter
G1 X166.142 Y218.737 E2.70306 ; external perimeter
G1 X165.500 Y218.042 E2.70989 ; external perimeter
G1 X164.890 Y217.319 E2.71671 ; external perimeter
G1 X164.313 Y216.569 E2.72354 ; external perimeter
G1 X163.771 Y215.793 E2.73036 ; external perimeter
G1 X163.265 Y214.994 E2.73719 ; external perimeter
G1 X162.795 Y214.173 E2.74401 ; external perimeter
G1 X162.362 Y213.332 E2.75084 ; external perimeter
G1 X161.968 Y212.472 E2.75767 ; external perimeter
G1 X161.614 Y211.595 E2.76449 ; external perimeter
G1 X161.299 Y210.703 E2.77132 ; external perimeter
G1 X161.025 Y209.797 E2.77814 ; external perimeter
G1 X160.792 Y208.880 E2.78497 ; external perimeter
G1 X160.601 Y207.954 E2.79179 ; external perimeter
G1 X160.452 Y207.020 E2.79862 ; external perimeter
G1 X160.346 Y206.080 E2.80544 ; external perimeter
G1 X160.282 Y205.136 E2.81227 ; external perimeter
G1 X160.260 Y204.190 E2.81909 ; external perimeter
G1 X160.282 Y203.244 E2.82592 ; external perimeter
G1 X160.346 Y202.300 E2.83274 ; external perimeter
G1 X160.452 Y201.360 E2.83957 ; external perimeter
G1 X160.601 Y200.426 E2.84639 ; external perimeter
G1 X160.792 Y199.500 E2.85322 ; external perimeter
G1 X161.025 Y198.583 E2.86004 ; external perimeter
G1 X161.299 Y197.677 E2.86687 ; external perimeter
G1 X161.614 Y196.785 E2.87370 ; external perimeter
G1 X161.968 Y195.908 E2.88052 ; external perimeter
G1 X162.362 Y195.048 E2.88735 ; external perimeter
G1 X162.795 Y194.207 E2.89417 ; external perimeter
G1 X163.265 Y193.386 E2.90100 ; external perimeter
G1 X163.771 Y192.587 E2.90782 ; external perimeter
G1 X164.313 Y191.811 E2.91465 ; external perimeter
G1 X164.890 Y191.061 E2.92147 ; external perimeter
G1 X165.500 Y190.338 E2.92830 ; external perimeter
G1 X166.142 Y189.643 E2.93512 ; external perimeter
G1 X166.814 Y188.978 E2.94195 ; external perimeter
G1 X167.377 Y188.470 E2.94742 ; external perimeter
G1 E0.94742 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X166.499 Y190.725 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F900.000
G1 X166.481 Y190.743 E2.00017 ; infill
G1 X167.903 Y189.328 E2.01408 ; infill
G1 X168.571 Y188.725 E2.02032 ; infill
G1 X169.266 Y188.152 E2.02656 ; infill
G1 X169.985 Y187.612 E2.03280 ; infill
G1 X170.729 Y187.105 E2.03904 ; infill
G1 X171.494 Y186.631 E2.04528 ; infill
G1 X172.280 Y186.193 E2.05152 ; infill
G1 X172.670 Y185.998 E2.05454 ; infill
G1 X162.996 Y195.672 E2.14940 ; infill
G1 X162.513 Y196.701 E2.15727 ; infill
G1 X162.176 Y197.535 E2.16351 ; infill
G1 X161.957 Y198.155 E2.16807 ; infill
G1 X175.153 Y184.959 E2.29746 ; infill
G1 X175.598 Y184.808 E2.30072 ; infill
G1 X176.462 Y184.557 E2.30696 ; infill
G1 X177.171 Y184.386 E2.31201 ; infill
G1 X161.383 Y200.173 E2.46682 ; infill
G1 X161.213 Y200.999 E2.47267 ; infill
G1 X161.066 Y201.935 E2.47923 ; infill
G1 X178.932 Y184.068 E2.65442 ; infill
G1 X180.006 Y183.950 E2.66192 ; infill
G1 X180.523 Y183.921 E2.66550 ; infill
G1 X160.919 Y203.525 E2.85773 ; infill
G1 X160.888 Y204.580 E2.86505 ; infill
G1 X160.897 Y204.991 E2.86790 ; infill
G1 X181.992 Y183.896 E3.07475 ; infill
G1 X182.704 Y183.920 E3.07969 ; infill
G1 X183.360 Y183.972 E3.08425 ; infill
G1 X160.968 Y206.364 E3.30381 ; infill
G1 X161.130 Y207.646 E3.31277 ; infill
G1 X184.647 Y184.129 E3.54337 ; infill
G1 X185.382 Y184.254 E3.54853 ; infill
G1 X185.861 Y184.359 E3.55193 ; infill
G1 X161.357 Y208.863 E3.79221 ; infill
G1 X161.647 Y210.017 E3.80046 ; infill
G1 X187.017 Y184.647 E4.04922 ; infill
G1 X188.114 Y184.994 E4.05720 ; infill
G1 X161.995 Y211.113 E4.31331 ; infill
G1 X162.176 Y211.625 E4.31708 ; infill
G1 X162.392 Y212.160 E4.32108 ; infill
G1 X189.160 Y185.392 E4.58355 ; infill
G1 X190.159 Y185.837 E4.59113 ; infill
G1 X162.835 Y213.161 E4.85907 ; infill
G1 X163.322 Y214.118 E4.86651 ; infill
G1 X191.116 Y186.324 E5.13904 ; infill
G1 X192.032 Y186.852 E5.14637 ; infill
G1 X163.854 Y215.029 E5.42267 ; infill
G1 X164.426 Y215.902 E5.42990 ; infill
G1 X192.904 Y187.424 E5.70914 ; infill
G1 X193.737 Y188.035 E5.71630 ; infill
G1 X165.036 Y216.736 E5.99773 ; infill
G1 X165.683 Y217.533 E6.00484 ; infill
G1 X194.533 Y188.683 E6.28773 ; infill
G1 X195.292 Y189.368 E6.29482 ; infill
G1 X166.367 Y218.293 E6.57844 ; infill
G1 X167.087 Y219.016 E6.58552 ; infill
G1 X196.014 Y190.090 E6.86916 ; infill
G1 X196.700 Y190.848 E6.87625 ; infill
G1 X167.847 Y219.701 E7.15917 ; infill
G1 X168.645 Y220.347 E7.16628 ; infill
G1 X197.349 Y191.643 E7.44774 ; infill
G1 X197.957 Y192.478 E7.45491 ; infill
G1 X169.480 Y220.956 E7.73414 ; infill
G1 X170.354 Y221.526 E7.74138 ; infill
G1 X198.527 Y193.353 E8.01763 ; infill
G1 X199.056 Y194.268 E8.02495 ; infill
G1 X171.267 Y222.057 E8.29744 ; infill
G1 X172.221 Y222.547 E8.30487 ; infill
G1 X199.545 Y195.223 E8.57280 ; infill
G1 X199.991 Y196.221 E8.58038 ; infill
G1 X173.221 Y222.991 E8.84287 ; infill
G1 X174.270 Y223.386 E8.85064 ; infill
G1 X200.388 Y197.268 E9.10674 ; infill
G1 X200.732 Y198.368 E9.11474 ; infill
G1 X175.368 Y223.732 E9.36344 ; infill
G1 X176.518 Y224.025 E9.37167 ; infill
G1 X201.022 Y199.521 E9.61195 ; infill
G1 X201.253 Y200.735 E9.62051 ; infill
G1 X177.737 Y224.250 E9.85110 ; infill
G1 X178.331 Y224.338 E9.85526 ; infill
G1 X179.023 Y224.409 E9.86008 ; infill
G1 X201.408 Y202.024 E10.07958 ; infill
G1 X201.446 Y202.451 E10.08255 ; infill
G1 X201.487 Y203.389 E10.08905 ; infill
G1 X180.392 Y224.484 E10.29590 ; infill
G1 X181.025 Y224.491 E10.30029 ; infill
G1 X181.857 Y224.463 E10.30606 ; infill
G1 X201.459 Y204.860 E10.49827 ; infill
G1 X201.365 Y206.046 E10.50652 ; infill
G1 X201.309 Y206.454 E10.50938 ; infill
G1 X183.453 Y224.310 E10.68446 ; infill
G1 X184.602 Y224.126 E10.69253 ; infill
G1 X185.216 Y223.992 E10.69689 ; infill
G1 X200.991 Y208.217 E10.85157 ; infill
G1 X200.880 Y208.700 E10.85501 ; infill
G1 X200.639 Y209.567 E10.86125 ; infill
G1 X200.422 Y210.230 E10.86608 ; infill
G1 X187.225 Y223.427 E10.99549 ; infill
G1 X188.055 Y223.123 E11.00161 ; infill
G1 X188.885 Y222.777 E11.00785 ; infill
G1 X189.707 Y222.389 E11.01415 ; infill
G1 X199.381 Y212.714 E11.10901 ; infill
G1 X198.862 Y213.691 E11.11669 ; infill
G1 X198.397 Y214.462 E11.12293 ; infill
G1 X197.898 Y215.211 E11.12917 ; infill
G1 X197.366 Y215.937 E11.13541 ; infill
G1 X196.801 Y216.638 E11.14165 ; infill
G1 X196.206 Y217.312 E11.14789 ; infill
G1 X194.798 Y218.742 E11.16180 ; infill
G1 E9.16180 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = nan
; cog_y = nan
; cog_z = nan
; filament_length_m = 0.0233 
; filament_volume_cm3 = 0.1647
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.04
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 4
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 2.3
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
