; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2022-09-17 at 14:55:49

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z6.520 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X147.752 Y180.924 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X149.113 Y181.064 E2.00326 ; external small perimeter
G1 X149.529 Y181.141 E2.00427 ; external small perimeter
G1 X150.517 Y181.403 E2.00670 ; external small perimeter
G1 X151.061 Y181.588 E2.00807 ; external small perimeter
G1 X151.636 Y181.811 E2.00954 ; external small perimeter
G1 X152.267 Y182.089 E2.01118 ; external small perimeter
G1 X152.892 Y182.395 E2.01284 ; external small perimeter
G1 X153.529 Y182.741 E2.01457 ; external small perimeter
G1 X154.178 Y183.126 E2.01637 ; external small perimeter
G1 X154.825 Y183.545 E2.01820 ; external small perimeter
G1 X155.464 Y183.995 E2.02007 ; external small perimeter
G1 X156.392 Y184.706 E2.02285 ; external small perimeter
G1 X154.025 Y187.968 E2.03246 ; external small perimeter
G1 X153.018 Y187.269 E2.03538 ; external small perimeter
G1 X152.388 Y186.795 E2.03725 ; external small perimeter
G1 X151.779 Y186.297 E2.03913 ; external small perimeter
G1 X151.193 Y185.777 E2.04100 ; external small perimeter
G1 X150.640 Y185.244 E2.04283 ; external small perimeter
G1 X150.128 Y184.706 E2.04460 ; external small perimeter
G1 X149.663 Y184.170 E2.04629 ; external small perimeter
G1 X149.287 Y183.696 E2.04773 ; external small perimeter
G1 X148.956 Y183.238 E2.04908 ; external small perimeter
G1 X148.669 Y182.799 E2.05032 ; external small perimeter
G1 X148.231 Y182.006 E2.05249 ; external small perimeter
G1 X147.825 Y181.088 E2.05487 ; external small perimeter
G1 X149.407 Y182.170 F1800.000 ; move to first infill point
G1 F600.000
G1 X151.534 Y183.664 E2.05950 ; infill
G1 F600.000
G1 X151.735 Y183.811 E2.05997 ; infill
G1 F600.000
G1 X151.935 Y183.958 E2.06046 ; infill
G1 F600.000
G1 X152.159 Y184.118 E2.06104 ; infill
G1 F600.000
G1 X152.385 Y184.284 E2.06165 ; infill
G1 F600.000
G1 X152.576 Y184.421 E2.06219 ; infill
G1 F600.000
G1 X152.905 Y184.662 E2.06315 ; infill
G1 F600.000
G1 X153.348 Y184.983 E2.06449 ; infill
G1 F600.000
G1 X153.600 Y185.158 E2.06527 ; infill
G1 F600.000
G1 X153.660 Y185.182 E2.06544 ; infill
G1 F600.000
G1 X153.720 Y185.206 E2.06562 ; infill
G1 F600.000
G1 X153.779 Y185.230 E2.06581 ; infill
G1 F600.000
G1 X153.839 Y185.255 E2.06600 ; infill
G1 F600.000
G1 X153.898 Y185.279 E2.06620 ; infill
G1 F600.000
G1 X153.958 Y185.303 E2.06641 ; infill
G1 F600.000
G1 X154.018 Y185.328 E2.06663 ; infill
G1 F600.000
G1 X154.077 Y185.352 E2.06686 ; infill
G1 F600.000
G1 X154.137 Y185.376 E2.06709 ; infill
G1 F600.000
G1 X154.197 Y185.400 E2.06734 ; infill
G1 F600.000
G1 X154.256 Y185.425 E2.06759 ; infill
G1 F600.000
G1 X154.316 Y185.449 E2.06784 ; infill
G1 F600.000
G1 X154.376 Y185.473 E2.06811 ; infill
G1 F600.000
G1 X154.435 Y185.498 E2.06838 ; infill
G1 F600.000
G1 X154.495 Y185.522 E2.06866 ; infill
G1 F600.000
G1 X154.554 Y185.546 E2.06895 ; infill
G1 F600.000
G1 X154.584 Y185.558 E2.06910 ; infill
G1 Z7.720 F1800.000 ; move to next layer (1)
G1 X147.260 Y180.583 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X147.583 Y180.495 E2.07061 ; external small perimeter
G1 X147.811 Y180.465 E2.07165 ; external small perimeter
G1 X148.405 Y180.454 E2.07433 ; external small perimeter
G1 X149.183 Y180.534 E2.07786 ; external small perimeter
G1 X150.140 Y180.738 E2.08227 ; external small perimeter
G1 X150.677 Y180.894 E2.08479 ; external small perimeter
G1 X151.244 Y181.087 E2.08749 ; external small perimeter
G1 X151.840 Y181.319 E2.09037 ; external small perimeter
G1 X152.492 Y181.605 E2.09358 ; external small perimeter
G1 X153.136 Y181.921 E2.09682 ; external small perimeter
G1 X153.792 Y182.277 E2.10019 ; external small perimeter
G1 X154.459 Y182.673 E2.10368 ; external small perimeter
G1 X155.123 Y183.103 E2.10725 ; external small perimeter
G1 X155.779 Y183.565 E2.11087 ; external small perimeter
G1 X156.422 Y184.057 E2.11452 ; external small perimeter
G1 X157.109 Y184.625 E2.11854 ; external small perimeter
G1 X154.175 Y188.669 E2.14107 ; external small perimeter
G1 X153.360 Y188.155 E2.14541 ; external small perimeter
G1 X152.705 Y187.701 E2.14900 ; external small perimeter
G1 X152.059 Y187.215 E2.15265 ; external small perimeter
G1 X151.433 Y186.703 E2.15630 ; external small perimeter
G1 X150.831 Y186.169 E2.15992 ; external small perimeter
G1 X150.261 Y185.619 E2.16349 ; external small perimeter
G1 X149.734 Y185.064 E2.16695 ; external small perimeter
G1 X149.252 Y184.510 E2.17026 ; external small perimeter
G1 X148.862 Y184.018 E2.17309 ; external small perimeter
G1 X148.517 Y183.541 E2.17575 ; external small perimeter
G1 X148.216 Y183.080 E2.17823 ; external small perimeter
G1 X147.960 Y182.643 E2.18051 ; external small perimeter
G1 X147.750 Y182.236 E2.18258 ; external small perimeter
G1 X147.566 Y181.821 E2.18462 ; external small perimeter
G1 X147.447 Y181.496 E2.18618 ; external small perimeter
G1 X147.304 Y180.935 E2.18880 ; external small perimeter
G1 X147.282 Y180.762 E2.18958 ; external small perimeter
G1 X148.821 Y181.445 F1800.000 ; move to first infill point
G1 F755.741
G1 X154.502 Y187.125 E2.26087 ; infill
G1 X155.745 Y185.411 F1800.000 ; move to first infill point
G1 F755.741
G1 X154.677 Y184.344 E2.27427 ; infill
G1 Z8.920 F1800.000 ; move to next layer (2)
G1 X147.003 Y180.350 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X147.293 Y180.252 E2.27565 ; external small perimeter
G1 X147.785 Y180.167 E2.27790 ; external small perimeter
G1 X148.417 Y180.155 E2.28075 ; external small perimeter
G1 X149.230 Y180.239 E2.28443 ; external small perimeter
G1 X149.702 Y180.326 E2.28660 ; external small perimeter
G1 X150.217 Y180.449 E2.28898 ; external small perimeter
G1 X150.767 Y180.609 E2.29157 ; external small perimeter
G1 X151.346 Y180.806 E2.29433 ; external small perimeter
G1 X151.954 Y181.042 E2.29727 ; external small perimeter
G1 X152.618 Y181.334 E2.30054 ; external small perimeter
G1 X153.273 Y181.656 E2.30383 ; external small perimeter
G1 X153.940 Y182.016 E2.30725 ; external small perimeter
G1 X154.617 Y182.418 E2.31080 ; external small perimeter
G1 X155.291 Y182.855 E2.31442 ; external small perimeter
G1 X155.956 Y183.324 E2.31809 ; external small perimeter
G1 X156.609 Y183.823 E2.32179 ; external small perimeter
G1 X157.153 Y184.274 E2.32498 ; external small perimeter
G1 X157.267 Y184.400 E2.32575 ; external small perimeter
G1 X157.341 Y184.602 E2.32672 ; external small perimeter
G1 X157.344 Y184.680 E2.32707 ; external small perimeter
G1 X157.312 Y184.831 E2.32777 ; external small perimeter
G1 X157.278 Y184.899 E2.32811 ; external small perimeter
G1 X154.536 Y188.681 E2.34917 ; external small perimeter
G1 X154.416 Y188.809 E2.34996 ; external small perimeter
G1 X154.294 Y188.878 E2.35060 ; external small perimeter
G1 X154.142 Y188.908 E2.35129 ; external small perimeter
G1 X153.923 Y188.862 E2.35230 ; external small perimeter
G1 X153.193 Y188.404 E2.35619 ; external small perimeter
G1 X152.530 Y187.944 E2.35983 ; external small perimeter
G1 X151.874 Y187.450 E2.36353 ; external small perimeter
G1 X151.239 Y186.931 E2.36723 ; external small perimeter
G1 X150.628 Y186.389 E2.37091 ; external small perimeter
G1 X150.049 Y185.830 E2.37454 ; external small perimeter
G1 X149.512 Y185.266 E2.37805 ; external small perimeter
G1 X149.022 Y184.701 E2.38142 ; external small perimeter
G1 X148.623 Y184.199 E2.38432 ; external small perimeter
G1 X148.270 Y183.710 E2.38703 ; external small perimeter
G1 X147.961 Y183.238 E2.38958 ; external small perimeter
G1 X147.698 Y182.788 E2.39193 ; external small perimeter
G1 X147.480 Y182.366 E2.39407 ; external small perimeter
G1 X147.289 Y181.933 E2.39621 ; external small perimeter
G1 X147.068 Y181.266 E2.39937 ; external small perimeter
G1 X146.982 Y180.772 E2.40164 ; external small perimeter
G1 X146.984 Y180.529 E2.40273 ; external small perimeter
G1 X149.176 Y181.029 F1800.000 ; move to first infill point
G1 F985.047
G1 X148.108 Y182.096 E2.41507 ; infill
G1 X148.380 Y182.652 E2.42012 ; infill
G1 X148.608 Y183.041 E2.42380 ; infill
G1 X149.128 Y183.800 E2.43132 ; infill
G1 X151.365 Y181.562 E2.45718 ; infill
G1 X151.957 Y181.791 E2.46236 ; infill
G1 X152.567 Y182.059 E2.46781 ; infill
G1 X153.252 Y182.399 E2.47406 ; infill
G1 X150.385 Y185.265 E2.50718 ; infill
G1 X151.037 Y185.904 E2.51463 ; infill
G1 X151.803 Y186.570 E2.52293 ; infill
G1 X154.959 Y183.414 E2.55941 ; infill
G1 X155.669 Y183.909 E2.56647 ; infill
G1 X156.158 Y184.283 E2.57151 ; infill
G1 X154.429 Y186.668 E2.59558 ; infill
G1 X153.361 Y187.736 E2.60792 ; infill
M106 S255 ; enable fan
G1 Z10.120 F1800.000 ; move to next layer (3)
G1 X146.742 Y180.195 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X147.019 Y180.030 E2.60937 ; external small perimeter
G1 X147.463 Y179.907 E2.61145 ; external small perimeter
G1 X147.759 Y179.869 E2.61280 ; external small perimeter
G1 X148.429 Y179.856 E2.61582 ; external small perimeter
G1 X148.827 Y179.885 E2.61762 ; external small perimeter
G1 X149.277 Y179.943 E2.61966 ; external small perimeter
G1 X149.764 Y180.034 E2.62190 ; external small perimeter
G1 X150.293 Y180.160 E2.62435 ; external small perimeter
G1 X150.856 Y180.323 E2.62699 ; external small perimeter
G1 X151.449 Y180.525 E2.62982 ; external small perimeter
G1 X152.069 Y180.766 E2.63282 ; external small perimeter
G1 X152.744 Y181.063 E2.63614 ; external small perimeter
G1 X153.410 Y181.390 E2.63949 ; external small perimeter
G1 X154.087 Y181.756 E2.64296 ; external small perimeter
G1 X154.774 Y182.164 E2.64656 ; external small perimeter
G1 X155.458 Y182.607 E2.65024 ; external small perimeter
G1 X156.134 Y183.083 E2.65396 ; external small perimeter
G1 X156.795 Y183.589 E2.65772 ; external small perimeter
G1 X157.348 Y184.047 E2.66095 ; external small perimeter
G1 X157.513 Y184.229 E2.66206 ; external small perimeter
G1 X157.613 Y184.444 E2.66313 ; external small perimeter
G1 X157.638 Y184.568 E2.66370 ; external small perimeter
G1 X157.643 Y184.694 E2.66427 ; external small perimeter
G1 X157.590 Y184.941 E2.66541 ; external small perimeter
G1 X157.535 Y185.052 E2.66597 ; external small perimeter
G1 X154.778 Y188.857 E2.68716 ; external small perimeter
G1 X154.606 Y189.040 E2.68829 ; external small perimeter
G1 X154.514 Y189.103 E2.68879 ; external small perimeter
G1 X154.278 Y189.192 E2.68993 ; external small perimeter
G1 X154.026 Y189.201 E2.69107 ; external small perimeter
G1 X153.791 Y189.130 E2.69218 ; external small perimeter
G1 X153.027 Y188.653 E2.69624 ; external small perimeter
G1 X152.355 Y188.186 E2.69993 ; external small perimeter
G1 X151.690 Y187.686 E2.70368 ; external small perimeter
G1 X151.045 Y187.158 E2.70744 ; external small perimeter
G1 X150.425 Y186.608 E2.71118 ; external small perimeter
G1 X149.837 Y186.041 E2.71486 ; external small perimeter
G1 X149.291 Y185.467 E2.71843 ; external small perimeter
G1 X148.792 Y184.892 E2.72187 ; external small perimeter
G1 X148.385 Y184.379 E2.72482 ; external small perimeter
G1 X148.024 Y183.880 E2.72760 ; external small perimeter
G1 X147.707 Y183.395 E2.73021 ; external small perimeter
G1 X147.436 Y182.932 E2.73263 ; external small perimeter
G1 X147.211 Y182.496 E2.73484 ; external small perimeter
G1 X147.011 Y182.045 E2.73707 ; external small perimeter
G1 X146.778 Y181.340 E2.74041 ; external small perimeter
G1 X146.684 Y180.796 E2.74290 ; external small perimeter
G1 X146.677 Y180.582 E2.74387 ; external small perimeter
G1 X146.702 Y180.371 E2.74483 ; external small perimeter
G1 X150.285 Y184.527 F1800.000 ; move to first infill point
G1 F1014.209
G1 X151.901 Y186.123 E2.76363 ; infill
G1 X152.479 Y186.636 E2.77002 ; infill
G1 X153.080 Y187.128 E2.77645 ; infill
G1 X153.701 Y187.596 E2.78288 ; infill
G1 X154.504 Y188.140 E2.79091 ; infill
G1 X155.409 Y186.892 E2.80366 ; infill
G1 X149.516 Y181.000 E2.87262 ; infill
G1 X150.440 Y181.295 E2.88064 ; infill
G1 X151.004 Y181.514 E2.88565 ; infill
G1 X151.625 Y181.787 E2.89127 ; infill
G1 X152.240 Y182.089 E2.89694 ; infill
G1 X152.869 Y182.429 E2.90285 ; infill
G1 X153.509 Y182.810 E2.90901 ; infill
G1 X154.148 Y183.223 E2.91531 ; infill
G1 X154.778 Y183.668 E2.92169 ; infill
G1 X155.397 Y184.141 E2.92815 ; infill
G1 X156.567 Y185.294 E2.94173 ; infill
M106 S247.35 ; enable fan
G1 Z11.320 F1800.000 ; move to next layer (4)
G1 E0.94173 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X146.442 Y180.172 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X146.523 Y180.016 E2.00080 ; external small perimeter
G1 X146.599 Y179.932 E2.00130 ; external small perimeter
G1 X146.769 Y179.816 E2.00223 ; external small perimeter
G1 X147.132 Y179.676 E2.00399 ; external small perimeter
G1 X147.411 Y179.613 E2.00528 ; external small perimeter
G1 X147.733 Y179.571 E2.00674 ; external small perimeter
G1 X148.442 Y179.557 E2.00994 ; external small perimeter
G1 X148.857 Y179.587 E2.01181 ; external small perimeter
G1 X149.324 Y179.648 E2.01394 ; external small perimeter
G1 X149.826 Y179.741 E2.01624 ; external small perimeter
G1 X150.369 Y179.871 E2.01876 ; external small perimeter
G1 X150.946 Y180.038 E2.02147 ; external small perimeter
G1 X151.551 Y180.243 E2.02435 ; external small perimeter
G1 X152.183 Y180.489 E2.02741 ; external small perimeter
G1 X152.870 Y180.791 E2.03079 ; external small perimeter
G1 X153.548 Y181.124 E2.03419 ; external small perimeter
G1 X154.235 Y181.496 E2.03772 ; external small perimeter
G1 X154.932 Y181.910 E2.04137 ; external small perimeter
G1 X155.626 Y182.359 E2.04510 ; external small perimeter
G1 X156.311 Y182.842 E2.04888 ; external small perimeter
G1 X156.982 Y183.355 E2.05269 ; external small perimeter
G1 X157.631 Y183.900 E2.05651 ; external small perimeter
G1 X157.751 Y184.045 E2.05736 ; external small perimeter
G1 X157.839 Y184.197 E2.05815 ; external small perimeter
G1 X157.901 Y184.361 E2.05894 ; external small perimeter
G1 X157.936 Y184.533 E2.05973 ; external small perimeter
G1 X157.942 Y184.708 E2.06052 ; external small perimeter
G1 X157.919 Y184.882 E2.06132 ; external small perimeter
G1 X157.868 Y185.050 E2.06211 ; external small perimeter
G1 X157.792 Y185.206 E2.06289 ; external small perimeter
G1 X154.943 Y189.131 E2.08476 ; external small perimeter
G1 X154.808 Y189.262 E2.08561 ; external small perimeter
G1 X154.664 Y189.362 E2.08640 ; external small perimeter
G1 X154.506 Y189.437 E2.08719 ; external small perimeter
G1 X154.337 Y189.486 E2.08798 ; external small perimeter
G1 X154.163 Y189.506 E2.08877 ; external small perimeter
G1 X153.987 Y189.498 E2.08956 ; external small perimeter
G1 X153.816 Y189.461 E2.09035 ; external small perimeter
G1 X153.641 Y189.392 E2.09120 ; external small perimeter
G1 X152.864 Y188.904 E2.09534 ; external small perimeter
G1 X152.179 Y188.429 E2.09910 ; external small perimeter
G1 X151.505 Y187.921 E2.10290 ; external small perimeter
G1 X150.851 Y187.386 E2.10671 ; external small perimeter
G1 X150.222 Y186.828 E2.11051 ; external small perimeter
G1 X149.625 Y186.252 E2.11425 ; external small perimeter
G1 X149.070 Y185.668 E2.11788 ; external small perimeter
G1 X148.561 Y185.083 E2.12137 ; external small perimeter
G1 X148.147 Y184.560 E2.12438 ; external small perimeter
G1 X147.777 Y184.049 E2.12723 ; external small perimeter
G1 X147.453 Y183.553 E2.12990 ; external small perimeter
G1 X147.174 Y183.076 E2.13239 ; external small perimeter
G1 X146.941 Y182.625 E2.13468 ; external small perimeter
G1 X146.734 Y182.156 E2.13699 ; external small perimeter
G1 X146.591 Y181.766 E2.13887 ; external small perimeter
G1 X146.488 Y181.413 E2.14052 ; external small perimeter
G1 X146.386 Y180.821 E2.14323 ; external small perimeter
G1 X146.378 Y180.577 E2.14433 ; external small perimeter
G1 X146.401 Y180.348 E2.14537 ; external small perimeter
G1 X147.795 Y180.271 F1800.000 ; move to first infill point
G1 F900.000
G1 X147.015 Y181.051 E2.15019 ; infill
G1 X147.091 Y181.573 E2.15250 ; infill
G1 X147.309 Y182.214 E2.15545 ; infill
G1 X149.294 Y180.229 E2.16772 ; infill
G1 X150.005 Y180.347 E2.17087 ; infill
G1 X150.511 Y180.468 E2.17314 ; infill
G1 X147.797 Y183.182 E2.18991 ; infill
G1 X147.928 Y183.407 E2.19105 ; infill
G1 X148.371 Y184.064 E2.19451 ; infill
G1 X151.616 Y180.819 E2.21456 ; infill
G1 X152.647 Y181.244 E2.21944 ; infill
G1 X149.007 Y184.884 E2.24193 ; infill
G1 X149.696 Y185.651 E2.24644 ; infill
G1 X153.625 Y181.722 E2.27072 ; infill
G1 X154.555 Y182.248 E2.27538 ; infill
G1 X150.426 Y186.377 E2.30090 ; infill
G1 X151.196 Y187.063 E2.30541 ; infill
G1 X155.446 Y182.813 E2.33167 ; infill
G1 X156.294 Y183.422 E2.33623 ; infill
G1 X152.007 Y187.709 E2.36272 ; infill
G1 X152.853 Y188.318 E2.36728 ; infill
G1 X157.105 Y184.066 E2.39356 ; infill
G1 X157.310 Y184.253 E2.39477 ; infill
G1 X157.308 Y184.288 E2.39492 ; infill
G1 X154.609 Y188.014 E2.41503 ; infill
G1 X153.755 Y188.872 E2.42032 ; infill
G1 E0.42032 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
M107 ; disable fan
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = 152.195625
; cog_y = 184.116586
; cog_z = 9.589403
; filament_length_m = 0.0014 
; filament_volume_cm3 = 0.0096
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.025
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 8
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 6.17
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
