; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2022-09-17 at 14:55:49

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z6.520 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X199.252 Y164.184 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X199.505 Y165.537 E2.00328 ; external small perimeter
G1 X199.600 Y166.457 E2.00548 ; external small perimeter
G1 X199.618 Y166.990 E2.00676 ; external small perimeter
G1 X199.610 Y167.566 E2.00813 ; external small perimeter
G1 X199.575 Y168.181 E2.00960 ; external small perimeter
G1 X199.506 Y168.867 E2.01124 ; external small perimeter
G1 X199.407 Y169.556 E2.01290 ; external small perimeter
G1 X199.276 Y170.269 E2.01462 ; external small perimeter
G1 X199.110 Y171.005 E2.01642 ; external small perimeter
G1 X198.912 Y171.750 E2.01826 ; external small perimeter
G1 X198.681 Y172.496 E2.02012 ; external small perimeter
G1 X198.291 Y173.601 E2.02291 ; external small perimeter
G1 X194.458 Y172.353 E2.03252 ; external small perimeter
G1 X194.811 Y171.182 E2.03543 ; external small perimeter
G1 X195.067 Y170.437 E2.03731 ; external small perimeter
G1 X195.353 Y169.703 E2.03919 ; external small perimeter
G1 X195.666 Y168.986 E2.04105 ; external small perimeter
G1 X196.003 Y168.294 E2.04288 ; external small perimeter
G1 X196.356 Y167.642 E2.04465 ; external small perimeter
G1 X196.722 Y167.033 E2.04634 ; external small perimeter
G1 X197.057 Y166.530 E2.04778 ; external small perimeter
G1 X197.390 Y166.073 E2.04913 ; external small perimeter
G1 X197.718 Y165.665 E2.05038 ; external small perimeter
G1 X198.338 Y165.003 E2.05254 ; external small perimeter
G1 X199.118 Y164.304 E2.05504 ; external small perimeter
G1 X198.545 Y166.172 F1800.000 ; move to first infill point
G1 F600.000
G1 X198.163 Y167.415 E2.05735 ; infill
G1 F600.000
G1 X197.742 Y168.775 E2.06002 ; infill
G1 F600.000
G1 X197.665 Y169.011 E2.06052 ; infill
G1 F600.000
G1 X197.586 Y169.258 E2.06106 ; infill
G1 F600.000
G1 X197.498 Y169.524 E2.06167 ; infill
G1 F600.000
G1 X197.411 Y169.791 E2.06231 ; infill
G1 F600.000
G1 X197.320 Y170.075 E2.06302 ; infill
G1 F600.000
G1 X197.173 Y170.528 E2.06419 ; infill
G1 F600.000
G1 X197.002 Y171.051 E2.06559 ; infill
G1 F600.000
G1 X196.997 Y171.115 E2.06576 ; infill
G1 F600.000
G1 X196.992 Y171.180 E2.06594 ; infill
G1 F600.000
G1 X196.987 Y171.244 E2.06612 ; infill
G1 F600.000
G1 X196.983 Y171.308 E2.06632 ; infill
G1 F600.000
G1 X196.978 Y171.372 E2.06652 ; infill
G1 F600.000
G1 X196.973 Y171.437 E2.06673 ; infill
G1 F600.000
G1 X196.968 Y171.501 E2.06695 ; infill
G1 F600.000
G1 X196.964 Y171.565 E2.06718 ; infill
G1 F600.000
G1 X196.959 Y171.629 E2.06741 ; infill
G1 F600.000
G1 X196.954 Y171.693 E2.06765 ; infill
G1 F600.000
G1 X196.950 Y171.758 E2.06790 ; infill
G1 F600.000
G1 X196.945 Y171.822 E2.06816 ; infill
G1 F600.000
G1 X196.940 Y171.886 E2.06843 ; infill
G1 F600.000
G1 X196.935 Y171.950 E2.06870 ; infill
G1 F600.000
G1 X196.931 Y172.015 E2.06898 ; infill
G1 F600.000
G1 X196.926 Y172.079 E2.06927 ; infill
G1 F600.000
G1 X196.921 Y172.143 E2.06957 ; infill
G1 Z7.720 F1800.000 ; move to next layer (1)
G1 X199.058 Y163.798 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X199.449 Y163.634 E2.07148 ; external small perimeter
G1 X199.772 Y164.386 E2.07518 ; external small perimeter
G1 X199.956 Y165.050 E2.07828 ; external small perimeter
G1 X200.092 Y165.914 E2.08223 ; external small perimeter
G1 X200.133 Y166.427 E2.08455 ; external small perimeter
G1 X200.151 Y166.985 E2.08707 ; external small perimeter
G1 X200.143 Y167.584 E2.08977 ; external small perimeter
G1 X200.106 Y168.223 E2.09265 ; external small perimeter
G1 X200.035 Y168.931 E2.09586 ; external small perimeter
G1 X199.934 Y169.642 E2.09910 ; external small perimeter
G1 X199.798 Y170.376 E2.10246 ; external small perimeter
G1 X199.628 Y171.132 E2.10596 ; external small perimeter
G1 X199.424 Y171.897 E2.10953 ; external small perimeter
G1 X199.187 Y172.664 E2.11315 ; external small perimeter
G1 X198.919 Y173.425 E2.11679 ; external small perimeter
G1 X198.584 Y174.257 E2.12083 ; external small perimeter
G1 X193.839 Y172.712 E2.14334 ; external small perimeter
G1 X194.074 Y171.781 E2.14767 ; external small perimeter
G1 X194.303 Y171.018 E2.15126 ; external small perimeter
G1 X194.567 Y170.253 E2.15491 ; external small perimeter
G1 X194.860 Y169.500 E2.15855 ; external small perimeter
G1 X195.182 Y168.762 E2.16218 ; external small perimeter
G1 X195.528 Y168.051 E2.16575 ; external small perimeter
G1 X195.893 Y167.377 E2.16920 ; external small perimeter
G1 X196.271 Y166.748 E2.17251 ; external small perimeter
G1 X196.619 Y166.225 E2.17535 ; external small perimeter
G1 X196.966 Y165.749 E2.17800 ; external small perimeter
G1 X197.311 Y165.320 E2.18048 ; external small perimeter
G1 X197.648 Y164.942 E2.18277 ; external small perimeter
G1 X197.970 Y164.616 E2.18483 ; external small perimeter
G1 X198.308 Y164.314 E2.18688 ; external small perimeter
G1 X198.580 Y164.100 E2.18844 ; external small perimeter
G1 X198.906 Y163.894 E2.19018 ; external small perimeter
G1 X199.214 Y166.405 F1800.000 ; move to first infill point
G1 F859.625
G1 X198.146 Y165.338 E2.20358 ; infill
G1 X197.534 Y166.060 E2.21197 ; infill
G1 X197.224 Y166.484 E2.21664 ; infill
G1 X196.872 Y167.021 E2.22233 ; infill
G1 X199.186 Y169.335 E2.25138 ; infill
G1 X199.098 Y169.952 E2.25691 ; infill
G1 X198.973 Y170.631 E2.26304 ; infill
G1 X198.691 Y171.797 E2.27368 ; infill
G1 X195.846 Y168.952 E2.30938 ; infill
G1 X195.609 Y169.495 E2.31464 ; infill
G1 X195.336 Y170.197 E2.32133 ; infill
G1 X195.034 Y171.097 E2.32975 ; infill
G1 X196.376 Y172.439 E2.34659 ; infill
G1 X196.051 Y172.333 E2.34962 ; infill
G1 X196.102 Y172.165 E2.35118 ; infill
G1 Z8.920 F1800.000 ; move to next layer (2)
G1 X199.716 Y163.569 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X199.949 Y164.011 E2.35343 ; external small perimeter
G1 X200.155 Y164.608 E2.35628 ; external small perimeter
G1 X200.327 Y165.407 E2.35997 ; external small perimeter
G1 X200.389 Y165.883 E2.36213 ; external small perimeter
G1 X200.432 Y166.410 E2.36452 ; external small perimeter
G1 X200.450 Y166.983 E2.36710 ; external small perimeter
G1 X200.442 Y167.595 E2.36986 ; external small perimeter
G1 X200.405 Y168.246 E2.37280 ; external small perimeter
G1 X200.332 Y168.968 E2.37607 ; external small perimeter
G1 X200.229 Y169.690 E2.37936 ; external small perimeter
G1 X200.092 Y170.435 E2.38278 ; external small perimeter
G1 X199.919 Y171.204 E2.38633 ; external small perimeter
G1 X199.712 Y171.980 E2.38995 ; external small perimeter
G1 X199.471 Y172.758 E2.39363 ; external small perimeter
G1 X199.199 Y173.530 E2.39732 ; external small perimeter
G1 X198.902 Y174.265 E2.40089 ; external small perimeter
G1 X198.751 Y174.432 E2.40191 ; external small perimeter
G1 X198.611 Y174.496 E2.40260 ; external small perimeter
G1 X198.472 Y174.512 E2.40323 ; external small perimeter
G1 X198.299 Y174.479 E2.40403 ; external small perimeter
G1 X193.857 Y173.031 E2.42509 ; external small perimeter
G1 X193.791 Y172.996 E2.42543 ; external small perimeter
G1 X193.676 Y172.893 E2.42613 ; external small perimeter
G1 X193.632 Y172.829 E2.42648 ; external small perimeter
G1 X193.580 Y172.683 E2.42718 ; external small perimeter
G1 X193.576 Y172.535 E2.42784 ; external small perimeter
G1 X193.786 Y171.700 E2.43173 ; external small perimeter
G1 X194.019 Y170.926 E2.43537 ; external small perimeter
G1 X194.286 Y170.150 E2.43907 ; external small perimeter
G1 X194.583 Y169.385 E2.44277 ; external small perimeter
G1 X194.910 Y168.637 E2.44645 ; external small perimeter
G1 X195.262 Y167.914 E2.45008 ; external small perimeter
G1 X195.633 Y167.229 E2.45359 ; external small perimeter
G1 X196.019 Y166.588 E2.45696 ; external small perimeter
G1 X196.373 Y166.054 E2.45986 ; external small perimeter
G1 X196.729 Y165.567 E2.46258 ; external small perimeter
G1 X197.083 Y165.127 E2.46512 ; external small perimeter
G1 X197.429 Y164.738 E2.46747 ; external small perimeter
G1 X197.763 Y164.400 E2.46961 ; external small perimeter
G1 X198.116 Y164.084 E2.47175 ; external small perimeter
G1 X198.412 Y163.852 E2.47345 ; external small perimeter
G1 X198.907 Y163.538 E2.47609 ; external small perimeter
G1 X199.303 Y163.372 E2.47802 ; external small perimeter
G1 X199.533 Y163.324 E2.47908 ; external small perimeter
G1 X199.608 Y163.425 E2.47965 ; external small perimeter
G1 X199.531 Y165.408 F1800.000 ; move to first infill point
G1 F936.604
G1 X196.088 Y168.851 E2.52287 ; infill
G1 X195.636 Y169.752 E2.53182 ; infill
G1 X195.332 Y170.449 E2.53856 ; infill
G1 X195.055 Y171.162 E2.54535 ; infill
G1 X194.806 Y171.886 E2.55214 ; infill
G1 X194.613 Y172.526 E2.55808 ; infill
G1 X195.184 Y172.712 E2.56341 ; infill
G1 X199.465 Y168.431 E2.61713 ; infill
G1 X199.266 Y169.624 E2.62786 ; infill
G1 X199.105 Y170.338 E2.63436 ; infill
G1 X198.912 Y171.062 E2.64101 ; infill
G1 X198.687 Y171.788 E2.64775 ; infill
G1 X198.482 Y172.371 E2.65324 ; infill
G1 X197.414 Y173.439 E2.66664 ; infill
M106 S255 ; enable fan
G1 Z10.120 F1800.000 ; move to next layer (3)
G1 X199.851 Y163.252 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X200.096 Y163.624 E2.66865 ; external small perimeter
G1 X200.224 Y163.894 E2.67000 ; external small perimeter
G1 X200.444 Y164.527 E2.67302 ; external small perimeter
G1 X200.622 Y165.360 E2.67686 ; external small perimeter
G1 X200.687 Y165.852 E2.67909 ; external small perimeter
G1 X200.730 Y166.394 E2.68155 ; external small perimeter
G1 X200.749 Y166.980 E2.68419 ; external small perimeter
G1 X200.741 Y167.606 E2.68701 ; external small perimeter
G1 X200.703 Y168.270 E2.69001 ; external small perimeter
G1 X200.629 Y169.004 E2.69334 ; external small perimeter
G1 X200.524 Y169.738 E2.69669 ; external small perimeter
G1 X200.385 Y170.495 E2.70016 ; external small perimeter
G1 X200.209 Y171.275 E2.70376 ; external small perimeter
G1 X199.999 Y172.062 E2.70744 ; external small perimeter
G1 X199.755 Y172.852 E2.71116 ; external small perimeter
G1 X199.478 Y173.637 E2.71492 ; external small perimeter
G1 X199.214 Y174.304 E2.71815 ; external small perimeter
G1 X199.092 Y174.517 E2.71926 ; external small perimeter
G1 X198.919 Y174.680 E2.72033 ; external small perimeter
G1 X198.689 Y174.785 E2.72147 ; external small perimeter
G1 X198.453 Y174.810 E2.72254 ; external small perimeter
G1 X198.206 Y174.764 E2.72367 ; external small perimeter
G1 X193.846 Y173.347 E2.74435 ; external small perimeter
G1 X193.618 Y173.239 E2.74548 ; external small perimeter
G1 X193.442 Y173.080 E2.74655 ; external small perimeter
G1 X193.371 Y172.975 E2.74712 ; external small perimeter
G1 X193.319 Y172.860 E2.74769 ; external small perimeter
G1 X193.273 Y172.612 E2.74883 ; external small perimeter
G1 X193.280 Y172.492 E2.74937 ; external small perimeter
G1 X193.498 Y171.619 E2.75343 ; external small perimeter
G1 X193.734 Y170.835 E2.75712 ; external small perimeter
G1 X194.005 Y170.048 E2.76088 ; external small perimeter
G1 X194.307 Y169.271 E2.76463 ; external small perimeter
G1 X194.638 Y168.512 E2.76837 ; external small perimeter
G1 X194.996 Y167.777 E2.77205 ; external small perimeter
G1 X195.374 Y167.081 E2.77563 ; external small perimeter
G1 X195.766 Y166.428 E2.77906 ; external small perimeter
G1 X196.128 Y165.883 E2.78201 ; external small perimeter
G1 X196.491 Y165.385 E2.78479 ; external small perimeter
G1 X196.854 Y164.934 E2.78740 ; external small perimeter
G1 X197.211 Y164.533 E2.78982 ; external small perimeter
G1 X197.557 Y164.184 E2.79204 ; external small perimeter
G1 X197.924 Y163.855 E2.79426 ; external small perimeter
G1 X198.522 Y163.415 E2.79761 ; external small perimeter
G1 X199.010 Y163.158 E2.80010 ; external small perimeter
G1 X199.348 Y163.051 E2.80170 ; external small perimeter
G1 X199.629 Y163.034 E2.80296 ; external small perimeter
G1 X199.723 Y163.126 E2.80356 ; external small perimeter
G1 X199.582 Y165.272 F1800.000 ; move to first infill point
G1 F1069.507
G1 X198.514 Y164.204 E2.81683 ; infill
G1 X197.980 Y164.656 E2.82298 ; infill
G1 X197.689 Y164.949 E2.82661 ; infill
G1 X197.067 Y165.686 E2.83509 ; infill
G1 X199.865 Y168.485 E2.86989 ; infill
G1 X199.785 Y169.370 E2.87771 ; infill
G1 X199.688 Y170.048 E2.88373 ; infill
G1 X199.493 Y171.042 E2.89264 ; infill
G1 X195.919 Y167.468 E2.93708 ; infill
G1 X195.697 Y167.878 E2.94118 ; infill
G1 X195.365 Y168.560 E2.94785 ; infill
G1 X194.981 Y169.460 E2.95645 ; infill
G1 X198.841 Y173.320 E3.00444 ; infill
G1 X198.662 Y173.813 E3.00906 ; infill
G1 X195.319 Y172.727 E3.03996 ; infill
G1 X194.251 Y171.659 E3.05324 ; infill
M106 S247.35 ; enable fan
G1 Z11.320 F1800.000 ; move to next layer (4)
G1 E1.05324 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X199.692 Y162.759 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X199.805 Y162.810 E2.00056 ; external small perimeter
G1 X199.968 Y162.936 E2.00149 ; external small perimeter
G1 X200.072 Y163.047 E2.00218 ; external small perimeter
G1 X200.214 Y163.238 E2.00325 ; external small perimeter
G1 X200.360 Y163.484 E2.00454 ; external small perimeter
G1 X200.504 Y163.787 E2.00605 ; external small perimeter
G1 X200.621 Y164.089 E2.00751 ; external small perimeter
G1 X200.832 Y164.851 E2.01108 ; external small perimeter
G1 X200.918 Y165.313 E2.01320 ; external small perimeter
G1 X200.984 Y165.820 E2.01550 ; external small perimeter
G1 X201.029 Y166.377 E2.01802 ; external small perimeter
G1 X201.048 Y166.977 E2.02073 ; external small perimeter
G1 X201.040 Y167.616 E2.02361 ; external small perimeter
G1 X201.001 Y168.293 E2.02667 ; external small perimeter
G1 X200.926 Y169.040 E2.03005 ; external small perimeter
G1 X200.819 Y169.787 E2.03346 ; external small perimeter
G1 X200.678 Y170.555 E2.03698 ; external small perimeter
G1 X200.500 Y171.346 E2.04064 ; external small perimeter
G1 X200.287 Y172.145 E2.04436 ; external small perimeter
G1 X200.039 Y172.945 E2.04814 ; external small perimeter
G1 X199.758 Y173.742 E2.05195 ; external small perimeter
G1 X199.480 Y174.445 E2.05536 ; external small perimeter
G1 X199.340 Y174.687 E2.05662 ; external small perimeter
G1 X199.223 Y174.818 E2.05741 ; external small perimeter
G1 X199.086 Y174.927 E2.05820 ; external small perimeter
G1 X198.933 Y175.013 E2.05899 ; external small perimeter
G1 X198.768 Y175.073 E2.05978 ; external small perimeter
G1 X198.596 Y175.106 E2.06058 ; external small perimeter
G1 X198.420 Y175.109 E2.06137 ; external small perimeter
G1 X198.140 Y175.056 E2.06266 ; external small perimeter
G1 X193.635 Y173.588 E2.08402 ; external small perimeter
G1 X193.469 Y173.501 E2.08487 ; external small perimeter
G1 X193.329 Y173.395 E2.08566 ; external small perimeter
G1 X193.209 Y173.267 E2.08645 ; external small perimeter
G1 X193.111 Y173.122 E2.08724 ; external small perimeter
G1 X193.037 Y172.962 E2.08803 ; external small perimeter
G1 X192.991 Y172.793 E2.08882 ; external small perimeter
G1 X192.973 Y172.618 E2.08961 ; external small perimeter
G1 X192.984 Y172.449 E2.09038 ; external small perimeter
G1 X193.210 Y171.538 E2.09461 ; external small perimeter
G1 X193.449 Y170.743 E2.09835 ; external small perimeter
G1 X193.724 Y169.945 E2.10216 ; external small perimeter
G1 X194.030 Y169.157 E2.10597 ; external small perimeter
G1 X194.367 Y168.386 E2.10976 ; external small perimeter
G1 X194.730 Y167.640 E2.11351 ; external small perimeter
G1 X195.114 Y166.932 E2.11714 ; external small perimeter
G1 X195.513 Y166.268 E2.12063 ; external small perimeter
G1 X195.882 Y165.712 E2.12364 ; external small perimeter
G1 X196.254 Y165.203 E2.12648 ; external small perimeter
G1 X196.626 Y164.741 E2.12916 ; external small perimeter
G1 X196.993 Y164.328 E2.13165 ; external small perimeter
G1 X197.350 Y163.967 E2.13394 ; external small perimeter
G1 X197.732 Y163.625 E2.13625 ; external small perimeter
G1 X198.059 Y163.369 E2.13812 ; external small perimeter
G1 X198.363 Y163.162 E2.13978 ; external small perimeter
G1 X198.641 Y163.001 E2.14123 ; external small perimeter
G1 X199.124 Y162.799 E2.14359 ; external small perimeter
G1 X199.319 Y162.750 E2.14450 ; external small perimeter
G1 X199.514 Y162.736 E2.14538 ; external small perimeter
G1 X198.443 Y164.314 F1800.000 ; move to first infill point
G1 F900.000
G1 X197.345 Y165.415 E2.15303 ; infill
G1 X197.013 Y165.788 E2.15549 ; infill
G1 X196.672 Y166.212 E2.15817 ; infill
G1 X196.328 Y166.683 E2.16104 ; infill
G1 X195.983 Y167.202 E2.16410 ; infill
G1 X195.608 Y167.827 E2.16769 ; infill
G1 X195.245 Y168.496 E2.17144 ; infill
G1 X194.901 Y169.203 E2.17531 ; infill
G1 X194.674 Y169.722 E2.17810 ; infill
G1 X200.116 Y164.281 E2.21597 ; infill
G1 X200.229 Y164.690 E2.21807 ; infill
G1 X200.303 Y165.083 E2.22003 ; infill
G1 X200.372 Y165.664 E2.22291 ; infill
G1 X193.789 Y172.247 E2.26873 ; infill
G1 X193.604 Y172.992 E2.27251 ; infill
G1 X193.643 Y173.038 E2.27280 ; infill
G1 X194.394 Y173.282 E2.27669 ; infill
G1 X200.408 Y167.268 E2.31855 ; infill
G1 X200.376 Y167.823 E2.32129 ; infill
G1 X200.306 Y168.527 E2.32477 ; infill
G1 X200.225 Y169.091 E2.32757 ; infill
G1 X195.631 Y173.686 E2.35955 ; infill
G1 X196.868 Y174.089 E2.36595 ; infill
G1 X199.777 Y171.179 E2.38620 ; infill
G1 X199.463 Y172.236 E2.39163 ; infill
G1 X199.195 Y172.996 E2.39560 ; infill
G1 X198.952 Y173.610 E2.39885 ; infill
G1 X198.905 Y173.691 E2.39931 ; infill
G1 X198.125 Y174.471 E2.40474 ; infill
G1 E0.40474 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
M107 ; disable fan
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = 197.520691
; cog_y = 169.443971
; cog_z = 9.481423
; filament_length_m = 0.0015 
; filament_volume_cm3 = 0.0103
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.025
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 8
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 6.17
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
