; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2022-09-17 at 14:55:48

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z4.550 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X213.701 Y199.807 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X214.488 Y199.637 E2.00169 ; external perimeter
G1 X216.081 Y199.373 E2.00507 ; external perimeter
G1 X217.733 Y199.176 E2.00856 ; external perimeter
G1 X219.414 Y199.052 E2.01210 ; external perimeter
G1 X221.097 Y199.001 E2.01563 ; external perimeter
G1 X222.778 Y199.024 E2.01915 ; external perimeter
G1 X224.466 Y199.120 E2.02270 ; external perimeter
G1 X226.150 Y199.292 E2.02625 ; external perimeter
G1 X227.742 Y199.527 E2.02962 ; external perimeter
G1 X229.305 Y199.834 E2.03296 ; external perimeter
G1 X230.834 Y200.214 E2.03627 ; external perimeter
G1 X232.263 Y200.651 E2.03940 ; external perimeter
G1 X233.600 Y201.143 E2.04238 ; external perimeter
G1 X234.844 Y201.691 E2.04524 ; external perimeter
G1 X235.985 Y202.290 E2.04794 ; external perimeter
G1 X236.997 Y202.922 E2.05044 ; external perimeter
G1 X237.888 Y203.591 E2.05278 ; external perimeter
G1 X238.652 Y204.288 E2.05494 ; external perimeter
G1 X239.268 Y204.990 E2.05690 ; external perimeter
G1 X239.752 Y205.703 E2.05871 ; external perimeter
G1 X240.100 Y206.413 E2.06037 ; external perimeter
G1 X240.320 Y207.128 E2.06194 ; external perimeter
G1 X240.411 Y207.815 E2.06339 ; external perimeter
G1 X240.383 Y208.504 E2.06483 ; external perimeter
G1 X240.232 Y209.212 E2.06635 ; external perimeter
G1 X239.956 Y209.915 E2.06794 ; external perimeter
G1 X239.546 Y210.625 E2.06966 ; external perimeter
G1 X238.994 Y211.342 E2.07155 ; external perimeter
G1 X238.308 Y212.043 E2.07361 ; external perimeter
G1 X237.483 Y212.728 E2.07586 ; external perimeter
G1 X236.531 Y213.382 E2.07828 ; external perimeter
G1 X235.458 Y213.999 E2.08088 ; external perimeter
G1 X234.283 Y214.567 E2.08361 ; external perimeter
G1 X232.979 Y215.096 E2.08656 ; external perimeter
G1 X231.590 Y215.565 E2.08964 ; external perimeter
G1 X230.130 Y215.971 E2.09282 ; external perimeter
G1 X228.587 Y216.316 E2.09613 ; external perimeter
G1 X226.989 Y216.593 E2.09953 ; external perimeter
G1 X225.358 Y216.798 E2.10298 ; external perimeter
G1 X223.700 Y216.932 E2.10647 ; external perimeter
G1 X221.992 Y216.995 E2.11005 ; external perimeter
G1 X220.304 Y216.984 E2.11359 ; external perimeter
G1 X218.618 Y216.898 E2.11713 ; external perimeter
G1 X216.949 Y216.740 E2.12064 ; external perimeter
G1 X215.323 Y216.510 E2.12409 ; external perimeter
G1 X213.701 Y216.204 E2.12755 ; external perimeter
G1 X213.701 Y199.987 E2.16155 ; external perimeter
G1 E0.16155 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X214.878 Y202.148 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X216.375 Y200.651 E2.00454 ; infill
G1 X217.101 Y200.530 E2.00611 ; infill
G1 X218.667 Y200.344 E2.00949 ; infill
G1 X219.528 Y200.280 E2.01134 ; infill
G1 X214.878 Y204.930 E2.02543 ; infill
G1 X214.878 Y207.712 E2.03140 ; infill
G1 X222.405 Y200.185 E2.05421 ; infill
G1 X223.459 Y200.199 E2.05647 ; infill
G1 X225.079 Y200.292 E2.05994 ; infill
G1 X214.878 Y210.494 E2.09086 ; infill
G1 X214.878 Y213.276 E2.09682 ; infill
G1 X227.566 Y200.588 E2.13527 ; infill
G1 X228.164 Y200.676 E2.13657 ; infill
G1 X229.904 Y201.032 E2.14038 ; infill
G1 X215.491 Y215.444 E2.18405 ; infill
G1 X216.426 Y215.576 E2.18608 ; infill
G1 X217.992 Y215.725 E2.18945 ; infill
G1 X232.086 Y201.632 E2.23216 ; infill
G1 X232.397 Y201.727 E2.23285 ; infill
G1 X233.627 Y202.180 E2.23566 ; infill
G1 X234.108 Y202.392 E2.23679 ; infill
G1 X220.685 Y215.815 E2.27747 ; infill
G1 X221.215 Y215.819 E2.27860 ; infill
G1 X222.838 Y215.759 E2.28208 ; infill
G1 X223.583 Y215.699 E2.28369 ; infill
G1 X235.956 Y203.325 E2.32118 ; infill
G1 X236.656 Y203.763 E2.32295 ; infill
G1 X237.407 Y204.326 E2.32496 ; infill
G1 X237.580 Y204.484 E2.32547 ; infill
G1 X226.767 Y215.297 E2.35823 ; infill
G1 X227.464 Y215.176 E2.35975 ; infill
G1 X228.913 Y214.852 E2.36293 ; infill
G1 X230.421 Y214.424 E2.36629 ; infill
G1 X238.862 Y205.984 E2.39187 ; infill
G1 X239.053 Y206.375 E2.39280 ; infill
G1 X239.181 Y206.792 E2.39374 ; infill
G1 X239.230 Y207.155 E2.39452 ; infill
G1 X239.215 Y207.513 E2.39529 ; infill
G1 X239.131 Y207.906 E2.39615 ; infill
G1 X238.965 Y208.329 E2.39713 ; infill
G1 X238.691 Y208.804 E2.39830 ; infill
G1 X238.287 Y209.329 E2.39972 ; infill
G1 X236.253 Y211.375 E2.40590 ; infill
G1 Z5.750 F1800.000 ; move to next layer (1)
G1 E0.40590 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X213.361 Y199.532 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X214.420 Y199.304 E2.00430 ; external perimeter
G1 X216.008 Y199.040 E2.01069 ; external perimeter
G1 X217.699 Y198.837 E2.01744 ; external perimeter
G1 X219.430 Y198.711 E2.02433 ; external perimeter
G1 X221.094 Y198.661 E2.03094 ; external perimeter
G1 X222.732 Y198.683 E2.03744 ; external perimeter
G1 X224.561 Y198.787 E2.04471 ; external perimeter
G1 X226.173 Y198.951 E2.05114 ; external perimeter
G1 X227.760 Y199.185 E2.05750 ; external perimeter
G1 X229.394 Y199.505 E2.06411 ; external perimeter
G1 X231.013 Y199.912 E2.07073 ; external perimeter
G1 X232.365 Y200.326 E2.07635 ; external perimeter
G1 X233.727 Y200.828 E2.08211 ; external perimeter
G1 X234.991 Y201.385 E2.08759 ; external perimeter
G1 X236.179 Y202.009 E2.09291 ; external perimeter
G1 X237.189 Y202.642 E2.09764 ; external perimeter
G1 X238.105 Y203.328 E2.10218 ; external perimeter
G1 X238.917 Y204.074 E2.10656 ; external perimeter
G1 X239.537 Y204.781 E2.11029 ; external perimeter
G1 X240.047 Y205.532 E2.11389 ; external perimeter
G1 X240.416 Y206.285 E2.11722 ; external perimeter
G1 X240.661 Y207.103 E2.12061 ; external perimeter
G1 X240.752 Y207.799 E2.12339 ; external perimeter
G1 X240.725 Y208.515 E2.12624 ; external perimeter
G1 X240.558 Y209.310 E2.12946 ; external perimeter
G1 X240.249 Y210.090 E2.13279 ; external perimeter
G1 X239.826 Y210.820 E2.13614 ; external perimeter
G1 X239.289 Y211.520 E2.13964 ; external perimeter
G1 X238.538 Y212.294 E2.14392 ; external perimeter
G1 X237.692 Y212.997 E2.14828 ; external perimeter
G1 X236.718 Y213.667 E2.15298 ; external perimeter
G1 X235.597 Y214.310 E2.15810 ; external perimeter
G1 X234.412 Y214.882 E2.16332 ; external perimeter
G1 X233.161 Y215.391 E2.16868 ; external perimeter
G1 X231.739 Y215.875 E2.17464 ; external perimeter
G1 X230.212 Y216.301 E2.18094 ; external perimeter
G1 X228.630 Y216.654 E2.18737 ; external perimeter
G1 X226.999 Y216.935 E2.19393 ; external perimeter
G1 X225.393 Y217.137 E2.20036 ; external perimeter
G1 X223.775 Y217.268 E2.20680 ; external perimeter
G1 X222.002 Y217.335 E2.21384 ; external perimeter
G1 X220.309 Y217.324 E2.22056 ; external perimeter
G1 X218.587 Y217.237 E2.22740 ; external perimeter
G1 X216.875 Y217.073 E2.23422 ; external perimeter
G1 X215.234 Y216.840 E2.24080 ; external perimeter
G1 X213.361 Y216.473 E2.24837 ; external perimeter
G1 X213.361 Y199.712 E2.31488 ; external perimeter
G1 X215.417 Y215.625 F1800.000 ; move to first infill point
G1 F900.000
G1 X214.637 Y214.845 E2.31902 ; infill
G1 X214.637 Y213.423 E2.32436 ; infill
G1 X216.983 Y215.770 E2.33681 ; infill
G1 X218.550 Y215.915 E2.34272 ; infill
G1 X214.637 Y212.002 E2.36349 ; infill
G1 X214.637 Y210.581 E2.36882 ; infill
G1 X220.071 Y216.015 E2.39767 ; infill
G1 X220.789 Y216.050 E2.40037 ; infill
G1 X221.532 Y216.054 E2.40316 ; infill
G1 X214.637 Y209.159 E2.43976 ; infill
G1 X214.637 Y207.738 E2.44510 ; infill
G1 X222.940 Y216.041 E2.48917 ; infill
G1 X224.301 Y215.980 E2.49429 ; infill
G1 X214.637 Y206.317 E2.54559 ; infill
G1 X214.637 Y204.895 E2.55092 ; infill
G1 X225.609 Y215.867 E2.60917 ; infill
G1 X226.872 Y215.709 E2.61395 ; infill
G1 X214.637 Y203.474 E2.67890 ; infill
G1 X214.637 Y202.052 E2.68423 ; infill
G1 X228.099 Y215.514 E2.75570 ; infill
G1 X229.289 Y215.282 E2.76025 ; infill
G1 X214.637 Y200.631 E2.83803 ; infill
G1 X214.637 Y200.405 E2.83888 ; infill
G1 X215.718 Y200.290 E2.84296 ; infill
G1 X230.440 Y215.013 E2.92111 ; infill
G1 X231.548 Y214.699 E2.92543 ; infill
G1 X217.003 Y200.154 E3.00265 ; infill
G1 X218.313 Y200.042 E3.00758 ; infill
G1 X232.615 Y214.344 E3.08351 ; infill
G1 X233.642 Y213.950 E3.08764 ; infill
G1 X219.661 Y199.969 E3.16186 ; infill
G1 X221.054 Y199.941 E3.16709 ; infill
G1 X234.626 Y213.513 E3.23914 ; infill
G1 X234.997 Y213.338 E3.24068 ; infill
G1 X235.563 Y213.029 E3.24310 ; infill
G1 X222.500 Y199.965 E3.31245 ; infill
G1 X224.012 Y200.056 E3.31814 ; infill
G1 X236.452 Y212.496 E3.38417 ; infill
G1 X237.029 Y212.095 E3.38681 ; infill
G1 X237.275 Y211.898 E3.38800 ; infill
G1 X225.599 Y200.221 E3.44998 ; infill
G1 X227.271 Y200.472 E3.45633 ; infill
G1 X238.030 Y211.231 E3.51345 ; infill
G1 X238.329 Y210.926 E3.51505 ; infill
G1 X238.697 Y210.476 E3.51723 ; infill
G1 X229.059 Y200.838 E3.56840 ; infill
G1 X230.301 Y201.160 E3.57321 ; infill
G1 X231.028 Y201.387 E3.57608 ; infill
G1 X239.223 Y209.581 E3.61958 ; infill
G1 X239.374 Y209.170 E3.62122 ; infill
G1 X239.447 Y208.852 E3.62245 ; infill
G1 X239.483 Y208.420 E3.62407 ; infill
G1 X233.300 Y202.238 E3.65690 ; infill
G1 X233.864 Y202.488 E3.65921 ; infill
G1 X234.800 Y202.972 E3.66317 ; infill
G1 X235.599 Y203.452 E3.66666 ; infill
G1 X236.305 Y203.947 E3.66990 ; infill
G1 X237.048 Y204.566 E3.67353 ; infill
G1 X238.221 Y205.737 E3.67975 ; infill
G1 Z6.950 F1800.000 ; move to next layer (2)
G1 E1.67975 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X216.866 Y202.435 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X219.490 Y202.216 E2.01045 ; external perimeter
G1 X221.096 Y202.166 E2.01683 ; external perimeter
G1 X222.730 Y202.188 E2.02331 ; external perimeter
G1 X224.351 Y202.285 E2.02975 ; external perimeter
G1 X225.990 Y202.461 E2.03630 ; external perimeter
G1 X227.549 Y202.706 E2.04256 ; external perimeter
G1 X228.899 Y202.986 E2.04803 ; external perimeter
G1 X230.186 Y203.318 E2.05330 ; external perimeter
G1 X231.362 Y203.686 E2.05819 ; external perimeter
G1 X232.449 Y204.091 E2.06280 ; external perimeter
G1 X233.413 Y204.514 E2.06698 ; external perimeter
G1 X234.291 Y204.966 E2.07089 ; external perimeter
G1 X235.031 Y205.413 E2.07432 ; external perimeter
G1 X235.647 Y205.848 E2.07732 ; external perimeter
G1 X236.145 Y206.264 E2.07989 ; external perimeter
G1 X236.538 Y206.654 E2.08209 ; external perimeter
G1 X236.833 Y207.011 E2.08392 ; external perimeter
G1 X237.051 Y207.346 E2.08551 ; external perimeter
G1 X237.206 Y207.691 E2.08701 ; external perimeter
G1 X237.265 Y207.968 E2.08814 ; external perimeter
G1 X237.219 Y208.273 E2.08936 ; external perimeter
G1 X237.065 Y208.629 E2.09090 ; external perimeter
G1 X236.850 Y208.966 E2.09248 ; external perimeter
G1 X236.530 Y209.354 E2.09448 ; external perimeter
G1 X236.101 Y209.776 E2.09687 ; external perimeter
G1 X235.534 Y210.236 E2.09977 ; external perimeter
G1 X234.949 Y210.640 E2.10259 ; external perimeter
G1 X234.559 Y210.880 E2.10440 ; external perimeter
G1 X233.763 Y211.314 E2.10800 ; external perimeter
G1 X232.885 Y211.726 E2.11185 ; external perimeter
G1 X231.884 Y212.128 E2.11613 ; external perimeter
G1 X230.755 Y212.512 E2.12086 ; external perimeter
G1 X229.521 Y212.862 E2.12595 ; external perimeter
G1 X228.199 Y213.167 E2.13134 ; external perimeter
G1 X226.776 Y213.425 E2.13708 ; external perimeter
G1 X225.249 Y213.628 E2.14319 ; external perimeter
G1 X223.691 Y213.763 E2.14940 ; external perimeter
G1 X222.106 Y213.829 E2.15569 ; external perimeter
G1 X220.472 Y213.823 E2.16217 ; external perimeter
G1 X218.843 Y213.742 E2.16865 ; external perimeter
G1 X216.866 Y213.558 E2.17652 ; external perimeter
G1 X216.866 Y202.615 E2.21995 ; external perimeter
G1 X213.361 Y199.532 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X214.421 Y199.304 E2.22425 ; external perimeter
G1 X215.970 Y199.045 E2.23048 ; external perimeter
G1 X217.699 Y198.837 E2.23739 ; external perimeter
G1 X219.388 Y198.713 E2.24411 ; external perimeter
G1 X221.275 Y198.662 E2.25160 ; external perimeter
G1 X222.802 Y198.684 E2.25766 ; external perimeter
G1 X224.421 Y198.775 E2.26410 ; external perimeter
G1 X226.172 Y198.951 E2.27108 ; external perimeter
G1 X227.965 Y199.222 E2.27828 ; external perimeter
G1 X229.394 Y199.505 E2.28406 ; external perimeter
G1 X230.809 Y199.855 E2.28984 ; external perimeter
G1 X232.365 Y200.326 E2.29629 ; external perimeter
G1 X233.862 Y200.884 E2.30263 ; external perimeter
G1 X234.991 Y201.385 E2.30753 ; external perimeter
G1 X236.149 Y201.992 E2.31272 ; external perimeter
G1 X237.189 Y202.641 E2.31758 ; external perimeter
G1 X238.164 Y203.378 E2.32243 ; external perimeter
G1 X238.889 Y204.044 E2.32634 ; external perimeter
G1 X239.537 Y204.781 E2.33024 ; external perimeter
G1 X240.068 Y205.569 E2.33401 ; external perimeter
G1 X240.421 Y206.295 E2.33721 ; external perimeter
G1 X240.459 Y206.408 E2.33768 ; external perimeter
G1 X240.657 Y207.070 E2.34043 ; external perimeter
G1 X240.752 Y207.798 E2.34334 ; external perimeter
G1 X240.719 Y208.570 E2.34640 ; external perimeter
G1 X240.562 Y209.299 E2.34936 ; external perimeter
G1 X240.241 Y210.108 E2.35282 ; external perimeter
G1 X239.809 Y210.844 E2.35621 ; external perimeter
G1 X239.176 Y211.647 E2.36026 ; external perimeter
G1 X238.539 Y212.293 E2.36386 ; external perimeter
G1 X237.829 Y212.888 E2.36754 ; external perimeter
G1 X237.646 Y213.031 E2.36846 ; external perimeter
G1 X236.718 Y213.667 E2.37292 ; external perimeter
G1 X235.621 Y214.298 E2.37795 ; external perimeter
G1 X234.413 Y214.882 E2.38327 ; external perimeter
G1 X233.054 Y215.431 E2.38909 ; external perimeter
G1 X231.607 Y215.915 E2.39514 ; external perimeter
G1 X230.211 Y216.302 E2.40089 ; external perimeter
G1 X228.797 Y216.620 E2.40664 ; external perimeter
G1 X227.048 Y216.928 E2.41369 ; external perimeter
G1 X225.203 Y217.154 E2.42106 ; external perimeter
G1 X223.707 Y217.273 E2.42702 ; external perimeter
G1 X222.124 Y217.333 E2.43331 ; external perimeter
G1 X220.328 Y217.324 E2.44043 ; external perimeter
G1 X218.595 Y217.238 E2.44732 ; external perimeter
G1 X216.823 Y217.067 E2.45438 ; external perimeter
G1 X215.183 Y216.831 E2.46096 ; external perimeter
G1 X213.361 Y216.473 E2.46832 ; external perimeter
G1 X213.361 Y199.712 E2.53483 ; external perimeter
G1 X214.215 Y201.189 F1800.000 ; move to first infill point
G1 F1200.000
G1 X215.283 Y200.122 E2.54510 ; infill
G1 X216.701 Y199.885 E2.55487 ; infill
G1 X218.284 Y199.695 E2.56571 ; infill
G1 X216.409 Y201.570 E2.58374 ; infill
G1 X218.876 Y201.364 E2.60057 ; infill
G1 X219.199 Y201.354 E2.60277 ; infill
G1 X221.016 Y199.537 E2.62024 ; infill
G1 X221.817 Y199.516 E2.62569 ; infill
G1 X223.287 Y199.537 E2.63568 ; infill
G1 X223.574 Y199.554 E2.63763 ; infill
G1 X221.799 Y201.329 E2.65470 ; infill
G1 X222.248 Y201.335 E2.65775 ; infill
G1 X224.234 Y201.468 E2.67128 ; infill
G1 X225.964 Y199.738 E2.68792 ; infill
G1 X226.533 Y199.795 E2.69181 ; infill
G1 X228.226 Y200.050 E2.70345 ; infill
G1 X226.518 Y201.757 E2.71986 ; infill
G1 X227.264 Y201.875 E2.72499 ; infill
G1 X228.682 Y202.168 E2.73483 ; infill
G1 X230.346 Y200.504 E2.75083 ; infill
G1 X230.975 Y200.659 E2.75524 ; infill
G1 X232.349 Y201.075 E2.76500 ; infill
G1 X230.699 Y202.725 E2.78086 ; infill
G1 X231.277 Y202.906 E2.78498 ; infill
G1 X232.592 Y203.406 E2.79454 ; infill
G1 X234.212 Y201.787 E2.81011 ; infill
G1 X234.921 Y202.101 E2.81539 ; infill
G1 X235.938 Y202.634 E2.82320 ; infill
G1 X234.336 Y204.237 E2.83861 ; infill
G1 X235.257 Y204.785 E2.84589 ; infill
G1 X235.904 Y205.242 E2.85128 ; infill
G1 X237.482 Y203.665 E2.86645 ; infill
G1 X237.808 Y203.911 E2.86923 ; infill
G1 X238.430 Y204.482 E2.87497 ; infill
G1 X238.808 Y204.913 E2.87886 ; infill
G1 X237.229 Y206.492 E2.89405 ; infill
G1 X237.419 Y206.721 E2.89607 ; infill
G1 X237.739 Y207.213 E2.90006 ; infill
G1 X237.999 Y207.793 E2.90439 ; infill
G1 X238.087 Y208.208 E2.90727 ; infill
G1 X239.747 Y206.549 E2.92322 ; infill
G1 X239.829 Y206.827 E2.92519 ; infill
G1 X239.894 Y207.325 E2.92861 ; infill
G1 X239.872 Y207.859 E2.93224 ; infill
G1 X239.762 Y208.367 E2.93578 ; infill
G1 X239.539 Y208.939 E2.93995 ; infill
G1 X239.194 Y209.527 E2.94458 ; infill
G1 X238.668 Y210.194 E2.95036 ; infill
G1 X237.063 Y211.806 E2.96582 ; infill
G1 X231.428 Y214.867 F1800.000 ; move to first infill point
G1 F1200.000
G1 X233.735 Y212.560 E2.98800 ; infill
G1 X232.900 Y212.895 E2.99412 ; infill
G1 X231.702 Y213.303 E3.00273 ; infill
G1 X230.400 Y213.672 E3.01193 ; infill
G1 X229.944 Y213.778 E3.01511 ; infill
G1 X227.915 Y215.806 E3.03462 ; infill
G1 X226.310 Y216.089 E3.04570 ; infill
G1 X224.883 Y216.264 E3.05547 ; infill
G1 X226.786 Y214.360 E3.07377 ; infill
G1 X225.934 Y214.474 E3.07961 ; infill
G1 X224.313 Y214.614 E3.09068 ; infill
G1 X223.943 Y214.630 E3.09319 ; infill
G1 X222.115 Y216.458 E3.11077 ; infill
G1 X221.567 Y216.479 E3.11450 ; infill
G1 X219.542 Y216.456 E3.12826 ; infill
G1 X221.321 Y214.678 E3.14536 ; infill
G1 X220.969 Y214.677 E3.14776 ; infill
G1 X219.278 Y214.593 E3.15927 ; infill
G1 X218.869 Y214.555 E3.16205 ; infill
G1 X217.136 Y216.288 E3.17872 ; infill
G1 X216.454 Y216.223 E3.18337 ; infill
G1 X214.858 Y215.992 E3.19434 ; infill
G1 X216.515 Y214.335 E3.21027 ; infill
G1 X216.012 Y214.288 E3.21370 ; infill
G1 X216.012 Y212.264 E3.22747 ; infill
G1 X214.215 Y214.061 E3.24474 ; infill
G1 X214.215 Y211.487 E3.26225 ; infill
G1 X216.012 Y209.689 E3.27952 ; infill
G1 X216.012 Y207.115 E3.29702 ; infill
G1 X214.215 Y208.912 E3.31430 ; infill
G1 X214.215 Y206.338 E3.33180 ; infill
G1 X216.012 Y204.541 E3.34908 ; infill
G1 X216.012 Y201.967 E3.36658 ; infill
G1 X214.215 Y203.764 E3.38386 ; infill
G1 X214.215 Y201.190 E3.40136 ; infill
M106 S196.35 ; enable fan
G1 Z8.150 F1800.000 ; move to next layer (3)
G1 X216.522 Y202.152 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X217.976 Y201.986 E3.40717 ; external perimeter
G1 X219.477 Y201.872 E3.41314 ; external perimeter
G1 X221.103 Y201.821 E3.41959 ; external perimeter
G1 X222.745 Y201.844 E3.42611 ; external perimeter
G1 X224.273 Y201.934 E3.43218 ; external perimeter
G1 X226.132 Y202.134 E3.43960 ; external perimeter
G1 X227.611 Y202.368 E3.44555 ; external perimeter
G1 X228.987 Y202.653 E3.45112 ; external perimeter
G1 X230.280 Y202.987 E3.45642 ; external perimeter
G1 X231.554 Y203.388 E3.46172 ; external perimeter
G1 X232.582 Y203.773 E3.46608 ; external perimeter
G1 X233.638 Y204.240 E3.47066 ; external perimeter
G1 X234.571 Y204.731 E3.47484 ; external perimeter
G1 X235.213 Y205.121 E3.47782 ; external perimeter
G1 X235.864 Y205.582 E3.48099 ; external perimeter
G1 X236.380 Y206.012 E3.48365 ; external perimeter
G1 X236.734 Y206.362 E3.48563 ; external perimeter
G1 X237.094 Y206.785 E3.48783 ; external perimeter
G1 X237.311 Y207.112 E3.48939 ; external perimeter
G1 X237.472 Y207.422 E3.49078 ; external perimeter
G1 X237.587 Y207.792 E3.49232 ; external perimeter
G1 X237.596 Y208.147 E3.49373 ; external perimeter
G1 X237.498 Y208.513 E3.49523 ; external perimeter
G1 X237.334 Y208.851 E3.49672 ; external perimeter
G1 X237.128 Y209.168 E3.49822 ; external perimeter
G1 X236.788 Y209.583 E3.50035 ; external perimeter
G1 X236.333 Y210.030 E3.50288 ; external perimeter
G1 X235.698 Y210.542 E3.50612 ; external perimeter
G1 X235.121 Y210.938 E3.50889 ; external perimeter
G1 X234.686 Y211.204 E3.51092 ; external perimeter
G1 X233.918 Y211.621 E3.51438 ; external perimeter
G1 X233.086 Y212.013 E3.51803 ; external perimeter
G1 X232.102 Y212.412 E3.52225 ; external perimeter
G1 X230.880 Y212.833 E3.52738 ; external perimeter
G1 X229.582 Y213.201 E3.53273 ; external perimeter
G1 X228.266 Y213.504 E3.53809 ; external perimeter
G1 X226.840 Y213.763 E3.54384 ; external perimeter
G1 X225.279 Y213.971 E3.55009 ; external perimeter
G1 X223.722 Y214.106 E3.55629 ; external perimeter
G1 X222.119 Y214.173 E3.56266 ; external perimeter
G1 X220.470 Y214.167 E3.56920 ; external perimeter
G1 X218.816 Y214.085 E3.57577 ; external perimeter
G1 X216.522 Y213.859 E3.58492 ; external perimeter
G1 X216.522 Y202.332 E3.63066 ; external perimeter
G1 X213.361 Y199.532 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X214.421 Y199.304 E3.63496 ; external perimeter
G1 X215.932 Y199.051 E3.64104 ; external perimeter
G1 X217.700 Y198.837 E3.64811 ; external perimeter
G1 X219.387 Y198.713 E3.65482 ; external perimeter
G1 X221.376 Y198.662 E3.66272 ; external perimeter
G1 X222.802 Y198.684 E3.66838 ; external perimeter
G1 X224.377 Y198.772 E3.67464 ; external perimeter
G1 X226.172 Y198.951 E3.68180 ; external perimeter
G1 X228.053 Y199.238 E3.68935 ; external perimeter
G1 X229.394 Y199.505 E3.69477 ; external perimeter
G1 X230.748 Y199.839 E3.70031 ; external perimeter
G1 X232.364 Y200.326 E3.70700 ; external perimeter
G1 X233.990 Y200.939 E3.71390 ; external perimeter
G1 X235.040 Y201.408 E3.71846 ; external perimeter
G1 X236.148 Y201.991 E3.72343 ; external perimeter
G1 X237.267 Y202.696 E3.72868 ; external perimeter
G1 X238.107 Y203.330 E3.73286 ; external perimeter
G1 X238.888 Y204.043 E3.73705 ; external perimeter
G1 X239.537 Y204.781 E3.74095 ; external perimeter
G1 X240.080 Y205.590 E3.74482 ; external perimeter
G1 X240.421 Y206.294 E3.74792 ; external perimeter
G1 X240.490 Y206.497 E3.74877 ; external perimeter
G1 X240.660 Y207.085 E3.75120 ; external perimeter
G1 X240.752 Y207.797 E3.75405 ; external perimeter
G1 X240.718 Y208.579 E3.75716 ; external perimeter
G1 X240.564 Y209.293 E3.76006 ; external perimeter
G1 X240.225 Y210.139 E3.76367 ; external perimeter
G1 X239.800 Y210.858 E3.76699 ; external perimeter
G1 X239.374 Y211.417 E3.76977 ; external perimeter
G1 X239.127 Y211.701 E3.77127 ; external perimeter
G1 X238.539 Y212.293 E3.77458 ; external perimeter
G1 X237.615 Y213.054 E3.77933 ; external perimeter
G1 X236.835 Y213.592 E3.78309 ; external perimeter
G1 X235.620 Y214.299 E3.78867 ; external perimeter
G1 X234.413 Y214.882 E3.79399 ; external perimeter
G1 X233.028 Y215.440 E3.79991 ; external perimeter
G1 X231.556 Y215.930 E3.80607 ; external perimeter
G1 X230.210 Y216.302 E3.81161 ; external perimeter
G1 X228.874 Y216.604 E3.81705 ; external perimeter
G1 X227.048 Y216.928 E3.82440 ; external perimeter
G1 X225.097 Y217.164 E3.83220 ; external perimeter
G1 X223.707 Y217.273 E3.83773 ; external perimeter
G1 X222.191 Y217.331 E3.84375 ; external perimeter
G1 X220.347 Y217.325 E3.85107 ; external perimeter
G1 X218.568 Y217.236 E3.85814 ; external perimeter
G1 X216.771 Y217.060 E3.86531 ; external perimeter
G1 X215.132 Y216.823 E3.87188 ; external perimeter
G1 X213.361 Y216.473 E3.87904 ; external perimeter
G1 X213.361 Y199.712 E3.94555 ; external perimeter
G1 X214.215 Y213.637 F1800.000 ; move to first infill point
G1 F600.000
G1 X215.668 Y215.090 E3.95892 ; infill
G1 X215.668 Y212.009 E3.97897 ; infill
G1 X214.215 Y210.557 E3.99234 ; infill
G1 X214.215 Y207.476 E4.01238 ; infill
G1 X215.668 Y208.929 E4.02576 ; infill
G1 X215.668 Y205.849 E4.04580 ; infill
G1 X214.215 Y204.396 E4.05917 ; infill
G1 X214.215 Y201.316 E4.07922 ; infill
G1 X215.668 Y202.769 E4.09259 ; infill
G1 X215.668 Y201.447 E4.10120 ; infill
G1 X217.247 Y201.267 E4.11154 ; infill
G1 X215.841 Y199.861 E4.12448 ; infill
G1 X217.300 Y199.685 E4.13404 ; infill
G1 X218.645 Y199.585 E4.14282 ; infill
G1 X220.076 Y201.016 E4.15599 ; infill
G1 X221.625 Y200.967 E4.16607 ; infill
G1 X223.129 Y200.988 E4.17586 ; infill
G1 X221.669 Y199.529 E4.18929 ; infill
G1 X222.219 Y199.537 E4.19287 ; infill
G1 X223.735 Y199.622 E4.20275 ; infill
G1 X224.965 Y199.745 E4.21080 ; infill
G1 X226.472 Y201.251 E4.22466 ; infill
G1 X226.848 Y201.291 E4.22712 ; infill
G1 X228.394 Y201.536 E4.23731 ; infill
G1 X229.835 Y201.835 E4.24689 ; infill
G1 X230.241 Y201.940 E4.24961 ; infill
G1 X228.649 Y200.348 E4.26426 ; infill
G1 X229.848 Y200.644 E4.27230 ; infill
G1 X231.385 Y201.107 E4.28274 ; infill
G1 X232.927 Y201.689 E4.29347 ; infill
G1 X233.185 Y201.804 E4.29531 ; infill
G1 X235.050 Y203.668 E4.31247 ; infill
G1 X239.889 Y208.508 F1800.000 ; move to first infill point
G1 F600.000
G1 X238.436 Y207.055 E4.32584 ; infill
G1 X238.455 Y207.780 E4.33056 ; infill
G1 X238.270 Y208.466 E4.33519 ; infill
G1 X238.011 Y209.000 E4.33905 ; infill
G1 X237.732 Y209.431 E4.34239 ; infill
G1 X239.067 Y210.766 E4.35468 ; infill
G1 X238.644 Y211.290 E4.35906 ; infill
G1 X238.132 Y211.806 E4.36379 ; infill
G1 X237.530 Y212.310 E4.36890 ; infill
G1 X236.187 Y210.966 E4.38126 ; infill
G1 X235.993 Y211.122 E4.38288 ; infill
G1 X235.341 Y211.570 E4.38803 ; infill
G1 X234.845 Y211.872 E4.39181 ; infill
G1 X234.306 Y212.166 E4.39580 ; infill
G1 X235.656 Y213.516 E4.40823 ; infill
G1 X234.385 Y214.146 E4.41747 ; infill
G1 X233.545 Y214.485 E4.42336 ; infill
G1 X232.185 Y213.125 E4.43587 ; infill
G1 X230.762 Y213.624 E4.44569 ; infill
G1 X229.859 Y213.880 E4.45179 ; infill
G1 X231.239 Y215.260 E4.46449 ; infill
G1 X230.406 Y215.490 E4.47012 ; infill
G1 X229.133 Y215.777 E4.47861 ; infill
G1 X228.746 Y215.846 E4.48117 ; infill
G1 X227.350 Y214.450 E4.49402 ; infill
G1 X226.522 Y214.600 E4.49950 ; infill
G1 X224.657 Y214.838 E4.51173 ; infill
G1 X226.066 Y216.247 E4.52471 ; infill
G1 X225.493 Y216.316 E4.52846 ; infill
G1 X224.160 Y216.421 E4.53717 ; infill
G1 X223.197 Y216.458 E4.54344 ; infill
G1 X221.759 Y215.020 E4.55667 ; infill
G1 X219.899 Y215.021 E4.56878 ; infill
G1 X218.616 Y214.957 E4.57714 ; infill
G1 X220.088 Y216.430 E4.59069 ; infill
G1 X219.204 Y216.385 E4.59645 ; infill
G1 X217.471 Y216.216 E4.60778 ; infill
G1 X216.680 Y216.101 E4.61298 ; infill
G1 X215.222 Y214.644 E4.62640 ; infill
M106 S204 ; enable fan
G1 Z9.350 F1800.000 ; move to next layer (4)
G1 X216.178 Y201.853 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X217.850 Y201.652 E4.63308 ; external perimeter
G1 X219.165 Y201.549 E4.63832 ; external perimeter
G1 X221.098 Y201.477 E4.64599 ; external perimeter
G1 X222.759 Y201.500 E4.65258 ; external perimeter
G1 X224.506 Y201.607 E4.65953 ; external perimeter
G1 X226.068 Y201.777 E4.66577 ; external perimeter
G1 X227.672 Y202.029 E4.67221 ; external perimeter
G1 X229.064 Y202.318 E4.67785 ; external perimeter
G1 X230.373 Y202.656 E4.68321 ; external perimeter
G1 X231.593 Y203.037 E4.68828 ; external perimeter
G1 X232.712 Y203.455 E4.69302 ; external perimeter
G1 X233.639 Y203.860 E4.69704 ; external perimeter
G1 X234.635 Y204.370 E4.70148 ; external perimeter
G1 X235.511 Y204.906 E4.70555 ; external perimeter
G1 X236.083 Y205.316 E4.70835 ; external perimeter
G1 X236.613 Y205.760 E4.71109 ; external perimeter
G1 X237.069 Y206.216 E4.71365 ; external perimeter
G1 X237.368 Y206.576 E4.71551 ; external perimeter
G1 X237.718 Y207.138 E4.71814 ; external perimeter
G1 X237.875 Y207.524 E4.71979 ; external perimeter
G1 X237.948 Y207.940 E4.72147 ; external perimeter
G1 X237.910 Y208.334 E4.72304 ; external perimeter
G1 X237.820 Y208.630 E4.72426 ; external perimeter
G1 X237.623 Y209.039 E4.72607 ; external perimeter
G1 X237.407 Y209.369 E4.72763 ; external perimeter
G1 X237.042 Y209.815 E4.72992 ; external perimeter
G1 X236.566 Y210.283 E4.73257 ; external perimeter
G1 X235.862 Y210.849 E4.73615 ; external perimeter
G1 X235.292 Y211.237 E4.73888 ; external perimeter
G1 X234.810 Y211.529 E4.74112 ; external perimeter
G1 X233.860 Y212.031 E4.74539 ; external perimeter
G1 X233.151 Y212.361 E4.74849 ; external perimeter
G1 X232.317 Y212.698 E4.75206 ; external perimeter
G1 X231.005 Y213.155 E4.75757 ; external perimeter
G1 X229.643 Y213.541 E4.76319 ; external perimeter
G1 X228.334 Y213.842 E4.76852 ; external perimeter
G1 X226.893 Y214.103 E4.77433 ; external perimeter
G1 X225.312 Y214.314 E4.78066 ; external perimeter
G1 X223.582 Y214.459 E4.78755 ; external perimeter
G1 X222.130 Y214.517 E4.79332 ; external perimeter
G1 X220.345 Y214.508 E4.80040 ; external perimeter
G1 X218.792 Y214.429 E4.80657 ; external perimeter
G1 X217.284 Y214.285 E4.81258 ; external perimeter
G1 X216.178 Y214.140 E4.81701 ; external perimeter
G1 X216.178 Y202.033 E4.86505 ; external perimeter
G1 X213.361 Y199.532 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X214.421 Y199.304 E4.86935 ; external perimeter
G1 X215.893 Y199.057 E4.87528 ; external perimeter
G1 X217.700 Y198.837 E4.88250 ; external perimeter
G1 X219.387 Y198.713 E4.88921 ; external perimeter
G1 X221.477 Y198.663 E4.89751 ; external perimeter
G1 X222.802 Y198.684 E4.90277 ; external perimeter
G1 X224.332 Y198.769 E4.90885 ; external perimeter
G1 X226.212 Y198.957 E4.91635 ; external perimeter
G1 X228.140 Y199.254 E4.92409 ; external perimeter
G1 X229.394 Y199.505 E4.92916 ; external perimeter
G1 X230.688 Y199.822 E4.93445 ; external perimeter
G1 X232.364 Y200.326 E4.94139 ; external perimeter
G1 X234.012 Y200.947 E4.94838 ; external perimeter
G1 X235.057 Y201.417 E4.95293 ; external perimeter
G1 X236.147 Y201.991 E4.95782 ; external perimeter
G1 X237.295 Y202.715 E4.96320 ; external perimeter
G1 X238.107 Y203.330 E4.96724 ; external perimeter
G1 X239.019 Y204.181 E4.97219 ; external perimeter
G1 X239.534 Y204.778 E4.97532 ; external perimeter
G1 X240.092 Y205.611 E4.97930 ; external perimeter
G1 X240.421 Y206.293 E4.98231 ; external perimeter
G1 X240.520 Y206.586 E4.98353 ; external perimeter
G1 X240.663 Y207.098 E4.98564 ; external perimeter
G1 X240.753 Y207.802 E4.98846 ; external perimeter
G1 X240.721 Y208.569 E4.99151 ; external perimeter
G1 X240.565 Y209.288 E4.99443 ; external perimeter
G1 X240.386 Y209.775 E4.99649 ; external perimeter
G1 X240.209 Y210.170 E4.99820 ; external perimeter
G1 X239.791 Y210.872 E5.00145 ; external perimeter
G1 X239.422 Y211.358 E5.00387 ; external perimeter
G1 X239.078 Y211.755 E5.00595 ; external perimeter
G1 X238.539 Y212.293 E5.00897 ; external perimeter
G1 X237.584 Y213.077 E5.01387 ; external perimeter
G1 X236.877 Y213.564 E5.01728 ; external perimeter
G1 X235.619 Y214.299 E5.02306 ; external perimeter
G1 X234.413 Y214.882 E5.02838 ; external perimeter
G1 X233.002 Y215.450 E5.03441 ; external perimeter
G1 X231.506 Y215.946 E5.04067 ; external perimeter
G1 X230.208 Y216.302 E5.04601 ; external perimeter
G1 X228.951 Y216.588 E5.05113 ; external perimeter
G1 X227.046 Y216.928 E5.05881 ; external perimeter
G1 X224.999 Y217.173 E5.06699 ; external perimeter
G1 X223.707 Y217.273 E5.07213 ; external perimeter
G1 X222.259 Y217.329 E5.07788 ; external perimeter
G1 X220.365 Y217.325 E5.08539 ; external perimeter
G1 X218.559 Y217.235 E5.09257 ; external perimeter
G1 X216.718 Y217.054 E5.09991 ; external perimeter
G1 X215.081 Y216.814 E5.10648 ; external perimeter
G1 X213.361 Y216.473 E5.11343 ; external perimeter
G1 X213.361 Y199.712 E5.17994 ; external perimeter
G1 X215.324 Y201.254 F1800.000 ; move to first infill point
G1 F600.000
G1 X214.215 Y202.363 E5.19014 ; infill
G1 X214.215 Y205.443 E5.21019 ; infill
G1 X215.324 Y204.335 E5.22040 ; infill
G1 X215.324 Y207.415 E5.24044 ; infill
G1 X214.215 Y208.524 E5.25065 ; infill
G1 X214.215 Y211.604 E5.27069 ; infill
G1 X215.324 Y210.495 E5.28090 ; infill
G1 X215.324 Y213.576 E5.30095 ; infill
G1 X214.215 Y214.684 E5.31115 ; infill
G1 X216.943 Y215.036 F1800.000 ; move to first infill point
G1 F600.000
G1 X215.844 Y216.135 E5.32126 ; infill
G1 X216.353 Y216.210 E5.32461 ; infill
G1 X218.128 Y216.385 E5.33621 ; infill
G1 X218.649 Y216.411 E5.33961 ; infill
G1 X219.754 Y215.306 E5.34978 ; infill
G1 X220.840 Y215.361 E5.35686 ; infill
G1 X222.773 Y215.367 E5.36944 ; infill
G1 X221.665 Y216.476 E5.37964 ; infill
G1 X223.093 Y216.421 E5.38894 ; infill
G1 X224.329 Y216.325 E5.39701 ; infill
G1 X224.972 Y216.249 E5.40123 ; infill
G1 X226.071 Y215.150 E5.41134 ; infill
G1 X227.643 Y214.940 E5.42166 ; infill
G1 X229.147 Y214.667 E5.43161 ; infill
G1 X229.779 Y214.522 E5.43583 ; infill
G1 X228.656 Y215.645 E5.44616 ; infill
G1 E3.44616 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X230.144 Y201.835 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X231.238 Y200.742 E2.01006 ; infill
G1 X230.857 Y200.628 E2.01265 ; infill
G1 X229.626 Y200.326 E2.02089 ; infill
G1 X228.749 Y200.150 E2.02672 ; infill
G1 X227.648 Y201.252 E2.03685 ; infill
G1 X225.717 Y200.935 E2.04958 ; infill
G1 X224.966 Y200.853 E2.05450 ; infill
G1 X226.070 Y199.750 E2.06466 ; infill
G1 X224.759 Y199.619 E2.07323 ; infill
G1 X223.203 Y199.536 E2.08337 ; infill
G1 X222.094 Y200.645 E2.09358 ; infill
G1 X220.549 Y200.623 E2.10364 ; infill
G1 X218.977 Y200.681 E2.11387 ; infill
G1 X220.096 Y199.562 E2.12417 ; infill
G1 X218.368 Y199.685 E2.13544 ; infill
G1 X216.690 Y199.889 E2.14644 ; infill
G1 X215.582 Y200.996 E2.15664 ; infill
G1 X214.821 Y201.088 E2.16162 ; infill
G1 X215.622 Y200.956 E2.16691 ; infill
G1 X232.936 Y202.759 F1800.000 ; move to first infill point
G1 F1200.000
G1 X234.003 Y201.692 E2.17741 ; infill
G1 X234.983 Y202.131 E2.18489 ; infill
G1 X235.780 Y202.550 E2.19115 ; infill
G1 X234.686 Y203.644 E2.20191 ; infill
G1 X235.744 Y204.283 E2.21051 ; infill
G1 X236.291 Y204.674 E2.21520 ; infill
G1 X237.382 Y203.583 E2.22593 ; infill
G1 X237.759 Y203.868 E2.22922 ; infill
G1 X238.546 Y204.604 E2.23672 ; infill
G1 X238.755 Y204.846 E2.23894 ; infill
G1 X237.664 Y205.937 E2.24968 ; infill
G1 X237.962 Y206.297 E2.25293 ; infill
G1 X238.425 Y207.039 E2.25902 ; infill
G1 X238.647 Y207.588 E2.26314 ; infill
G1 X239.737 Y206.498 E2.27387 ; infill
G1 X239.834 Y206.841 E2.27634 ; infill
G1 X239.895 Y207.328 E2.27976 ; infill
G1 X239.873 Y207.859 E2.28346 ; infill
G1 X239.764 Y208.366 E2.28707 ; infill
G1 X239.510 Y208.996 E2.29180 ; infill
G1 X239.172 Y209.562 E2.29639 ; infill
G1 X238.879 Y209.949 E2.29977 ; infill
G1 X238.596 Y210.274 E2.30276 ; infill
G1 X237.064 Y211.807 E2.31784 ; infill
M106 S214.2 ; enable fan
G1 Z10.550 F1800.000 ; move to next layer (5)
G1 E0.31784 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X215.833 Y201.552 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X217.762 Y201.315 E2.00771 ; external perimeter
G1 X219.449 Y201.185 E2.01443 ; external perimeter
G1 X221.097 Y201.133 E2.02097 ; external perimeter
G1 X222.771 Y201.157 E2.02761 ; external perimeter
G1 X224.574 Y201.268 E2.03478 ; external perimeter
G1 X226.114 Y201.436 E2.04092 ; external perimeter
G1 X227.733 Y201.690 E2.04743 ; external perimeter
G1 X229.142 Y201.983 E2.05314 ; external perimeter
G1 X230.467 Y202.325 E2.05857 ; external perimeter
G1 X231.704 Y202.712 E2.06371 ; external perimeter
G1 X232.846 Y203.138 E2.06855 ; external perimeter
G1 X234.056 Y203.679 E2.07381 ; external perimeter
G1 X235.107 Y204.249 E2.07855 ; external perimeter
G1 X235.591 Y204.546 E2.08081 ; external perimeter
G1 X236.303 Y205.051 E2.08427 ; external perimeter
G1 X236.973 Y205.626 E2.08777 ; external perimeter
G1 X237.337 Y205.999 E2.08984 ; external perimeter
G1 X237.628 Y206.350 E2.09165 ; external perimeter
G1 X237.946 Y206.831 E2.09394 ; external perimeter
G1 X238.106 Y207.158 E2.09539 ; external perimeter
G1 X238.208 Y207.443 E2.09659 ; external perimeter
G1 X238.292 Y207.932 E2.09855 ; external perimeter
G1 X238.244 Y208.417 E2.10049 ; external perimeter
G1 X238.147 Y208.739 E2.10182 ; external perimeter
G1 X237.911 Y209.228 E2.10398 ; external perimeter
G1 X237.687 Y209.570 E2.10560 ; external perimeter
G1 X237.296 Y210.047 E2.10805 ; external perimeter
G1 X236.799 Y210.537 E2.11082 ; external perimeter
G1 X236.026 Y211.155 E2.11474 ; external perimeter
G1 X235.464 Y211.535 E2.11744 ; external perimeter
G1 X234.936 Y211.854 E2.11988 ; external perimeter
G1 X233.915 Y212.387 E2.12445 ; external perimeter
G1 X233.288 Y212.676 E2.12719 ; external perimeter
G1 X232.534 Y212.983 E2.13042 ; external perimeter
G1 X231.130 Y213.476 E2.13633 ; external perimeter
G1 X229.704 Y213.880 E2.14221 ; external perimeter
G1 X228.401 Y214.179 E2.14752 ; external perimeter
G1 X226.947 Y214.443 E2.15338 ; external perimeter
G1 X225.347 Y214.656 E2.15978 ; external perimeter
G1 X223.528 Y214.806 E2.16703 ; external perimeter
G1 X222.141 Y214.861 E2.17253 ; external perimeter
G1 X220.281 Y214.850 E2.17991 ; external perimeter
G1 X218.767 Y214.772 E2.18593 ; external perimeter
G1 X217.325 Y214.636 E2.19168 ; external perimeter
G1 X215.834 Y214.441 E2.19765 ; external perimeter
G1 X215.833 Y201.732 E2.24808 ; external perimeter
G1 X213.361 Y199.532 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X214.421 Y199.304 E2.25238 ; external perimeter
G1 X215.855 Y199.062 E2.25815 ; external perimeter
G1 X217.699 Y198.838 E2.26552 ; external perimeter
G1 X219.639 Y198.701 E2.27324 ; external perimeter
G1 X221.577 Y198.663 E2.28093 ; external perimeter
G1 X222.802 Y198.684 E2.28579 ; external perimeter
G1 X224.288 Y198.766 E2.29170 ; external perimeter
G1 X226.226 Y198.958 E2.29943 ; external perimeter
G1 X227.517 Y199.146 E2.30461 ; external perimeter
G1 X229.394 Y199.505 E2.31219 ; external perimeter
G1 X231.172 Y199.956 E2.31947 ; external perimeter
G1 X232.364 Y200.326 E2.32442 ; external perimeter
G1 X233.733 Y200.830 E2.33021 ; external perimeter
G1 X234.076 Y200.974 E2.33169 ; external perimeter
G1 X235.074 Y201.425 E2.33603 ; external perimeter
G1 X236.147 Y201.990 E2.34084 ; external perimeter
G1 X237.322 Y202.734 E2.34636 ; external perimeter
G1 X238.107 Y203.330 E2.35027 ; external perimeter
G1 X238.555 Y203.730 E2.35266 ; external perimeter
G1 X239.052 Y204.216 E2.35542 ; external perimeter
G1 X239.540 Y204.784 E2.35839 ; external perimeter
G1 X239.809 Y205.163 E2.36023 ; external perimeter
G1 X240.100 Y205.624 E2.36239 ; external perimeter
G1 X240.420 Y206.293 E2.36534 ; external perimeter
G1 X240.549 Y206.674 E2.36693 ; external perimeter
G1 X240.666 Y207.110 E2.36873 ; external perimeter
G1 X240.753 Y207.804 E2.37150 ; external perimeter
G1 X240.743 Y208.336 E2.37361 ; external perimeter
G1 X240.672 Y208.849 E2.37567 ; external perimeter
G1 X240.561 Y209.305 E2.37753 ; external perimeter
G1 X240.310 Y209.964 E2.38033 ; external perimeter
G1 X240.199 Y210.191 E2.38133 ; external perimeter
G1 X239.781 Y210.886 E2.38455 ; external perimeter
G1 X239.470 Y211.300 E2.38660 ; external perimeter
G1 X239.028 Y211.808 E2.38927 ; external perimeter
G1 X238.541 Y212.292 E2.39200 ; external perimeter
G1 X237.873 Y212.858 E2.39547 ; external perimeter
G1 X237.560 Y213.095 E2.39703 ; external perimeter
G1 X236.719 Y213.666 E2.40107 ; external perimeter
G1 X235.622 Y214.297 E2.40609 ; external perimeter
G1 X234.291 Y214.935 E2.41195 ; external perimeter
G1 X233.100 Y215.414 E2.41704 ; external perimeter
G1 X231.952 Y215.808 E2.42186 ; external perimeter
G1 X230.206 Y216.303 E2.42906 ; external perimeter
G1 X228.660 Y216.649 E2.43534 ; external perimeter
G1 X226.749 Y216.971 E2.44303 ; external perimeter
G1 X225.523 Y217.123 E2.44793 ; external perimeter
G1 X224.892 Y217.182 E2.45045 ; external perimeter
G1 X223.707 Y217.273 E2.45517 ; external perimeter
G1 X222.326 Y217.328 E2.46065 ; external perimeter
G1 X220.384 Y217.326 E2.46836 ; external perimeter
G1 X218.549 Y217.234 E2.47565 ; external perimeter
G1 X216.666 Y217.047 E2.48316 ; external perimeter
G1 X215.030 Y216.805 E2.48972 ; external perimeter
G1 X213.361 Y216.473 E2.49647 ; external perimeter
G1 X213.361 Y199.712 E2.56298 ; external perimeter
G1 X213.906 Y199.943 F1800.000 ; move to first infill point
G1 F1200.000
G1 X214.683 Y200.600 E2.56811 ; infill
G1 X214.661 Y200.723 E2.56875 ; infill
G1 F1200.000
G1 X214.619 Y200.971 E2.56994 ; infill
G1 F1200.000
G1 X214.597 Y201.095 E2.57049 ; infill
G1 X214.597 Y214.894 E2.63142 ; infill
G1 F1200.000
G1 X214.641 Y215.143 E2.63262 ; infill
G1 F1200.000
G1 X214.684 Y215.393 E2.63390 ; infill
G1 X214.819 Y215.443 E2.63463 ; infill
G1 F1200.000
G1 X215.090 Y215.545 E2.63599 ; infill
G1 F1200.000
G1 X215.234 Y215.597 E2.63667 ; infill
G1 X216.817 Y215.818 E2.64374 ; infill
G1 X218.692 Y216.005 E2.65207 ; infill
G1 X220.416 Y216.088 E2.65970 ; infill
G1 X222.178 Y216.094 E2.66749 ; infill
G1 X223.619 Y216.039 E2.67387 ; infill
G1 X225.497 Y215.882 E2.68221 ; infill
G1 X227.121 Y215.661 E2.68946 ; infill
G1 X228.422 Y215.433 E2.69530 ; infill
G1 X229.902 Y215.104 E2.70200 ; infill
G1 X231.524 Y214.646 E2.70945 ; infill
G1 X232.667 Y214.251 E2.71480 ; infill
G1 X233.765 Y213.816 E2.72003 ; infill
G1 X235.044 Y213.198 E2.72631 ; infill
G1 X236.145 Y212.564 E2.73193 ; infill
G1 X236.837 Y212.090 E2.73564 ; infill
G1 X237.589 Y211.483 E2.73991 ; infill
G1 X238.126 Y210.963 E2.74322 ; infill
G1 X238.507 Y210.521 E2.74580 ; infill
G1 X238.755 Y210.195 E2.74761 ; infill
G1 X239.109 Y209.599 E2.75068 ; infill
G1 X239.313 Y209.130 E2.75293 ; infill
G1 X239.436 Y208.722 E2.75482 ; infill
G1 X239.506 Y208.239 E2.75698 ; infill
G1 X239.523 Y207.869 E2.75862 ; infill
G1 X239.414 Y207.191 E2.76166 ; infill
G1 X239.275 Y206.759 E2.76366 ; infill
G1 X239.019 Y206.221 E2.76630 ; infill
G1 X238.781 Y205.852 E2.76824 ; infill
G1 X238.565 Y205.545 E2.76990 ; infill
G1 X238.150 Y205.062 E2.77272 ; infill
G1 X237.712 Y204.633 E2.77543 ; infill
G1 X237.087 Y204.101 E2.77906 ; infill
G1 X236.615 Y203.753 E2.78165 ; infill
G1 X235.740 Y203.191 E2.78625 ; infill
G1 X234.531 Y202.537 E2.79233 ; infill
G1 X233.280 Y201.980 E2.79838 ; infill
G1 X232.086 Y201.538 E2.80402 ; infill
G1 X230.825 Y201.142 E2.80986 ; infill
G1 X229.125 Y200.714 E2.81762 ; infill
G1 X227.972 Y200.479 E2.82282 ; infill
G1 X227.321 Y200.370 E2.82574 ; infill
G1 X226.076 Y200.187 E2.83130 ; infill
G1 X224.695 Y200.043 E2.83744 ; infill
G1 X222.801 Y199.921 E2.84584 ; infill
G1 X221.103 Y199.903 E2.85335 ; infill
G1 X219.375 Y199.955 E2.86099 ; infill
G1 X217.623 Y200.089 E2.86877 ; infill
G1 X216.032 Y200.284 E2.87585 ; infill
G1 X215.232 Y200.400 E2.87943 ; infill
G1 X215.122 Y200.440 E2.87994 ; infill
G1 F1200.000
G1 X214.902 Y200.520 E2.88105 ; infill
G1 F1200.000
G1 X214.683 Y200.600 E2.88223 ; infill
G1 Z11.750 F1800.000 ; move to next layer (6)
G1 X215.489 Y201.261 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X217.325 Y201.016 E2.88958 ; external perimeter
G1 X218.117 Y200.937 E2.89274 ; external perimeter
G1 X219.432 Y200.841 E2.89797 ; external perimeter
G1 X221.094 Y200.789 E2.90457 ; external perimeter
G1 X222.784 Y200.813 E2.91128 ; external perimeter
G1 X224.642 Y200.929 E2.91866 ; external perimeter
G1 X226.159 Y201.095 E2.92472 ; external perimeter
G1 X227.795 Y201.352 E2.93129 ; external perimeter
G1 X229.220 Y201.647 E2.93707 ; external perimeter
G1 X230.563 Y201.994 E2.94257 ; external perimeter
G1 X232.083 Y202.480 E2.94890 ; external perimeter
G1 X232.975 Y202.819 E2.95269 ; external perimeter
G1 X233.785 Y203.169 E2.95619 ; external perimeter
G1 X234.979 Y203.773 E2.96150 ; external perimeter
G1 X235.990 Y204.399 E2.96622 ; external perimeter
G1 X236.518 Y204.782 E2.96881 ; external perimeter
G1 X236.968 Y205.154 E2.97112 ; external perimeter
G1 X237.598 Y205.774 E2.97463 ; external perimeter
G1 X237.887 Y206.124 E2.97643 ; external perimeter
G1 X238.123 Y206.461 E2.97807 ; external perimeter
G1 X238.313 Y206.789 E2.97957 ; external perimeter
G1 X238.529 Y207.315 E2.98183 ; external perimeter
G1 X238.601 Y207.626 E2.98310 ; external perimeter
G1 X238.631 Y207.923 E2.98428 ; external perimeter
G1 X238.620 Y208.234 E2.98551 ; external perimeter
G1 X238.569 Y208.531 E2.98671 ; external perimeter
G1 X238.486 Y208.811 E2.98787 ; external perimeter
G1 X238.358 Y209.120 E2.98919 ; external perimeter
G1 X238.037 Y209.670 E2.99172 ; external perimeter
G1 X237.748 Y210.048 E2.99361 ; external perimeter
G1 X237.425 Y210.410 E2.99553 ; external perimeter
G1 X237.034 Y210.787 E2.99769 ; external perimeter
G1 X236.576 Y211.170 E3.00006 ; external perimeter
G1 X236.182 Y211.466 E3.00201 ; external perimeter
G1 X235.636 Y211.834 E3.00463 ; external perimeter
G1 X235.063 Y212.178 E3.00728 ; external perimeter
G1 X233.970 Y212.742 E3.01216 ; external perimeter
G1 X233.425 Y212.992 E3.01454 ; external perimeter
G1 X232.758 Y213.265 E3.01740 ; external perimeter
G1 X232.175 Y213.487 E3.01987 ; external perimeter
G1 X231.250 Y213.799 E3.02375 ; external perimeter
G1 X229.765 Y214.220 E3.02987 ; external perimeter
G1 X228.466 Y214.517 E3.03516 ; external perimeter
G1 X226.650 Y214.835 E3.04248 ; external perimeter
G1 X225.380 Y214.999 E3.04756 ; external perimeter
G1 X223.475 Y215.154 E3.05515 ; external perimeter
G1 X222.153 Y215.205 E3.06039 ; external perimeter
G1 X220.218 Y215.192 E3.06807 ; external perimeter
G1 X218.742 Y215.115 E3.07394 ; external perimeter
G1 X217.366 Y214.987 E3.07942 ; external perimeter
G1 X215.489 Y214.741 E3.08693 ; external perimeter
G1 X215.489 Y201.441 E3.13971 ; external perimeter
G1 X213.361 Y199.532 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X214.421 Y199.304 E3.14401 ; external perimeter
G1 X215.817 Y199.068 E3.14963 ; external perimeter
G1 X217.699 Y198.838 E3.15715 ; external perimeter
G1 X219.694 Y198.699 E3.16509 ; external perimeter
G1 X221.096 Y198.661 E3.17065 ; external perimeter
G1 X222.960 Y198.690 E3.17805 ; external perimeter
G1 X224.243 Y198.762 E3.18315 ; external perimeter
G1 X226.238 Y198.960 E3.19110 ; external perimeter
G1 X227.455 Y199.135 E3.19598 ; external perimeter
G1 X228.309 Y199.285 E3.19942 ; external perimeter
G1 X229.465 Y199.521 E3.20411 ; external perimeter
G1 X231.227 Y199.972 E3.21132 ; external perimeter
G1 X232.364 Y200.325 E3.21605 ; external perimeter
G1 X233.733 Y200.830 E3.22184 ; external perimeter
G1 X234.152 Y201.006 E3.22364 ; external perimeter
G1 X235.092 Y201.433 E3.22774 ; external perimeter
G1 X236.146 Y201.990 E3.23247 ; external perimeter
G1 X237.350 Y202.754 E3.23813 ; external perimeter
G1 X238.106 Y203.329 E3.24190 ; external perimeter
G1 X238.652 Y203.817 E3.24480 ; external perimeter
G1 X239.085 Y204.250 E3.24723 ; external perimeter
G1 X239.539 Y204.783 E3.25001 ; external perimeter
G1 X239.869 Y205.247 E3.25227 ; external perimeter
G1 X240.110 Y205.641 E3.25410 ; external perimeter
G1 X240.420 Y206.292 E3.25696 ; external perimeter
G1 X240.579 Y206.761 E3.25893 ; external perimeter
G1 X240.672 Y207.133 E3.26045 ; external perimeter
G1 X240.754 Y207.816 E3.26318 ; external perimeter
G1 X240.748 Y208.299 E3.26509 ; external perimeter
G1 X240.717 Y208.600 E3.26630 ; external perimeter
G1 X240.663 Y208.904 E3.26752 ; external perimeter
G1 X240.562 Y209.303 E3.26915 ; external perimeter
G1 X240.322 Y209.938 E3.27185 ; external perimeter
G1 X240.184 Y210.222 E3.27310 ; external perimeter
G1 X239.775 Y210.894 E3.27622 ; external perimeter
G1 X239.251 Y211.566 E3.27961 ; external perimeter
G1 X238.541 Y212.292 E3.28363 ; external perimeter
G1 X237.912 Y212.826 E3.28691 ; external perimeter
G1 X237.530 Y213.118 E3.28882 ; external perimeter
G1 X236.719 Y213.666 E3.29270 ; external perimeter
G1 X235.622 Y214.297 E3.29772 ; external perimeter
G1 X234.265 Y214.946 E3.30369 ; external perimeter
G1 X233.100 Y215.414 E3.30867 ; external perimeter
G1 X231.998 Y215.793 E3.31330 ; external perimeter
G1 X231.410 Y215.974 E3.31574 ; external perimeter
G1 X230.208 Y216.302 E3.32068 ; external perimeter
G1 X228.660 Y216.648 E3.32698 ; external perimeter
G1 X226.687 Y216.979 E3.33492 ; external perimeter
G1 X225.552 Y217.120 E3.33946 ; external perimeter
G1 X224.786 Y217.192 E3.34251 ; external perimeter
G1 X223.707 Y217.273 E3.34680 ; external perimeter
G1 X222.394 Y217.326 E3.35202 ; external perimeter
G1 X220.403 Y217.326 E3.35992 ; external perimeter
G1 X218.540 Y217.234 E3.36732 ; external perimeter
G1 X216.613 Y217.041 E3.37500 ; external perimeter
G1 X214.979 Y216.796 E3.38156 ; external perimeter
G1 X213.361 Y216.473 E3.38811 ; external perimeter
G1 X213.361 Y199.712 E3.45461 ; external perimeter
G1 X214.487 Y200.441 F1800.000 ; move to first infill point
G1 F1200.000
G1 X214.556 Y200.403 E3.45490 ; infill
G1 F1200.000
G1 X214.764 Y200.324 E3.45562 ; infill
G1 F1200.000
G1 X214.903 Y200.284 E3.45606 ; infill
G1 X215.970 Y200.122 E3.45935 ; infill
G1 X217.211 Y199.964 E3.46315 ; infill
G1 X218.018 Y199.880 E3.46562 ; infill
G1 X219.366 Y199.783 E3.46973 ; infill
G1 X221.098 Y199.725 E3.47501 ; infill
G1 X222.838 Y199.751 E3.48030 ; infill
G1 X224.745 Y199.875 E3.48612 ; infill
G1 X226.109 Y200.018 E3.49029 ; infill
G1 X227.286 Y200.191 E3.49392 ; infill
G1 X227.998 Y200.309 E3.49611 ; infill
G1 X229.232 Y200.561 E3.49994 ; infill
G1 X230.928 Y200.993 E3.50527 ; infill
G1 X232.445 Y201.485 E3.51012 ; infill
G1 X233.364 Y201.829 E3.51311 ; infill
G1 X234.250 Y202.216 E3.51605 ; infill
G1 X235.611 Y202.912 E3.52070 ; infill
G1 X236.597 Y203.531 E3.52425 ; infill
G1 X237.179 Y203.955 E3.52644 ; infill
G1 X237.695 Y204.383 E3.52848 ; infill
G1 X238.302 Y204.973 E3.53105 ; infill
G1 X238.699 Y205.436 E3.53291 ; infill
G1 X239.006 Y205.871 E3.53453 ; infill
G1 X239.278 Y206.355 E3.53622 ; infill
G1 X239.525 Y206.951 E3.53818 ; infill
G1 X239.642 Y207.418 E3.53965 ; infill
G1 X239.692 Y207.856 E3.54099 ; infill
G1 X239.680 Y208.306 E3.54236 ; infill
G1 X239.610 Y208.741 E3.54370 ; infill
G1 X239.493 Y209.138 E3.54496 ; infill
G1 X239.293 Y209.624 E3.54656 ; infill
G1 X238.900 Y210.290 E3.54891 ; infill
G1 X238.578 Y210.707 E3.55052 ; infill
G1 X238.206 Y211.131 E3.55223 ; infill
G1 X237.729 Y211.589 E3.55424 ; infill
G1 X237.246 Y211.997 E3.55617 ; infill
G1 X236.786 Y212.339 E3.55791 ; infill
G1 X236.155 Y212.763 E3.56023 ; infill
G1 X235.124 Y213.350 E3.56384 ; infill
G1 X233.837 Y213.972 E3.56819 ; infill
G1 X232.728 Y214.416 E3.57182 ; infill
G1 X231.578 Y214.810 E3.57552 ; infill
G1 X230.015 Y215.253 E3.58047 ; infill
G1 X228.456 Y215.602 E3.58533 ; infill
G1 X226.797 Y215.886 E3.59045 ; infill
G1 X225.504 Y216.055 E3.59442 ; infill
G1 X223.550 Y216.215 E3.60039 ; infill
G1 X222.182 Y216.265 E3.60455 ; infill
G1 X220.430 Y216.260 E3.60988 ; infill
G1 X218.676 Y216.176 E3.61523 ; infill
G1 X216.745 Y215.982 E3.62113 ; infill
G1 X214.904 Y215.718 E3.62679 ; infill
G1 F1200.000
G1 X214.695 Y215.638 E3.62753 ; infill
G1 F1200.000
G1 X214.486 Y215.557 E3.62833 ; infill
G1 X214.466 Y215.436 E3.62877 ; infill
G1 F1200.000
G1 X214.425 Y215.194 E3.62958 ; infill
G1 X214.425 Y200.810 E3.67682 ; infill
G1 X214.446 Y200.687 E3.67723 ; infill
G1 F1200.000
G1 X214.457 Y200.619 E3.67747 ; infill
M106 S219.3 ; enable fan
G1 Z12.950 F1800.000 ; move to next layer (7)
G1 X215.145 Y200.972 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X215.145 Y215.027 E3.73325 ; external perimeter
G1 X216.951 Y215.286 E3.74048 ; external perimeter
G1 X218.881 Y215.470 E3.74818 ; external perimeter
G1 X220.150 Y215.534 E3.75322 ; external perimeter
G1 X222.167 Y215.548 E3.76122 ; external perimeter
G1 X223.810 Y215.479 E3.76775 ; external perimeter
G1 X225.633 Y215.316 E3.77501 ; external perimeter
G1 X227.394 Y215.067 E3.78207 ; external perimeter
G1 X228.536 Y214.854 E3.78668 ; external perimeter
G1 X229.616 Y214.611 E3.79107 ; external perimeter
G1 X230.375 Y214.414 E3.79418 ; external perimeter
G1 X231.376 Y214.120 E3.79833 ; external perimeter
G1 X232.255 Y213.824 E3.80200 ; external perimeter
G1 X233.131 Y213.488 E3.80573 ; external perimeter
G1 X233.826 Y213.190 E3.80873 ; external perimeter
G1 X234.539 Y212.850 E3.81186 ; external perimeter
G1 X235.195 Y212.499 E3.81481 ; external perimeter
G1 X235.808 Y212.132 E3.81765 ; external perimeter
G1 X236.347 Y211.772 E3.82022 ; external perimeter
G1 X236.832 Y211.408 E3.82263 ; external perimeter
G1 X237.268 Y211.040 E3.82489 ; external perimeter
G1 X237.916 Y210.418 E3.82846 ; external perimeter
G1 X237.932 Y212.806 E3.83793 ; external perimeter
G1 X237.695 Y212.995 E3.83914 ; external perimeter
G1 X236.992 Y213.490 E3.84255 ; external perimeter
G1 X235.943 Y214.124 E3.84741 ; external perimeter
G1 X234.790 Y214.710 E3.85254 ; external perimeter
G1 X233.495 Y215.263 E3.85813 ; external perimeter
G1 X232.049 Y215.777 E3.86422 ; external perimeter
G1 X231.359 Y215.989 E3.86708 ; external perimeter
G1 X230.214 Y216.301 E3.87179 ; external perimeter
G1 X228.659 Y216.649 E3.87812 ; external perimeter
G1 X227.048 Y216.928 E3.88460 ; external perimeter
G1 X225.394 Y217.137 E3.89122 ; external perimeter
G1 X223.491 Y217.285 E3.89880 ; external perimeter
G1 X221.738 Y217.338 E3.90575 ; external perimeter
G1 X220.421 Y217.327 E3.91098 ; external perimeter
G1 X218.533 Y217.233 E3.91848 ; external perimeter
G1 X216.561 Y217.034 E3.92635 ; external perimeter
G1 X214.928 Y216.788 E3.93290 ; external perimeter
G1 X213.361 Y216.473 E3.93924 ; external perimeter
G1 X213.361 Y199.532 E4.00646 ; external perimeter
G1 X214.421 Y199.304 E4.01077 ; external perimeter
G1 X215.779 Y199.073 E4.01623 ; external perimeter
G1 X217.702 Y198.837 E4.02392 ; external perimeter
G1 X219.742 Y198.696 E4.03203 ; external perimeter
G1 X221.096 Y198.661 E4.03741 ; external perimeter
G1 X221.771 Y198.663 E4.04009 ; external perimeter
G1 X222.987 Y198.691 E4.04491 ; external perimeter
G1 X224.204 Y198.759 E4.04975 ; external perimeter
G1 X225.015 Y198.827 E4.05298 ; external perimeter
G1 X226.246 Y198.961 E4.05789 ; external perimeter
G1 X227.391 Y199.125 E4.06248 ; external perimeter
G1 X228.697 Y199.360 E4.06775 ; external perimeter
G1 X229.565 Y199.544 E4.07127 ; external perimeter
G1 X230.512 Y199.775 E4.07514 ; external perimeter
G1 X231.282 Y199.987 E4.07831 ; external perimeter
G1 X232.365 Y200.326 E4.08281 ; external perimeter
G1 X233.382 Y200.695 E4.08710 ; external perimeter
G1 X234.231 Y201.039 E4.09073 ; external perimeter
G1 X235.108 Y201.441 E4.09457 ; external perimeter
G1 X236.150 Y201.992 E4.09924 ; external perimeter
G1 X236.984 Y202.504 E4.10313 ; external perimeter
G1 X237.426 Y202.807 E4.10525 ; external perimeter
G1 X237.933 Y203.199 E4.10780 ; external perimeter
G1 X237.925 Y205.618 E4.11739 ; external perimeter
G1 X237.310 Y204.998 E4.12086 ; external perimeter
G1 X236.739 Y204.518 E4.12382 ; external perimeter
G1 X236.285 Y204.185 E4.12605 ; external perimeter
G1 X235.725 Y203.815 E4.12871 ; external perimeter
G1 X235.145 Y203.473 E4.13139 ; external perimeter
G1 X233.974 Y202.877 E4.13660 ; external perimeter
G1 X233.108 Y202.501 E4.14035 ; external perimeter
G1 X232.444 Y202.247 E4.14317 ; external perimeter
G1 X231.368 Y201.879 E4.14768 ; external perimeter
G1 X230.653 Y201.662 E4.15064 ; external perimeter
G1 X229.668 Y201.402 E4.15469 ; external perimeter
G1 X228.916 Y201.227 E4.15775 ; external perimeter
G1 X227.854 Y201.013 E4.16205 ; external perimeter
G1 X226.204 Y200.754 E4.16868 ; external perimeter
G1 X224.710 Y200.589 E4.17464 ; external perimeter
G1 X222.797 Y200.469 E4.18225 ; external perimeter
G1 X221.091 Y200.445 E4.18902 ; external perimeter
G1 X219.418 Y200.497 E4.19566 ; external perimeter
G1 X218.163 Y200.587 E4.20066 ; external perimeter
G1 X217.283 Y200.674 E4.20417 ; external perimeter
G1 X215.324 Y200.947 E4.21201 ; external perimeter
G1 X214.253 Y200.522 F1800.000 ; move to first infill point
G1 F1200.000
G1 X214.253 Y215.474 E4.23960 ; infill
G1 X214.273 Y215.596 E4.23983 ; infill
G1 F1200.000
G1 X214.293 Y215.717 E4.24009 ; infill
G1 X214.483 Y215.792 E4.24053 ; infill
G1 F1200.000
G1 X214.578 Y215.829 E4.24072 ; infill
G1 X215.078 Y215.913 E4.24166 ; infill
G1 X216.855 Y216.170 E4.24500 ; infill
G1 X218.808 Y216.357 E4.24864 ; infill
G1 X220.442 Y216.434 E4.25168 ; infill
G1 X221.728 Y216.444 E4.25408 ; infill
G1 X223.442 Y216.392 E4.25726 ; infill
G1 X225.303 Y216.247 E4.26074 ; infill
G1 X226.916 Y216.045 E4.26376 ; infill
G1 X228.485 Y215.772 E4.26672 ; infill
G1 X230.000 Y215.434 E4.26960 ; infill
G1 X231.652 Y214.967 E4.27279 ; infill
G1 X233.170 Y214.430 E4.27579 ; infill
G1 X234.411 Y213.900 E4.27830 ; infill
G1 X235.517 Y213.339 E4.28060 ; infill
G1 X236.496 Y212.747 E4.28273 ; infill
G1 X237.411 Y212.097 E4.28482 ; infill
G1 E2.28482 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X237.414 Y203.917 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F1200.000
G1 X236.900 Y203.529 E2.00119 ; infill
G1 X236.497 Y203.254 E2.00210 ; infill
G1 X235.584 Y202.699 E2.00408 ; infill
G1 X234.342 Y202.068 E2.00666 ; infill
G1 X233.062 Y201.528 E2.00923 ; infill
G1 X231.647 Y201.034 E2.01200 ; infill
G1 X230.287 Y200.641 E2.01463 ; infill
G1 X229.099 Y200.355 E2.01689 ; infill
G1 X228.019 Y200.140 E2.01893 ; infill
G1 X227.248 Y200.010 E2.02037 ; infill
G1 X226.134 Y199.847 E2.02246 ; infill
G1 X224.778 Y199.701 E2.02499 ; infill
G1 X222.840 Y199.579 E2.02858 ; infill
G1 X221.075 Y199.554 E2.03185 ; infill
G1 X219.364 Y199.608 E2.03502 ; infill
G1 X217.791 Y199.726 E2.03794 ; infill
G1 X215.908 Y199.961 E2.04146 ; infill
G1 X214.579 Y200.166 E2.04395 ; infill
G1 X214.387 Y200.244 E2.04433 ; infill
G1 F1200.000
G1 X214.291 Y200.283 E2.04455 ; infill
G1 X214.253 Y200.522 E2.04507 ; infill
M106 S229.5 ; enable fan
G1 Z14.150 F1800.000 ; move to next layer (8)
G1 X214.801 Y200.691 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X214.801 Y215.302 E2.10304 ; external perimeter
G1 X215.855 Y215.482 E2.10729 ; external perimeter
G1 X217.449 Y215.689 E2.11366 ; external perimeter
G1 X218.692 Y215.801 E2.11862 ; external perimeter
G1 X220.086 Y215.876 E2.12416 ; external perimeter
G1 X220.979 Y215.897 E2.12770 ; external perimeter
G1 X222.180 Y215.892 E2.13247 ; external perimeter
G1 X223.361 Y215.850 E2.13716 ; external perimeter
G1 X224.287 Y215.790 E2.14084 ; external perimeter
G1 X225.452 Y215.683 E2.14548 ; external perimeter
G1 X226.582 Y215.541 E2.15000 ; external perimeter
G1 X227.512 Y215.396 E2.15374 ; external perimeter
G1 X228.603 Y215.192 E2.15814 ; external perimeter
G1 X229.638 Y214.960 E2.16235 ; external perimeter
G1 X230.603 Y214.708 E2.16631 ; external perimeter
G1 X231.982 Y214.279 E2.17204 ; external perimeter
G1 X231.982 Y215.791 E2.17803 ; external perimeter
G1 X231.306 Y216.005 E2.18085 ; external perimeter
G1 X230.207 Y216.303 E2.18537 ; external perimeter
G1 X228.657 Y216.649 E2.19167 ; external perimeter
G1 X227.376 Y216.878 E2.19683 ; external perimeter
G1 X226.569 Y216.996 E2.20007 ; external perimeter
G1 X225.395 Y217.137 E2.20476 ; external perimeter
G1 X223.705 Y217.273 E2.21149 ; external perimeter
G1 X222.523 Y217.324 E2.21618 ; external perimeter
G1 X221.703 Y217.338 E2.21944 ; external perimeter
G1 X220.296 Y217.324 E2.22502 ; external perimeter
G1 X218.592 Y217.238 E2.23179 ; external perimeter
G1 X217.522 Y217.144 E2.23605 ; external perimeter
G1 X216.510 Y217.028 E2.24010 ; external perimeter
G1 X215.276 Y216.847 E2.24505 ; external perimeter
G1 X213.781 Y216.567 E2.25108 ; external perimeter
G1 X213.361 Y216.472 E2.25279 ; external perimeter
G1 X213.361 Y199.532 E2.32001 ; external perimeter
G1 X214.422 Y199.304 E2.32432 ; external perimeter
G1 X215.434 Y199.130 E2.32839 ; external perimeter
G1 X216.641 Y198.956 E2.33323 ; external perimeter
G1 X217.698 Y198.837 E2.33745 ; external perimeter
G1 X218.929 Y198.740 E2.34235 ; external perimeter
G1 X219.795 Y198.694 E2.34579 ; external perimeter
G1 X221.096 Y198.661 E2.35095 ; external perimeter
G1 X223.013 Y198.692 E2.35856 ; external perimeter
G1 X224.499 Y198.781 E2.36447 ; external perimeter
G1 X226.175 Y198.952 E2.37115 ; external perimeter
G1 X227.331 Y199.115 E2.37579 ; external perimeter
G1 X228.484 Y199.317 E2.38043 ; external perimeter
G1 X229.589 Y199.549 E2.38491 ; external perimeter
G1 X230.916 Y199.883 E2.39034 ; external perimeter
G1 X231.984 Y200.211 E2.39478 ; external perimeter
G1 X231.983 Y201.718 E2.40076 ; external perimeter
G1 X230.750 Y201.332 E2.40588 ; external perimeter
G1 X229.817 Y201.084 E2.40971 ; external perimeter
G1 X228.921 Y200.875 E2.41337 ; external perimeter
G1 X227.918 Y200.675 E2.41742 ; external perimeter
G1 X226.851 Y200.498 E2.42172 ; external perimeter
G1 X225.924 Y200.371 E2.42543 ; external perimeter
G1 X224.781 Y200.250 E2.42999 ; external perimeter
G1 X223.869 Y200.180 E2.43362 ; external perimeter
G1 X222.694 Y200.121 E2.43829 ; external perimeter
G1 X221.497 Y200.100 E2.44304 ; external perimeter
G1 X219.398 Y200.153 E2.45137 ; external perimeter
G1 X217.714 Y200.282 E2.45807 ; external perimeter
G1 X216.170 Y200.471 E2.46425 ; external perimeter
G1 X214.979 Y200.663 E2.46903 ; external perimeter
G1 E0.46903 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X231.468 Y200.804 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F1200.000
G1 X230.722 Y200.578 E2.00042 ; infill
G1 X229.427 Y200.252 E2.00115 ; infill
G1 X228.348 Y200.025 E2.00174 ; infill
G1 X227.218 Y199.828 E2.00236 ; infill
G1 X226.088 Y199.667 E2.00298 ; infill
G1 X224.843 Y199.536 E2.00366 ; infill
G1 X223.917 Y199.465 E2.00417 ; infill
G1 X222.721 Y199.403 E2.00481 ; infill
G1 X221.495 Y199.381 E2.00548 ; infill
G1 X219.823 Y199.415 E2.00638 ; infill
G1 X218.977 Y199.461 E2.00684 ; infill
G1 X217.647 Y199.567 E2.00757 ; infill
G1 X216.065 Y199.762 E2.00843 ; infill
G1 X214.255 Y200.063 E2.00943 ; infill
G1 X214.100 Y200.129 E2.00952 ; infill
G1 X214.081 Y200.252 E2.00958 ; infill
G1 X214.081 Y215.738 E2.01798 ; infill
G1 X214.104 Y215.873 E2.01805 ; infill
G1 X214.252 Y215.931 E2.01814 ; infill
G1 X215.752 Y216.192 E2.01896 ; infill
G1 X217.366 Y216.403 E2.01984 ; infill
G1 X218.637 Y216.519 E2.02053 ; infill
G1 X220.318 Y216.603 E2.02145 ; infill
G1 X221.701 Y216.616 E2.02220 ; infill
G1 X222.501 Y216.603 E2.02263 ; infill
G1 X223.660 Y216.553 E2.02326 ; infill
G1 X225.323 Y216.419 E2.02416 ; infill
G1 X226.474 Y216.281 E2.02479 ; infill
G1 X227.260 Y216.165 E2.02522 ; infill
G1 X228.515 Y215.942 E2.02591 ; infill
G1 X229.803 Y215.658 E2.02663 ; infill
G1 X230.792 Y215.401 E2.02718 ; infill
G1 X231.466 Y215.201 E2.02756 ; infill
M106 S244.8 ; enable fan
G1 Z15.350 F1800.000 ; move to next layer (9)
G1 E0.02756 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X214.457 Y200.399 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X214.457 Y215.593 E2.06029 ; external perimeter
G1 X215.786 Y215.820 E2.06564 ; external perimeter
G1 X217.490 Y216.040 E2.07246 ; external perimeter
G1 X218.668 Y216.145 E2.07715 ; external perimeter
G1 X220.023 Y216.219 E2.08254 ; external perimeter
G1 X221.059 Y216.242 E2.08665 ; external perimeter
G1 X222.195 Y216.236 E2.09116 ; external perimeter
G1 X223.854 Y216.166 E2.09775 ; external perimeter
G1 X224.409 Y216.119 E2.09996 ; external perimeter
G1 X224.410 Y217.216 E2.10431 ; external perimeter
G1 X223.428 Y217.288 E2.10822 ; external perimeter
G1 X221.661 Y217.339 E2.11523 ; external perimeter
G1 X220.296 Y217.324 E2.12065 ; external perimeter
G1 X218.595 Y217.238 E2.12741 ; external perimeter
G1 X216.917 Y217.078 E2.13410 ; external perimeter
G1 X215.381 Y216.865 E2.14025 ; external perimeter
G1 X213.794 Y216.570 E2.14665 ; external perimeter
G1 X213.361 Y216.472 E2.14841 ; external perimeter
G1 X213.361 Y199.532 E2.21563 ; external perimeter
G1 X214.422 Y199.304 E2.21994 ; external perimeter
G1 X215.706 Y199.084 E2.22511 ; external perimeter
G1 X216.716 Y198.946 E2.22916 ; external perimeter
G1 X217.698 Y198.837 E2.23308 ; external perimeter
G1 X218.869 Y198.743 E2.23774 ; external perimeter
G1 X219.848 Y198.691 E2.24163 ; external perimeter
G1 X221.096 Y198.661 E2.24658 ; external perimeter
G1 X221.974 Y198.664 E2.25006 ; external perimeter
G1 X223.041 Y198.693 E2.25430 ; external perimeter
G1 X224.413 Y198.769 E2.25975 ; external perimeter
G1 X224.412 Y199.881 E2.26416 ; external perimeter
G1 X222.820 Y199.781 E2.27049 ; external perimeter
G1 X221.562 Y199.756 E2.27548 ; external perimeter
G1 X220.420 Y199.769 E2.28002 ; external perimeter
G1 X219.383 Y199.810 E2.28413 ; external perimeter
G1 X217.680 Y199.940 E2.29091 ; external perimeter
G1 X216.133 Y200.128 E2.29709 ; external perimeter
G1 X214.635 Y200.370 E2.30312 ; external perimeter
G1 E0.30312 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
M107 ; disable fan
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = 224.519521
; cog_y = 207.947986
; cog_z = 8.877261
; filament_length_m = 0.0091 
; filament_volume_cm3 = 0.0643
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.022
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 8
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 4.2
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
