; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2022-09-17 at 14:55:48

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z4.550 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X156.957 Y218.234 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X166.595 Y231.499 E2.03438 ; external perimeter
G1 X166.058 Y232.099 E2.03607 ; external perimeter
G1 X164.925 Y233.249 E2.03945 ; external perimeter
G1 X163.704 Y234.380 E2.04294 ; external perimeter
G1 X162.417 Y235.468 E2.04648 ; external perimeter
G1 X161.085 Y236.498 E2.05001 ; external perimeter
G1 X159.698 Y237.477 E2.05357 ; external perimeter
G1 X158.290 Y238.382 E2.05708 ; external perimeter
G1 X156.826 Y239.233 E2.06063 ; external perimeter
G1 X155.400 Y239.978 E2.06400 ; external perimeter
G1 X153.937 Y240.657 E2.06738 ; external perimeter
G1 X152.495 Y241.241 E2.07065 ; external perimeter
G1 X151.098 Y241.722 E2.07374 ; external perimeter
G1 X149.711 Y242.114 E2.07677 ; external perimeter
G1 X148.364 Y242.405 E2.07966 ; external perimeter
G1 X147.113 Y242.588 E2.08231 ; external perimeter
G1 X145.917 Y242.672 E2.08482 ; external perimeter
G1 X144.797 Y242.654 E2.08717 ; external perimeter
G1 X143.782 Y242.540 E2.08931 ; external perimeter
G1 X142.864 Y242.334 E2.09128 ; external perimeter
G1 X142.042 Y242.036 E2.09312 ; external perimeter
G1 X141.354 Y241.672 E2.09475 ; external perimeter
G1 X140.764 Y241.230 E2.09629 ; external perimeter
G1 X140.278 Y240.720 E2.09777 ; external perimeter
G1 X139.897 Y240.147 E2.09922 ; external perimeter
G1 X139.601 Y239.479 E2.10075 ; external perimeter
G1 X139.413 Y238.754 E2.10232 ; external perimeter
G1 X139.327 Y237.939 E2.10404 ; external perimeter
G1 X139.352 Y237.034 E2.10593 ; external perimeter
G1 X139.497 Y236.055 E2.10801 ; external perimeter
G1 X139.760 Y235.024 E2.11024 ; external perimeter
G1 X140.141 Y233.948 E2.11263 ; external perimeter
G1 X140.651 Y232.805 E2.11526 ; external perimeter
G1 X141.275 Y231.644 E2.11802 ; external perimeter
G1 X142.012 Y230.461 E2.12095 ; external perimeter
G1 X142.850 Y229.278 E2.12399 ; external perimeter
G1 X143.803 Y228.078 E2.12720 ; external perimeter
G1 X144.848 Y226.893 E2.13051 ; external perimeter
G1 X145.978 Y225.729 E2.13391 ; external perimeter
G1 X147.177 Y224.604 E2.13736 ; external perimeter
G1 X148.440 Y223.521 E2.14085 ; external perimeter
G1 X149.784 Y222.467 E2.14443 ; external perimeter
G1 X151.168 Y221.476 E2.14800 ; external perimeter
G1 X152.571 Y220.562 E2.15151 ; external perimeter
G1 X154.000 Y219.717 E2.15499 ; external perimeter
G1 X155.465 Y218.939 E2.15847 ; external perimeter
G1 X156.794 Y218.311 E2.16155 ; external perimeter
G1 E0.16155 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X148.079 Y226.351 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X146.574 Y227.856 E2.00492 ; infill
G1 X145.512 Y228.949 E2.00845 ; infill
G1 X144.531 Y230.063 E2.01188 ; infill
G1 X143.642 Y231.182 E2.01519 ; infill
G1 X142.867 Y232.276 E2.01829 ; infill
G1 X142.192 Y233.358 E2.02124 ; infill
G1 X141.632 Y234.403 E2.02398 ; infill
G1 X141.181 Y235.411 E2.02653 ; infill
G1 X140.855 Y236.333 E2.02880 ; infill
G1 X140.771 Y236.662 E2.02958 ; infill
G1 X157.271 Y220.162 E2.08356 ; infill
G1 X158.535 Y221.902 E2.08853 ; infill
G1 X140.728 Y239.709 E2.14678 ; infill
G1 X140.841 Y239.966 E2.14743 ; infill
G1 X141.039 Y240.262 E2.14826 ; infill
G1 X141.298 Y240.534 E2.14913 ; infill
G1 X141.639 Y240.789 E2.15011 ; infill
G1 X142.075 Y241.020 E2.15125 ; infill
G1 X142.327 Y241.112 E2.15187 ; infill
G1 X159.798 Y223.641 E2.20903 ; infill
G1 X161.062 Y225.380 E2.21400 ; infill
G1 X144.950 Y241.492 E2.26670 ; infill
G1 X146.158 Y241.421 E2.26950 ; infill
G1 X147.272 Y241.258 E2.27211 ; infill
G1 X148.439 Y241.006 E2.27487 ; infill
G1 X162.326 Y227.120 E2.32029 ; infill
G1 X163.589 Y228.859 E2.32527 ; infill
G1 X153.144 Y239.305 E2.35944 ; infill
G1 E0.35944 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X162.834 Y232.617 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X164.343 Y231.109 E2.00493 ; infill
G1 X164.331 Y231.120 E2.00497 ; infill
G1 Z5.750 F1800.000 ; move to next layer (1)
G1 X157.073 Y217.816 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X167.031 Y231.521 E2.07220 ; external perimeter
G1 X166.309 Y232.329 E2.07649 ; external perimeter
G1 X165.180 Y233.476 E2.08288 ; external perimeter
G1 X163.857 Y234.697 E2.09002 ; external perimeter
G1 X162.637 Y235.728 E2.09636 ; external perimeter
G1 X161.287 Y236.772 E2.10313 ; external perimeter
G1 X159.892 Y237.757 E2.10991 ; external perimeter
G1 X158.492 Y238.657 E2.11652 ; external perimeter
G1 X156.915 Y239.571 E2.12375 ; external perimeter
G1 X155.542 Y240.287 E2.12989 ; external perimeter
G1 X154.077 Y240.967 E2.13630 ; external perimeter
G1 X152.528 Y241.590 E2.14293 ; external perimeter
G1 X151.190 Y242.050 E2.14854 ; external perimeter
G1 X149.794 Y242.444 E2.15430 ; external perimeter
G1 X148.345 Y242.752 E2.16018 ; external perimeter
G1 X147.150 Y242.926 E2.16497 ; external perimeter
G1 X145.926 Y243.012 E2.16983 ; external perimeter
G1 X144.748 Y242.992 E2.17451 ; external perimeter
G1 X143.726 Y242.876 E2.17859 ; external perimeter
G1 X142.771 Y242.661 E2.18248 ; external perimeter
G1 X141.850 Y242.321 E2.18637 ; external perimeter
G1 X141.172 Y241.960 E2.18942 ; external perimeter
G1 X140.538 Y241.485 E2.19257 ; external perimeter
G1 X140.012 Y240.933 E2.19559 ; external perimeter
G1 X139.614 Y240.340 E2.19843 ; external perimeter
G1 X139.269 Y239.560 E2.20181 ; external perimeter
G1 X139.077 Y238.811 E2.20488 ; external perimeter
G1 X138.988 Y237.982 E2.20818 ; external perimeter
G1 X139.013 Y237.005 E2.21206 ; external perimeter
G1 X139.171 Y235.950 E2.21630 ; external perimeter
G1 X139.433 Y234.930 E2.22047 ; external perimeter
G1 X139.813 Y233.851 E2.22501 ; external perimeter
G1 X140.344 Y232.660 E2.23019 ; external perimeter
G1 X140.989 Y231.458 E2.23560 ; external perimeter
G1 X141.727 Y230.276 E2.24113 ; external perimeter
G1 X142.557 Y229.102 E2.24684 ; external perimeter
G1 X143.542 Y227.859 E2.25313 ; external perimeter
G1 X144.615 Y226.644 E2.25956 ; external perimeter
G1 X145.733 Y225.493 E2.26593 ; external perimeter
G1 X146.873 Y224.423 E2.27213 ; external perimeter
G1 X148.234 Y223.250 E2.27927 ; external perimeter
G1 X149.600 Y222.180 E2.28615 ; external perimeter
G1 X151.028 Y221.161 E2.29311 ; external perimeter
G1 X152.397 Y220.270 E2.29959 ; external perimeter
G1 X153.801 Y219.439 E2.30607 ; external perimeter
G1 X155.343 Y218.620 E2.31300 ; external perimeter
G1 X156.908 Y217.887 E2.31985 ; external perimeter
G1 X156.844 Y220.187 F1800.000 ; move to first infill point
G1 F900.000
G1 X156.064 Y219.407 E2.32414 ; infill
G1 X155.142 Y219.955 E2.32830 ; infill
G1 X160.748 Y225.561 E2.35906 ; infill
G1 X164.652 Y230.934 E2.38484 ; infill
G1 X154.220 Y220.502 E2.44209 ; infill
G1 X153.298 Y221.050 E2.44625 ; infill
G1 X164.693 Y232.445 E2.50878 ; infill
G1 X163.921 Y233.142 E2.51282 ; infill
G1 X152.394 Y221.615 E2.57608 ; infill
G1 X151.505 Y222.196 E2.58020 ; infill
G1 X163.144 Y233.835 E2.64408 ; infill
G1 X162.350 Y234.510 E2.64812 ; infill
G1 X150.649 Y222.809 E2.71234 ; infill
G1 X149.806 Y223.435 E2.71641 ; infill
G1 X161.536 Y235.165 E2.78079 ; infill
G1 X160.708 Y235.807 E2.78485 ; infill
G1 X148.986 Y224.085 E2.84918 ; infill
G1 X148.189 Y224.757 E2.85323 ; infill
G1 X159.847 Y236.415 E2.91721 ; infill
G1 X158.972 Y237.010 E2.92131 ; infill
G1 X147.407 Y225.444 E2.98478 ; infill
G1 X146.654 Y226.161 E2.98882 ; infill
G1 X158.076 Y237.583 E3.05150 ; infill
G1 X157.151 Y238.128 E3.05567 ; infill
G1 X145.920 Y226.897 E3.11730 ; infill
G1 X145.205 Y227.651 E3.12134 ; infill
G1 X156.212 Y238.658 E3.18174 ; infill
G1 X155.239 Y239.154 E3.18598 ; infill
G1 X144.522 Y228.437 E3.24480 ; infill
G1 X143.864 Y229.249 E3.24885 ; infill
G1 X154.242 Y239.626 E3.30580 ; infill
G1 X153.217 Y240.071 E3.31014 ; infill
G1 X143.232 Y230.086 E3.36494 ; infill
G1 X142.631 Y230.954 E3.36903 ; infill
G1 X152.161 Y240.484 E3.42133 ; infill
G1 X151.062 Y240.855 E3.42583 ; infill
G1 X142.066 Y231.859 E3.47520 ; infill
G1 X141.547 Y232.809 E3.47940 ; infill
G1 X149.917 Y241.180 E3.52534 ; infill
G1 X148.720 Y241.451 E3.53011 ; infill
G1 X141.080 Y233.812 E3.57203 ; infill
G1 X140.942 Y234.145 E3.57343 ; infill
G1 X140.681 Y234.883 E3.57647 ; infill
G1 X147.449 Y241.650 E3.61361 ; infill
G1 X146.582 Y241.724 E3.61698 ; infill
G1 X146.064 Y241.735 E3.61899 ; infill
G1 X140.385 Y236.056 E3.65016 ; infill
G1 X140.289 Y236.676 E3.65259 ; infill
G1 X140.257 Y237.397 E3.65540 ; infill
G1 X144.495 Y241.635 E3.67866 ; infill
G1 X144.080 Y241.567 E3.68029 ; infill
G1 X143.474 Y241.412 E3.68272 ; infill
G1 X142.922 Y241.200 E3.68501 ; infill
G1 X142.520 Y240.991 E3.68677 ; infill
G1 X142.235 Y240.801 E3.68810 ; infill
G1 X141.976 Y240.586 E3.68940 ; infill
G1 X141.191 Y239.801 E3.69371 ; infill
G1 Z6.950 F1800.000 ; move to next layer (2)
G1 E1.69371 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X155.952 Y222.234 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X162.490 Y231.233 E2.04414 ; external perimeter
G1 X160.481 Y232.964 E2.05466 ; external perimeter
G1 X159.211 Y233.949 E2.06104 ; external perimeter
G1 X157.875 Y234.890 E2.06753 ; external perimeter
G1 X156.506 Y235.764 E2.07397 ; external perimeter
G1 X155.109 Y236.566 E2.08036 ; external perimeter
G1 X153.687 Y237.293 E2.08670 ; external perimeter
G1 X152.413 Y237.868 E2.09224 ; external perimeter
G1 X151.195 Y238.348 E2.09744 ; external perimeter
G1 X150.011 Y238.747 E2.10240 ; external perimeter
G1 X148.893 Y239.057 E2.10700 ; external perimeter
G1 X147.880 Y239.278 E2.11112 ; external perimeter
G1 X146.905 Y239.428 E2.11503 ; external perimeter
G1 X146.044 Y239.501 E2.11846 ; external perimeter
G1 X145.289 Y239.511 E2.12146 ; external perimeter
G1 X144.641 Y239.468 E2.12403 ; external perimeter
G1 X144.094 Y239.383 E2.12623 ; external perimeter
G1 X143.646 Y239.268 E2.12806 ; external perimeter
G1 X143.273 Y239.125 E2.12965 ; external perimeter
G1 X142.915 Y238.920 E2.13129 ; external perimeter
G1 X142.638 Y238.614 E2.13292 ; external perimeter
G1 X142.508 Y238.105 E2.13501 ; external perimeter
G1 X142.483 Y237.697 E2.13663 ; external perimeter
G1 X142.513 Y237.205 E2.13859 ; external perimeter
G1 X142.613 Y236.601 E2.14102 ; external perimeter
G1 X142.797 Y235.908 E2.14386 ; external perimeter
G1 X143.037 Y235.225 E2.14674 ; external perimeter
G1 X143.212 Y234.801 E2.14856 ; external perimeter
G1 X143.601 Y233.982 E2.15215 ; external perimeter
G1 X144.069 Y233.132 E2.15600 ; external perimeter
G1 X144.653 Y232.204 E2.16035 ; external perimeter
G1 X145.342 Y231.230 E2.16509 ; external perimeter
G1 X146.123 Y230.236 E2.17010 ; external perimeter
G1 X147.013 Y229.213 E2.17549 ; external perimeter
G1 X147.999 Y228.180 E2.18115 ; external perimeter
G1 X149.128 Y227.105 E2.18734 ; external perimeter
G1 X150.310 Y226.080 E2.19355 ; external perimeter
G1 X151.553 Y225.095 E2.19984 ; external perimeter
G1 X152.880 Y224.138 E2.20633 ; external perimeter
G1 X154.466 Y223.117 E2.21382 ; external perimeter
G1 X155.797 Y222.326 E2.21996 ; external perimeter
G1 X157.073 Y217.816 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X167.031 Y231.521 E2.28718 ; external perimeter
G1 X166.308 Y232.329 E2.29148 ; external perimeter
G1 X165.207 Y233.449 E2.29772 ; external perimeter
G1 X163.915 Y234.646 E2.30470 ; external perimeter
G1 X162.637 Y235.728 E2.31135 ; external perimeter
G1 X161.288 Y236.771 E2.31811 ; external perimeter
G1 X159.668 Y237.902 E2.32596 ; external perimeter
G1 X158.462 Y238.676 E2.33164 ; external perimeter
G1 X157.008 Y239.522 E2.33832 ; external perimeter
G1 X155.542 Y240.288 E2.34488 ; external perimeter
G1 X154.251 Y240.889 E2.35053 ; external perimeter
G1 X152.525 Y241.592 E2.35793 ; external perimeter
G1 X151.190 Y242.050 E2.36353 ; external perimeter
G1 X149.796 Y242.443 E2.36928 ; external perimeter
G1 X148.221 Y242.772 E2.37566 ; external perimeter
G1 X147.151 Y242.926 E2.37995 ; external perimeter
G1 X145.927 Y243.012 E2.38482 ; external perimeter
G1 X144.705 Y242.989 E2.38967 ; external perimeter
G1 X143.727 Y242.876 E2.39358 ; external perimeter
G1 X142.768 Y242.661 E2.39747 ; external perimeter
G1 X141.907 Y242.350 E2.40111 ; external perimeter
G1 X141.146 Y241.943 E2.40453 ; external perimeter
G1 X140.538 Y241.486 E2.40755 ; external perimeter
G1 X140.011 Y240.932 E2.41059 ; external perimeter
G1 X139.627 Y240.363 E2.41331 ; external perimeter
G1 X139.553 Y240.226 E2.41393 ; external perimeter
G1 X139.256 Y239.518 E2.41697 ; external perimeter
G1 X139.077 Y238.811 E2.41987 ; external perimeter
G1 X138.991 Y238.029 E2.42299 ; external perimeter
G1 X139.013 Y237.005 E2.42705 ; external perimeter
G1 X139.185 Y235.891 E2.43153 ; external perimeter
G1 X139.432 Y234.930 E2.43546 ; external perimeter
G1 X139.795 Y233.898 E2.43981 ; external perimeter
G1 X140.344 Y232.659 E2.44518 ; external perimeter
G1 X141.003 Y231.434 E2.45070 ; external perimeter
G1 X141.727 Y230.276 E2.45612 ; external perimeter
G1 X142.524 Y229.147 E2.46160 ; external perimeter
G1 X143.543 Y227.858 E2.46812 ; external perimeter
G1 X144.640 Y226.617 E2.47470 ; external perimeter
G1 X145.733 Y225.493 E2.48092 ; external perimeter
G1 X146.775 Y224.513 E2.48660 ; external perimeter
G1 X148.235 Y223.249 E2.49426 ; external perimeter
G1 X149.631 Y222.157 E2.50129 ; external perimeter
G1 X151.109 Y221.107 E2.50848 ; external perimeter
G1 X152.390 Y220.274 E2.51455 ; external perimeter
G1 X153.751 Y219.468 E2.52083 ; external perimeter
G1 X155.390 Y218.597 E2.52819 ; external perimeter
G1 X156.908 Y217.887 E2.53484 ; external perimeter
G1 X147.243 Y225.946 F1800.000 ; move to first infill point
G1 F1200.000
G1 X145.124 Y228.094 E2.55565 ; infill
G1 X144.074 Y229.283 E2.56659 ; infill
G1 X143.102 Y230.512 E2.57740 ; infill
G1 X142.349 Y231.578 E2.58640 ; infill
G1 X141.670 Y232.665 E2.59524 ; infill
G1 X141.057 Y233.804 E2.60416 ; infill
G1 X140.552 Y234.943 E2.61275 ; infill
G1 X140.387 Y235.413 E2.61619 ; infill
G1 X142.821 Y232.980 E2.63993 ; infill
G1 X142.477 Y233.705 E2.64547 ; infill
G1 X142.274 Y234.196 E2.64913 ; infill
G1 X142.004 Y234.966 E2.65476 ; infill
G1 X141.789 Y235.775 E2.66053 ; infill
G1 X141.666 Y236.515 E2.66571 ; infill
G1 X141.651 Y236.761 E2.66741 ; infill
G1 X139.853 Y238.559 E2.68495 ; infill
G1 X139.912 Y239.098 E2.68868 ; infill
G1 X140.039 Y239.600 E2.69226 ; infill
G1 X140.313 Y240.224 E2.69696 ; infill
G1 X140.509 Y240.515 E2.69938 ; infill
G1 X142.081 Y238.943 E2.71471 ; infill
G1 X142.567 Y239.480 E2.71971 ; infill
G1 X143.210 Y239.849 E2.72482 ; infill
G1 X143.627 Y240.008 E2.72790 ; infill
G1 X142.000 Y241.635 E2.74377 ; infill
G1 X142.624 Y241.860 E2.74834 ; infill
G1 X143.425 Y242.040 E2.75401 ; infill
G1 X144.126 Y242.121 E2.75887 ; infill
G1 X145.883 Y240.364 E2.77601 ; infill
G1 X146.645 Y240.354 E2.78127 ; infill
G1 X147.604 Y240.273 E2.78790 ; infill
G1 X148.773 Y240.086 E2.79607 ; infill
G1 X146.831 Y242.027 E2.81500 ; infill
G1 X147.446 Y241.939 E2.81929 ; infill
G1 X148.931 Y241.629 E2.82975 ; infill
G1 X150.199 Y241.271 E2.83884 ; infill
G1 X152.448 Y239.022 E2.86077 ; infill
G1 X153.487 Y238.613 E2.86848 ; infill
G1 X154.822 Y238.010 E2.87858 ; infill
G1 X156.305 Y237.253 E2.89006 ; infill
G1 X157.536 Y236.545 E2.89986 ; infill
G1 X154.626 Y239.456 E2.92825 ; infill
G1 X163.704 Y232.989 F1800.000 ; move to first infill point
G1 F1200.000
G1 X164.782 Y231.911 E2.93876 ; infill
G1 X164.772 Y231.921 E2.93886 ; infill
G1 X163.100 Y230.981 F1800.000 ; move to first infill point
G1 F1200.000
G1 X164.690 Y229.392 E2.95437 ; infill
G1 X163.591 Y227.879 E2.96727 ; infill
G1 X162.001 Y229.469 E2.98277 ; infill
G1 X160.902 Y227.956 E2.99567 ; infill
G1 X162.492 Y226.366 E3.01118 ; infill
G1 X161.393 Y224.854 E3.02407 ; infill
G1 X159.803 Y226.444 E3.03958 ; infill
G1 X158.704 Y224.931 E3.05247 ; infill
G1 X160.294 Y223.341 E3.06798 ; infill
G1 X159.195 Y221.829 E3.08088 ; infill
G1 X157.605 Y223.418 E3.09638 ; infill
G1 X156.506 Y221.906 E3.10928 ; infill
G1 X158.096 Y220.316 E3.12478 ; infill
G1 X157.156 Y219.021 E3.13582 ; infill
G1 X156.442 Y219.359 E3.14127 ; infill
G1 X153.518 Y222.283 E3.16979 ; infill
G1 X151.565 Y223.526 E3.18575 ; infill
G1 X150.182 Y224.522 E3.19751 ; infill
G1 X148.890 Y225.545 E3.20888 ; infill
G1 X147.661 Y226.612 E3.22010 ; infill
G1 X146.485 Y227.732 E3.23130 ; infill
G1 X145.453 Y228.811 E3.24160 ; infill
G1 X144.520 Y229.886 E3.25142 ; infill
G1 X143.695 Y230.933 E3.26061 ; infill
G1 X142.964 Y231.967 E3.26934 ; infill
G1 X142.340 Y232.961 E3.27744 ; infill
G1 X141.753 Y234.047 E3.28595 ; infill
M106 S196.35 ; enable fan
G1 Z8.150 F1800.000 ; move to next layer (3)
G1 E1.28595 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X156.067 Y221.807 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X162.935 Y231.260 E2.04637 ; external perimeter
G1 X161.855 Y232.249 E2.05218 ; external perimeter
G1 X160.708 Y233.223 E2.05815 ; external perimeter
G1 X159.422 Y234.220 E2.06461 ; external perimeter
G1 X158.080 Y235.167 E2.07112 ; external perimeter
G1 X156.651 Y236.079 E2.07785 ; external perimeter
G1 X155.267 Y236.872 E2.08418 ; external perimeter
G1 X153.836 Y237.604 E2.09056 ; external perimeter
G1 X152.480 Y238.213 E2.09646 ; external perimeter
G1 X151.313 Y238.671 E2.10143 ; external perimeter
G1 X150.046 Y239.095 E2.10673 ; external perimeter
G1 X148.990 Y239.388 E2.11108 ; external perimeter
G1 X148.003 Y239.604 E2.11509 ; external perimeter
G1 X146.941 Y239.770 E2.11936 ; external perimeter
G1 X145.998 Y239.847 E2.12311 ; external perimeter
G1 X145.269 Y239.854 E2.12600 ; external perimeter
G1 X144.598 Y239.809 E2.12867 ; external perimeter
G1 X144.008 Y239.716 E2.13104 ; external perimeter
G1 X143.562 Y239.602 E2.13287 ; external perimeter
G1 X143.127 Y239.437 E2.13472 ; external perimeter
G1 X142.706 Y239.192 E2.13665 ; external perimeter
G1 X142.377 Y238.838 E2.13857 ; external perimeter
G1 X142.201 Y238.350 E2.14063 ; external perimeter
G1 X142.139 Y237.741 E2.14306 ; external perimeter
G1 X142.167 Y237.210 E2.14517 ; external perimeter
G1 X142.302 Y236.426 E2.14832 ; external perimeter
G1 X142.471 Y235.797 E2.15091 ; external perimeter
G1 X142.723 Y235.084 E2.15391 ; external perimeter
G1 X142.919 Y234.613 E2.15593 ; external perimeter
G1 X143.295 Y233.823 E2.15940 ; external perimeter
G1 X143.830 Y232.863 E2.16376 ; external perimeter
G1 X144.391 Y231.976 E2.16793 ; external perimeter
G1 X145.040 Y231.057 E2.17239 ; external perimeter
G1 X145.796 Y230.093 E2.17725 ; external perimeter
G1 X146.759 Y228.980 E2.18310 ; external perimeter
G1 X147.762 Y227.931 E2.18885 ; external perimeter
G1 X148.903 Y226.845 E2.19510 ; external perimeter
G1 X150.083 Y225.821 E2.20130 ; external perimeter
G1 X151.341 Y224.825 E2.20767 ; external perimeter
G1 X152.678 Y223.860 E2.21422 ; external perimeter
G1 X154.063 Y222.954 E2.22078 ; external perimeter
G1 X155.459 Y222.132 E2.22721 ; external perimeter
G1 X155.908 Y221.892 E2.22923 ; external perimeter
G1 X157.074 Y217.816 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X167.031 Y231.521 E2.29645 ; external perimeter
G1 X166.308 Y232.329 E2.30075 ; external perimeter
G1 X165.235 Y233.422 E2.30683 ; external perimeter
G1 X163.907 Y234.654 E2.31402 ; external perimeter
G1 X162.637 Y235.728 E2.32062 ; external perimeter
G1 X161.287 Y236.772 E2.32739 ; external perimeter
G1 X160.091 Y237.619 E2.33321 ; external perimeter
G1 X159.549 Y237.980 E2.33579 ; external perimeter
G1 X158.462 Y238.676 E2.34091 ; external perimeter
G1 X157.008 Y239.522 E2.34759 ; external perimeter
G1 X155.542 Y240.288 E2.35415 ; external perimeter
G1 X154.342 Y240.848 E2.35941 ; external perimeter
G1 X153.739 Y241.107 E2.36201 ; external perimeter
G1 X152.474 Y241.610 E2.36742 ; external perimeter
G1 X151.191 Y242.050 E2.37280 ; external perimeter
G1 X149.793 Y242.444 E2.37856 ; external perimeter
G1 X148.439 Y242.738 E2.38406 ; external perimeter
G1 X148.111 Y242.790 E2.38537 ; external perimeter
G1 X147.151 Y242.926 E2.38922 ; external perimeter
G1 X145.928 Y243.012 E2.39409 ; external perimeter
G1 X144.663 Y242.986 E2.39911 ; external perimeter
G1 X143.727 Y242.876 E2.40285 ; external perimeter
G1 X142.768 Y242.661 E2.40675 ; external perimeter
G1 X141.907 Y242.350 E2.41038 ; external perimeter
G1 X141.134 Y241.936 E2.41386 ; external perimeter
G1 X140.505 Y241.456 E2.41700 ; external perimeter
G1 X140.011 Y240.932 E2.41986 ; external perimeter
G1 X139.653 Y240.407 E2.42238 ; external perimeter
G1 X139.519 Y240.157 E2.42351 ; external perimeter
G1 X139.340 Y239.752 E2.42526 ; external perimeter
G1 X139.245 Y239.488 E2.42637 ; external perimeter
G1 X139.077 Y238.811 E2.42914 ; external perimeter
G1 X138.984 Y237.916 E2.43271 ; external perimeter
G1 X139.013 Y237.003 E2.43634 ; external perimeter
G1 X139.121 Y236.224 E2.43946 ; external perimeter
G1 X139.195 Y235.843 E2.44100 ; external perimeter
G1 X139.432 Y234.931 E2.44474 ; external perimeter
G1 X139.777 Y233.944 E2.44889 ; external perimeter
G1 X140.344 Y232.659 E2.45446 ; external perimeter
G1 X141.017 Y231.410 E2.46009 ; external perimeter
G1 X141.727 Y230.276 E2.46540 ; external perimeter
G1 X142.491 Y229.192 E2.47066 ; external perimeter
G1 X143.544 Y227.858 E2.47741 ; external perimeter
G1 X144.665 Y226.590 E2.48412 ; external perimeter
G1 X145.734 Y225.493 E2.49020 ; external perimeter
G1 X146.678 Y224.603 E2.49535 ; external perimeter
G1 X148.235 Y223.249 E2.50354 ; external perimeter
G1 X149.662 Y222.134 E2.51072 ; external perimeter
G1 X151.189 Y221.054 E2.51815 ; external perimeter
G1 X152.390 Y220.274 E2.52383 ; external perimeter
G1 X153.701 Y219.496 E2.52988 ; external perimeter
G1 X155.437 Y218.574 E2.53768 ; external perimeter
G1 X156.908 Y217.887 E2.54412 ; external perimeter
G1 X156.110 Y221.029 F1800.000 ; move to first infill point
G1 F600.000
G1 X154.765 Y219.684 E2.55650 ; infill
G1 X153.847 Y220.172 E2.56327 ; infill
G1 X152.796 Y220.796 E2.57122 ; infill
G1 X154.145 Y222.144 E2.58363 ; infill
G1 X153.865 Y222.309 E2.58574 ; infill
G1 X152.278 Y223.357 E2.59812 ; infill
G1 X150.939 Y222.019 E2.61044 ; infill
G1 X149.956 Y222.714 E2.61827 ; infill
G1 X149.169 Y223.329 E2.62477 ; infill
G1 X150.510 Y224.669 E2.63711 ; infill
G1 X149.731 Y225.287 E2.64358 ; infill
G1 X148.829 Y226.069 E2.65135 ; infill
G1 X147.494 Y224.734 E2.66364 ; infill
G1 X147.075 Y225.098 E2.66725 ; infill
G1 X146.173 Y225.948 E2.67531 ; infill
G1 X145.904 Y226.224 E2.67782 ; infill
G1 X147.241 Y227.561 E2.69012 ; infill
G1 X146.267 Y228.579 E2.69930 ; infill
G1 X145.762 Y229.163 E2.70431 ; infill
G1 X144.422 Y227.822 E2.71665 ; infill
G1 X144.075 Y228.214 E2.72005 ; infill
G1 X143.069 Y229.488 E2.73062 ; infill
G1 X143.044 Y229.525 E2.73091 ; infill
G1 X144.387 Y230.868 E2.74327 ; infill
G1 X143.771 Y231.738 E2.75020 ; infill
G1 X143.155 Y232.716 E2.75773 ; infill
G1 X141.810 Y231.372 E2.77010 ; infill
G1 X141.684 Y231.574 E2.77166 ; infill
G1 X141.058 Y232.736 E2.78024 ; infill
G1 X140.763 Y233.404 E2.78500 ; infill
G1 X142.113 Y234.755 E2.79743 ; infill
G1 X141.961 Y235.120 E2.80000 ; infill
G1 X141.679 Y235.919 E2.80552 ; infill
G1 X141.479 Y236.661 E2.81052 ; infill
G1 X141.400 Y237.122 E2.81356 ; infill
G1 X139.995 Y235.717 E2.82648 ; infill
G1 X139.957 Y235.918 E2.82781 ; infill
G1 X139.865 Y236.580 E2.83216 ; infill
G1 X139.847 Y237.456 E2.83787 ; infill
G1 X139.911 Y238.031 E2.84163 ; infill
G1 X140.034 Y238.521 E2.84492 ; infill
G1 X140.243 Y239.032 E2.84851 ; infill
G1 X142.584 Y241.387 E2.87012 ; infill
G1 X142.421 Y241.299 E2.87133 ; infill
G1 X141.970 Y240.955 E2.87502 ; infill
G1 X141.629 Y240.593 E2.87826 ; infill
G1 X141.325 Y240.127 E2.88188 ; infill
G1 X144.984 Y240.706 F1800.000 ; move to first infill point
G1 F600.000
G1 X146.435 Y242.157 E2.89523 ; infill
G1 X147.536 Y242.079 E2.90242 ; infill
G1 X148.725 Y241.905 E2.91024 ; infill
G1 X149.168 Y241.809 E2.91319 ; infill
G1 X147.781 Y240.423 E2.92595 ; infill
G1 X148.790 Y240.201 E2.93267 ; infill
G1 X149.918 Y239.889 E2.94029 ; infill
G1 X150.225 Y239.786 E2.94240 ; infill
G1 X151.599 Y241.160 E2.95504 ; infill
G1 X152.526 Y240.843 E2.96142 ; infill
G1 X153.837 Y240.318 E2.97061 ; infill
G1 X152.479 Y238.960 E2.98311 ; infill
G1 X153.902 Y238.321 E2.99326 ; infill
G1 X154.576 Y237.977 E2.99819 ; infill
G1 X155.931 Y239.332 E3.01065 ; infill
G1 X156.871 Y238.840 E3.01756 ; infill
G1 X157.914 Y238.234 E3.02541 ; infill
G1 X156.566 Y236.887 E3.03781 ; infill
G1 X156.836 Y236.732 E3.03983 ; infill
G1 X158.452 Y235.692 E3.05234 ; infill
G1 X159.797 Y237.037 E3.06471 ; infill
G1 X160.994 Y236.191 E3.07425 ; infill
G1 X161.579 Y235.738 E3.07906 ; infill
G1 X160.237 Y234.397 E3.09141 ; infill
G1 X161.049 Y233.767 E3.09810 ; infill
G1 X161.935 Y233.014 E3.10566 ; infill
G1 X163.276 Y234.355 E3.11800 ; infill
G1 X163.521 Y234.149 E3.12009 ; infill
G1 X164.880 Y232.880 E3.13219 ; infill
G1 X163.553 Y231.552 E3.14441 ; infill
G1 X164.251 Y230.913 E3.15057 ; infill
G1 X159.621 Y224.540 E3.20183 ; infill
G1 X162.431 Y227.350 E3.22769 ; infill
M106 S206.55 ; enable fan
G1 Z9.350 F1800.000 ; move to next layer (4)
G1 X156.168 Y221.362 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X163.389 Y231.300 E3.27644 ; external perimeter
G1 X162.153 Y232.446 E3.28312 ; external perimeter
G1 X160.923 Y233.492 E3.28954 ; external perimeter
G1 X159.626 Y234.498 E3.29605 ; external perimeter
G1 X158.040 Y235.604 E3.30372 ; external perimeter
G1 X156.794 Y236.394 E3.30958 ; external perimeter
G1 X155.245 Y237.274 E3.31664 ; external perimeter
G1 X153.702 Y238.044 E3.32349 ; external perimeter
G1 X152.690 Y238.498 E3.32789 ; external perimeter
G1 X151.705 Y238.889 E3.33209 ; external perimeter
G1 X150.224 Y239.401 E3.33831 ; external perimeter
G1 X149.069 Y239.723 E3.34307 ; external perimeter
G1 X147.859 Y239.980 E3.34798 ; external perimeter
G1 X146.978 Y240.112 E3.35151 ; external perimeter
G1 X146.200 Y240.181 E3.35461 ; external perimeter
G1 X145.254 Y240.198 E3.35837 ; external perimeter
G1 X144.639 Y240.159 E3.36081 ; external perimeter
G1 X144.105 Y240.084 E3.36295 ; external perimeter
G1 X143.327 Y239.886 E3.36614 ; external perimeter
G1 X142.940 Y239.729 E3.36779 ; external perimeter
G1 X142.507 Y239.469 E3.36980 ; external perimeter
G1 X142.195 Y239.168 E3.37152 ; external perimeter
G1 X141.973 Y238.779 E3.37330 ; external perimeter
G1 X141.838 Y238.271 E3.37538 ; external perimeter
G1 X141.796 Y237.759 E3.37742 ; external perimeter
G1 X141.829 Y237.126 E3.37993 ; external perimeter
G1 X141.991 Y236.253 E3.38346 ; external perimeter
G1 X142.143 Y235.694 E3.38576 ; external perimeter
G1 X142.408 Y234.944 E3.38891 ; external perimeter
G1 X142.626 Y234.426 E3.39114 ; external perimeter
G1 X142.988 Y233.667 E3.39448 ; external perimeter
G1 X143.407 Y232.903 E3.39794 ; external perimeter
G1 X144.130 Y231.748 E3.40335 ; external perimeter
G1 X144.947 Y230.614 E3.40889 ; external perimeter
G1 X145.625 Y229.758 E3.41323 ; external perimeter
G1 X146.288 Y228.994 E3.41724 ; external perimeter
G1 X147.418 Y227.790 E3.42379 ; external perimeter
G1 X148.606 Y226.650 E3.43033 ; external perimeter
G1 X149.743 Y225.657 E3.43632 ; external perimeter
G1 X151.128 Y224.554 E3.44334 ; external perimeter
G1 X152.483 Y223.576 E3.44997 ; external perimeter
G1 X153.882 Y222.662 E3.45660 ; external perimeter
G1 X155.311 Y221.821 E3.46318 ; external perimeter
G1 X156.010 Y221.447 E3.46633 ; external perimeter
G1 X157.074 Y217.816 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X167.031 Y231.521 E3.53355 ; external perimeter
G1 X166.308 Y232.329 E3.53785 ; external perimeter
G1 X165.262 Y233.395 E3.54378 ; external perimeter
G1 X163.928 Y234.635 E3.55101 ; external perimeter
G1 X162.637 Y235.727 E3.55771 ; external perimeter
G1 X161.287 Y236.772 E3.56449 ; external perimeter
G1 X159.891 Y237.757 E3.57127 ; external perimeter
G1 X158.604 Y238.588 E3.57735 ; external perimeter
G1 X157.005 Y239.523 E3.58470 ; external perimeter
G1 X156.570 Y239.755 E3.58666 ; external perimeter
G1 X155.543 Y240.287 E3.59124 ; external perimeter
G1 X154.075 Y240.968 E3.59767 ; external perimeter
G1 X152.839 Y241.473 E3.60296 ; external perimeter
G1 X151.026 Y242.100 E3.61058 ; external perimeter
G1 X149.794 Y242.444 E3.61565 ; external perimeter
G1 X148.439 Y242.738 E3.62115 ; external perimeter
G1 X147.988 Y242.809 E3.62297 ; external perimeter
G1 X146.986 Y242.943 E3.62698 ; external perimeter
G1 X145.927 Y243.012 E3.63119 ; external perimeter
G1 X144.778 Y242.994 E3.63575 ; external perimeter
G1 X143.544 Y242.843 E3.64068 ; external perimeter
G1 X142.658 Y242.627 E3.64430 ; external perimeter
G1 X141.910 Y242.351 E3.64747 ; external perimeter
G1 X141.082 Y241.901 E3.65120 ; external perimeter
G1 X140.494 Y241.446 E3.65416 ; external perimeter
G1 X140.010 Y240.931 E3.65696 ; external perimeter
G1 X139.678 Y240.450 E3.65928 ; external perimeter
G1 X139.490 Y240.097 E3.66087 ; external perimeter
G1 X139.285 Y239.613 E3.66295 ; external perimeter
G1 X139.077 Y238.812 E3.66624 ; external perimeter
G1 X138.994 Y238.102 E3.66907 ; external perimeter
G1 X138.984 Y237.900 E3.66988 ; external perimeter
G1 X139.013 Y237.002 E3.67344 ; external perimeter
G1 X139.106 Y236.312 E3.67620 ; external perimeter
G1 X139.208 Y235.783 E3.67834 ; external perimeter
G1 X139.432 Y234.931 E3.68184 ; external perimeter
G1 X139.759 Y233.990 E3.68579 ; external perimeter
G1 X140.344 Y232.659 E3.69156 ; external perimeter
G1 X141.031 Y231.386 E3.69730 ; external perimeter
G1 X141.727 Y230.276 E3.70250 ; external perimeter
G1 X142.458 Y229.237 E3.70754 ; external perimeter
G1 X143.545 Y227.857 E3.71451 ; external perimeter
G1 X144.691 Y226.562 E3.72137 ; external perimeter
G1 X145.734 Y225.492 E3.72730 ; external perimeter
G1 X146.584 Y224.689 E3.73194 ; external perimeter
G1 X147.250 Y224.088 E3.73550 ; external perimeter
G1 X148.232 Y223.251 E3.74062 ; external perimeter
G1 X149.693 Y222.111 E3.74798 ; external perimeter
G1 X151.269 Y221.000 E3.75563 ; external perimeter
G1 X152.421 Y220.254 E3.76107 ; external perimeter
G1 X153.651 Y219.525 E3.76675 ; external perimeter
G1 X155.484 Y218.550 E3.77498 ; external perimeter
G1 X156.908 Y217.887 E3.78122 ; external perimeter
G1 X157.620 Y219.660 F1800.000 ; move to first infill point
G1 F600.000
G1 X156.522 Y220.757 E3.79132 ; infill
G1 X157.819 Y222.541 E3.80567 ; infill
G1 X158.916 Y221.444 E3.81576 ; infill
G1 X160.212 Y223.228 E3.83012 ; infill
G1 X159.115 Y224.325 E3.84021 ; infill
G1 X160.411 Y226.109 E3.85457 ; infill
G1 X161.508 Y225.012 E3.86466 ; infill
G1 X162.804 Y226.796 E3.87901 ; infill
G1 X161.707 Y227.893 E3.88911 ; infill
G1 X163.003 Y229.677 E3.90346 ; infill
G1 X164.101 Y228.580 E3.91356 ; infill
G1 X165.397 Y230.364 E3.92791 ; infill
G1 X164.300 Y231.461 E3.93801 ; infill
G1 X158.715 Y237.046 F1800.000 ; move to first infill point
G1 F600.000
G1 X159.980 Y235.781 E3.94965 ; infill
G1 X159.342 Y236.226 E3.95471 ; infill
G1 X158.042 Y237.050 E3.96473 ; infill
G1 X156.431 Y237.965 E3.97678 ; infill
G1 X154.830 Y238.765 E3.98843 ; infill
G1 X153.764 Y239.243 E3.99603 ; infill
G1 X153.224 Y239.457 E3.99981 ; infill
G1 X152.082 Y240.599 E4.01032 ; infill
G1 X151.816 Y240.708 E4.01219 ; infill
G1 X150.428 Y241.188 E4.02175 ; infill
G1 X150.405 Y241.156 E4.02200 ; infill
G1 X151.654 Y240.724 E4.03060 ; infill
G1 X152.156 Y240.525 E4.03412 ; infill
G1 E2.03412 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X151.364 Y222.835 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X152.588 Y221.611 E2.01127 ; infill
G1 X153.686 Y220.900 E2.01978 ; infill
G1 X154.865 Y220.201 E2.02870 ; infill
G1 X156.634 Y219.260 E2.04174 ; infill
G1 X157.044 Y219.071 E2.04468 ; infill
G1 X155.165 Y220.077 E2.05855 ; infill
G1 X153.684 Y220.949 E2.06973 ; infill
G1 X152.431 Y221.768 E2.07947 ; infill
G1 X142.928 Y231.290 F1800.000 ; move to first infill point
G1 F1200.000
G1 X141.860 Y232.358 E2.09018 ; infill
G1 X141.697 Y232.619 E2.09236 ; infill
G1 X141.058 Y233.802 E2.10191 ; infill
G1 X140.518 Y235.032 E2.11143 ; infill
G1 X140.227 Y235.869 E2.11772 ; infill
G1 X140.028 Y236.625 E2.12327 ; infill
G1 X139.968 Y236.936 E2.12552 ; infill
G1 X141.097 Y235.807 E2.13684 ; infill
G1 X140.982 Y236.429 E2.14133 ; infill
G1 X140.939 Y237.246 E2.14713 ; infill
G1 X140.999 Y237.975 E2.15232 ; infill
G1 X141.129 Y238.462 E2.15589 ; infill
G1 X140.025 Y239.565 E2.16696 ; infill
G1 X140.217 Y240.046 E2.17064 ; infill
G1 X140.332 Y240.261 E2.17236 ; infill
G1 X140.559 Y240.591 E2.17520 ; infill
G1 X140.896 Y240.950 E2.17870 ; infill
G1 X141.139 Y241.138 E2.18088 ; infill
G1 X142.217 Y240.060 E2.19169 ; infill
G1 X142.854 Y240.441 E2.19695 ; infill
G1 X143.427 Y240.673 E2.20135 ; infill
G1 X144.115 Y240.848 E2.20638 ; infill
G1 X143.014 Y241.949 E2.21742 ; infill
G1 X143.259 Y242.009 E2.21922 ; infill
G1 X144.340 Y242.142 E2.22694 ; infill
G1 X145.501 Y242.148 E2.23518 ; infill
G1 X146.612 Y241.037 E2.24632 ; infill
G1 X147.676 Y240.957 E2.25389 ; infill
G1 X148.640 Y240.812 E2.26081 ; infill
G1 X149.687 Y240.590 E2.26840 ; infill
G1 X149.711 Y240.624 E2.26870 ; infill
G1 X148.643 Y241.692 E2.27941 ; infill
M106 S214.2 ; enable fan
G1 Z10.550 F1800.000 ; move to next layer (5)
G1 E0.27941 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X156.270 Y220.916 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X163.844 Y231.341 E2.05113 ; external perimeter
G1 X162.382 Y232.702 E2.05906 ; external perimeter
G1 X161.136 Y233.762 E2.06555 ; external perimeter
G1 X159.662 Y234.897 E2.07293 ; external perimeter
G1 X158.122 Y235.962 E2.08036 ; external perimeter
G1 X156.937 Y236.709 E2.08592 ; external perimeter
G1 X155.321 Y237.623 E2.09329 ; external perimeter
G1 X153.718 Y238.416 E2.10039 ; external perimeter
G1 X152.824 Y238.815 E2.10427 ; external perimeter
G1 X151.953 Y239.163 E2.10799 ; external perimeter
G1 X150.532 Y239.665 E2.11397 ; external perimeter
G1 X149.150 Y240.057 E2.11967 ; external perimeter
G1 X147.857 Y240.330 E2.12492 ; external perimeter
G1 X147.014 Y240.454 E2.12830 ; external perimeter
G1 X146.271 Y240.522 E2.13126 ; external perimeter
G1 X145.234 Y240.542 E2.13537 ; external perimeter
G1 X144.521 Y240.493 E2.13821 ; external perimeter
G1 X143.837 Y240.383 E2.14096 ; external perimeter
G1 X143.398 Y240.271 E2.14276 ; external perimeter
G1 X143.020 Y240.137 E2.14435 ; external perimeter
G1 X142.711 Y239.997 E2.14570 ; external perimeter
G1 X142.290 Y239.736 E2.14766 ; external perimeter
G1 X141.925 Y239.380 E2.14969 ; external perimeter
G1 X141.671 Y238.946 E2.15168 ; external perimeter
G1 X141.520 Y238.441 E2.15377 ; external perimeter
G1 X141.470 Y238.096 E2.15515 ; external perimeter
G1 X141.451 Y237.699 E2.15673 ; external perimeter
G1 X141.488 Y237.083 E2.15918 ; external perimeter
G1 X141.601 Y236.401 E2.16192 ; external perimeter
G1 X141.758 Y235.784 E2.16445 ; external perimeter
G1 X142.092 Y234.808 E2.16855 ; external perimeter
G1 X142.333 Y234.239 E2.17100 ; external perimeter
G1 X142.683 Y233.509 E2.17421 ; external perimeter
G1 X143.183 Y232.602 E2.17832 ; external perimeter
G1 X143.614 Y231.909 E2.18156 ; external perimeter
G1 X144.460 Y230.685 E2.18746 ; external perimeter
G1 X145.376 Y229.520 E2.19334 ; external perimeter
G1 X146.253 Y228.514 E2.19864 ; external perimeter
G1 X146.594 Y228.152 E2.20061 ; external perimeter
G1 X147.276 Y227.444 E2.20451 ; external perimeter
G1 X148.092 Y226.661 E2.20900 ; external perimeter
G1 X149.465 Y225.441 E2.21629 ; external perimeter
G1 X150.916 Y224.283 E2.22365 ; external perimeter
G1 X152.288 Y223.293 E2.23037 ; external perimeter
G1 X153.701 Y222.370 E2.23707 ; external perimeter
G1 X155.163 Y221.510 E2.24380 ; external perimeter
G1 X156.112 Y221.001 E2.24807 ; external perimeter
G1 X157.074 Y217.817 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X167.031 Y231.521 E2.31529 ; external perimeter
G1 X166.308 Y232.329 E2.31959 ; external perimeter
G1 X165.290 Y233.368 E2.32536 ; external perimeter
G1 X163.891 Y234.668 E2.33294 ; external perimeter
G1 X162.637 Y235.728 E2.33946 ; external perimeter
G1 X161.286 Y236.772 E2.34623 ; external perimeter
G1 X160.237 Y237.519 E2.35134 ; external perimeter
G1 X159.298 Y238.143 E2.35581 ; external perimeter
G1 X158.463 Y238.675 E2.35975 ; external perimeter
G1 X156.962 Y239.547 E2.36663 ; external perimeter
G1 X155.541 Y240.288 E2.37299 ; external perimeter
G1 X154.537 Y240.760 E2.37739 ; external perimeter
G1 X153.491 Y241.210 E2.38191 ; external perimeter
G1 X152.368 Y241.649 E2.38670 ; external perimeter
G1 X151.191 Y242.049 E2.39163 ; external perimeter
G1 X149.793 Y242.444 E2.39740 ; external perimeter
G1 X148.439 Y242.738 E2.40289 ; external perimeter
G1 X147.864 Y242.829 E2.40520 ; external perimeter
G1 X146.944 Y242.947 E2.40889 ; external perimeter
G1 X145.928 Y243.012 E2.41292 ; external perimeter
G1 X144.778 Y242.994 E2.41749 ; external perimeter
G1 X144.181 Y242.934 E2.41987 ; external perimeter
G1 X143.497 Y242.834 E2.42261 ; external perimeter
G1 X142.629 Y242.619 E2.42616 ; external perimeter
G1 X141.910 Y242.352 E2.42920 ; external perimeter
G1 X141.547 Y242.171 E2.43082 ; external perimeter
G1 X141.060 Y241.887 E2.43305 ; external perimeter
G1 X140.483 Y241.436 E2.43596 ; external perimeter
G1 X140.009 Y240.930 E2.43871 ; external perimeter
G1 X139.704 Y240.493 E2.44082 ; external perimeter
G1 X139.460 Y240.036 E2.44288 ; external perimeter
G1 X139.288 Y239.623 E2.44466 ; external perimeter
G1 X139.219 Y239.405 E2.44556 ; external perimeter
G1 X139.077 Y238.812 E2.44798 ; external perimeter
G1 X138.997 Y238.150 E2.45063 ; external perimeter
G1 X138.983 Y237.883 E2.45169 ; external perimeter
G1 X139.013 Y237.001 E2.45519 ; external perimeter
G1 X139.091 Y236.400 E2.45760 ; external perimeter
G1 X139.221 Y235.724 E2.46033 ; external perimeter
G1 X139.432 Y234.931 E2.46358 ; external perimeter
G1 X139.745 Y234.026 E2.46738 ; external perimeter
G1 X139.892 Y233.655 E2.46897 ; external perimeter
G1 X140.342 Y232.662 E2.47329 ; external perimeter
G1 X141.045 Y231.362 E2.47916 ; external perimeter
G1 X141.727 Y230.275 E2.48425 ; external perimeter
G1 X142.424 Y229.282 E2.48907 ; external perimeter
G1 X143.545 Y227.856 E2.49626 ; external perimeter
G1 X144.716 Y226.535 E2.50327 ; external perimeter
G1 X145.734 Y225.492 E2.50905 ; external perimeter
G1 X146.489 Y224.777 E2.51318 ; external perimeter
G1 X146.948 Y224.353 E2.51566 ; external perimeter
G1 X148.233 Y223.251 E2.52237 ; external perimeter
G1 X149.724 Y222.088 E2.52988 ; external perimeter
G1 X151.349 Y220.947 E2.53776 ; external perimeter
G1 X152.430 Y220.249 E2.54286 ; external perimeter
G1 X153.601 Y219.554 E2.54827 ; external perimeter
G1 X155.531 Y218.527 E2.55694 ; external perimeter
G1 X156.908 Y217.887 E2.56297 ; external perimeter
G1 X156.730 Y219.559 F1800.000 ; move to first infill point
G1 F1200.000
G1 X156.638 Y219.470 E2.56362 ; infill
G1 X156.363 Y219.546 E2.56506 ; infill
G1 F1200.000
G1 X156.087 Y219.622 E2.56641 ; infill
G1 F1200.000
G1 X154.548 Y220.444 E2.57401 ; infill
G1 X153.035 Y221.329 E2.58164 ; infill
G1 X151.606 Y222.270 E2.58909 ; infill
G1 X150.461 Y223.084 E2.59520 ; infill
G1 X149.018 Y224.211 E2.60317 ; infill
G1 X147.774 Y225.281 E2.61031 ; infill
G1 X147.264 Y225.744 E2.61331 ; infill
G1 X146.414 Y226.561 E2.61844 ; infill
G1 X145.696 Y227.302 E2.62293 ; infill
G1 X144.495 Y228.649 E2.63079 ; infill
G1 X143.417 Y230.019 E2.63838 ; infill
G1 X142.761 Y230.962 E2.64337 ; infill
G1 X142.127 Y231.962 E2.64853 ; infill
G1 X141.452 Y233.213 E2.65472 ; infill
G1 X141.203 Y233.748 E2.65728 ; infill
G1 X140.905 Y234.457 E2.66063 ; infill
G1 X140.617 Y235.293 E2.66448 ; infill
G1 X140.427 Y236.000 E2.66767 ; infill
G1 X140.314 Y236.597 E2.67031 ; infill
G1 X140.247 Y237.102 E2.67253 ; infill
G1 X140.220 Y237.730 E2.67527 ; infill
G1 X140.248 Y238.248 E2.67752 ; infill
G1 X140.330 Y238.757 E2.67977 ; infill
G1 X140.510 Y239.357 E2.68249 ; infill
G1 X140.574 Y239.509 E2.68321 ; infill
G1 X140.762 Y239.845 E2.68489 ; infill
G1 X140.966 Y240.155 E2.68650 ; infill
G1 X141.320 Y240.520 E2.68872 ; infill
G1 X141.596 Y240.749 E2.69028 ; infill
G1 X142.132 Y241.086 E2.69303 ; infill
G1 X142.402 Y241.215 E2.69434 ; infill
G1 X142.993 Y241.437 E2.69709 ; infill
G1 X143.619 Y241.596 E2.69989 ; infill
G1 X144.333 Y241.711 E2.70304 ; infill
G1 X144.850 Y241.757 E2.70530 ; infill
G1 X145.898 Y241.770 E2.70986 ; infill
G1 X146.314 Y241.753 E2.71168 ; infill
G1 X146.825 Y241.714 E2.71391 ; infill
G1 X147.688 Y241.605 E2.71770 ; infill
G1 X148.211 Y241.520 E2.72000 ; infill
G1 X149.471 Y241.250 E2.72561 ; infill
G1 X150.929 Y240.834 E2.73221 ; infill
G1 X151.942 Y240.483 E2.73688 ; infill
G1 X153.022 Y240.066 E2.74191 ; infill
G1 X154.030 Y239.631 E2.74669 ; infill
G1 X154.989 Y239.174 E2.75132 ; infill
G1 X156.363 Y238.459 E2.75806 ; infill
G1 X157.585 Y237.759 E2.76419 ; infill
G1 X158.624 Y237.107 E2.76953 ; infill
G1 X160.405 Y235.884 E2.77893 ; infill
G1 X161.900 Y234.733 E2.78714 ; infill
G1 X163.214 Y233.613 E2.79466 ; infill
G1 X164.429 Y232.483 E2.80188 ; infill
G1 X165.007 Y231.920 E2.80540 ; infill
G1 X165.073 Y231.823 E2.80590 ; infill
G1 F1200.000
G1 X165.204 Y231.629 E2.80698 ; infill
G1 F1200.000
G1 X165.335 Y231.435 E2.80812 ; infill
G1 X166.349 Y231.510 E2.81309 ; infill
G1 X165.335 Y231.435 F1800.000 ; move to first infill point
G1 F1200.000
G1 X165.224 Y231.210 E2.81436 ; infill
G1 F1200.000
G1 X165.113 Y230.985 E2.81555 ; infill
G1 F1200.000
G1 X157.006 Y219.826 E2.87645 ; infill
G1 X156.914 Y219.737 E2.87701 ; infill
G1 F1200.000
G1 X156.730 Y219.559 E2.87823 ; infill
G1 Z11.750 F1800.000 ; move to next layer (6)
G1 X156.372 Y220.471 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X164.295 Y231.376 E2.93172 ; external perimeter
G1 X162.665 Y232.911 E2.94060 ; external perimeter
G1 X161.351 Y234.031 E2.94745 ; external perimeter
G1 X160.036 Y235.050 E2.95405 ; external perimeter
G1 X158.655 Y236.024 E2.96076 ; external perimeter
G1 X157.082 Y237.024 E2.96815 ; external perimeter
G1 X155.401 Y237.970 E2.97581 ; external perimeter
G1 X154.285 Y238.533 E2.98077 ; external perimeter
G1 X153.726 Y238.791 E2.98321 ; external perimeter
G1 X152.958 Y239.132 E2.98655 ; external perimeter
G1 X152.207 Y239.433 E2.98976 ; external perimeter
G1 X151.669 Y239.640 E2.99205 ; external perimeter
G1 X150.696 Y239.973 E2.99613 ; external perimeter
G1 X149.231 Y240.392 E3.00217 ; external perimeter
G1 X147.854 Y240.680 E3.00775 ; external perimeter
G1 X147.050 Y240.797 E3.01098 ; external perimeter
G1 X146.342 Y240.862 E3.01380 ; external perimeter
G1 X145.216 Y240.886 E3.01827 ; external perimeter
G1 X144.482 Y240.835 E3.02119 ; external perimeter
G1 X143.752 Y240.717 E3.02413 ; external perimeter
G1 X143.315 Y240.605 E3.02591 ; external perimeter
G1 X142.926 Y240.471 E3.02755 ; external perimeter
G1 X142.580 Y240.317 E3.02905 ; external perimeter
G1 X142.095 Y240.018 E3.03131 ; external perimeter
G1 X141.854 Y239.809 E3.03258 ; external perimeter
G1 X141.655 Y239.587 E3.03376 ; external perimeter
G1 X141.482 Y239.329 E3.03499 ; external perimeter
G1 X141.349 Y239.059 E3.03619 ; external perimeter
G1 X141.250 Y238.780 E3.03736 ; external perimeter
G1 X141.166 Y238.421 E3.03882 ; external perimeter
G1 X141.109 Y237.820 E3.04122 ; external perimeter
G1 X141.127 Y237.244 E3.04351 ; external perimeter
G1 X141.193 Y236.724 E3.04559 ; external perimeter
G1 X141.363 Y235.926 E3.04882 ; external perimeter
G1 X141.553 Y235.284 E3.05148 ; external perimeter
G1 X141.780 Y234.662 E3.05411 ; external perimeter
G1 X142.039 Y234.052 E3.05674 ; external perimeter
G1 X142.376 Y233.353 E3.05982 ; external perimeter
G1 X142.772 Y232.626 E3.06310 ; external perimeter
G1 X143.266 Y231.814 E3.06687 ; external perimeter
G1 X143.608 Y231.291 E3.06935 ; external perimeter
G1 X144.174 Y230.493 E3.07324 ; external perimeter
G1 X145.236 Y229.152 E3.08003 ; external perimeter
G1 X146.001 Y228.280 E3.08463 ; external perimeter
G1 X146.447 Y227.807 E3.08721 ; external perimeter
G1 X147.033 Y227.200 E3.09056 ; external perimeter
G1 X148.086 Y226.194 E3.09633 ; external perimeter
G1 X149.191 Y225.222 E3.10217 ; external perimeter
G1 X150.703 Y224.012 E3.10986 ; external perimeter
G1 X152.093 Y223.009 E3.11666 ; external perimeter
G1 X153.519 Y222.077 E3.12342 ; external perimeter
G1 X155.014 Y221.198 E3.13030 ; external perimeter
G1 X156.213 Y220.556 E3.13570 ; external perimeter
G1 X157.074 Y217.817 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X167.031 Y231.521 E3.20292 ; external perimeter
G1 X166.308 Y232.330 E3.20722 ; external perimeter
G1 X165.318 Y233.341 E3.21284 ; external perimeter
G1 X163.883 Y234.675 E3.22062 ; external perimeter
G1 X162.637 Y235.728 E3.22709 ; external perimeter
G1 X161.287 Y236.772 E3.23386 ; external perimeter
G1 X159.890 Y237.758 E3.24064 ; external perimeter
G1 X158.081 Y238.905 E3.24915 ; external perimeter
G1 X156.954 Y239.551 E3.25430 ; external perimeter
G1 X155.542 Y240.287 E3.26062 ; external perimeter
G1 X154.075 Y240.968 E3.26704 ; external perimeter
G1 X152.956 Y241.428 E3.27184 ; external perimeter
G1 X151.944 Y241.797 E3.27611 ; external perimeter
G1 X150.941 Y242.126 E3.28030 ; external perimeter
G1 X149.795 Y242.444 E3.28502 ; external perimeter
G1 X148.439 Y242.738 E3.29053 ; external perimeter
G1 X147.740 Y242.848 E3.29333 ; external perimeter
G1 X146.902 Y242.951 E3.29669 ; external perimeter
G1 X145.928 Y243.012 E3.30055 ; external perimeter
G1 X144.778 Y242.994 E3.30512 ; external perimeter
G1 X144.052 Y242.921 E3.30802 ; external perimeter
G1 X143.451 Y242.826 E3.31043 ; external perimeter
G1 X142.600 Y242.610 E3.31392 ; external perimeter
G1 X141.911 Y242.352 E3.31683 ; external perimeter
G1 X141.464 Y242.130 E3.31881 ; external perimeter
G1 X141.029 Y241.867 E3.32083 ; external perimeter
G1 X140.469 Y241.425 E3.32366 ; external perimeter
G1 X140.014 Y240.938 E3.32631 ; external perimeter
G1 X139.722 Y240.526 E3.32831 ; external perimeter
G1 X139.435 Y239.986 E3.33074 ; external perimeter
G1 X139.204 Y239.358 E3.33339 ; external perimeter
G1 X139.076 Y238.812 E3.33562 ; external perimeter
G1 X139.000 Y238.197 E3.33808 ; external perimeter
G1 X138.983 Y237.866 E3.33939 ; external perimeter
G1 X139.013 Y236.999 E3.34284 ; external perimeter
G1 X139.076 Y236.487 E3.34488 ; external perimeter
G1 X139.235 Y235.664 E3.34821 ; external perimeter
G1 X139.432 Y234.931 E3.35122 ; external perimeter
G1 X139.727 Y234.073 E3.35482 ; external perimeter
G1 X139.907 Y233.620 E3.35676 ; external perimeter
G1 X140.342 Y232.663 E3.36093 ; external perimeter
G1 X141.059 Y231.339 E3.36690 ; external perimeter
G1 X141.727 Y230.275 E3.37189 ; external perimeter
G1 X142.395 Y229.321 E3.37651 ; external perimeter
G1 X142.765 Y228.829 E3.37895 ; external perimeter
G1 X143.544 Y227.857 E3.38389 ; external perimeter
G1 X144.742 Y226.507 E3.39106 ; external perimeter
G1 X145.556 Y225.668 E3.39569 ; external perimeter
G1 X146.393 Y224.866 E3.40029 ; external perimeter
G1 X146.948 Y224.353 E3.40329 ; external perimeter
G1 X148.233 Y223.251 E3.41001 ; external perimeter
G1 X149.758 Y222.063 E3.41768 ; external perimeter
G1 X150.876 Y221.264 E3.42314 ; external perimeter
G1 X152.438 Y220.244 E3.43054 ; external perimeter
G1 X154.104 Y219.271 E3.43820 ; external perimeter
G1 X155.575 Y218.505 E3.44477 ; external perimeter
G1 X156.908 Y217.888 E3.45061 ; external perimeter
G1 X156.702 Y219.220 F1800.000 ; move to first infill point
G1 F1200.000
G1 X156.879 Y219.395 E3.45146 ; infill
G1 F1200.000
G1 X156.968 Y219.482 E3.45185 ; infill
G1 X165.423 Y231.119 E3.49687 ; infill
G1 F1200.000
G1 X165.588 Y231.448 E3.49813 ; infill
G1 X165.521 Y231.593 E3.49867 ; infill
G1 F1200.000
G1 X165.342 Y231.825 E3.49959 ; infill
G1 X164.574 Y232.577 E3.50294 ; infill
G1 X163.382 Y233.692 E3.50802 ; infill
G1 X161.968 Y234.900 E3.51382 ; infill
G1 X160.659 Y235.913 E3.51898 ; infill
G1 X159.293 Y236.877 E3.52419 ; infill
G1 X157.640 Y237.928 E3.53029 ; infill
G1 X155.889 Y238.911 E3.53656 ; infill
G1 X154.755 Y239.484 E3.54051 ; infill
G1 X153.648 Y239.991 E3.54431 ; infill
G1 X152.571 Y240.434 E3.54794 ; infill
G1 X151.596 Y240.791 E3.55118 ; infill
G1 X150.631 Y241.103 E3.55434 ; infill
G1 X149.505 Y241.419 E3.55799 ; infill
G1 X148.242 Y241.689 E3.56201 ; infill
G1 X147.592 Y241.794 E3.56406 ; infill
G1 X146.804 Y241.890 E3.56654 ; infill
G1 X145.903 Y241.941 E3.56935 ; infill
G1 X144.840 Y241.929 E3.57266 ; infill
G1 X144.189 Y241.865 E3.57470 ; infill
G1 X143.512 Y241.749 E3.57684 ; infill
G1 X142.988 Y241.614 E3.57853 ; infill
G1 X142.559 Y241.464 E3.57994 ; infill
G1 X142.053 Y241.238 E3.58168 ; infill
G1 X141.432 Y240.847 E3.58396 ; infill
G1 X141.022 Y240.474 E3.58569 ; infill
G1 X140.840 Y240.268 E3.58655 ; infill
G1 X140.617 Y239.950 E3.58776 ; infill
G1 X140.383 Y239.500 E3.58934 ; infill
G1 X140.229 Y239.076 E3.59074 ; infill
G1 X140.123 Y238.625 E3.59219 ; infill
G1 X140.047 Y237.819 E3.59471 ; infill
G1 F1200.000
G1 X140.071 Y237.135 E3.59687 ; infill
G1 X140.128 Y236.653 E3.59840 ; infill
G1 X140.339 Y235.643 E3.60166 ; infill
G1 X140.541 Y234.967 E3.60388 ; infill
G1 X140.786 Y234.286 E3.60617 ; infill
G1 X141.297 Y233.138 E3.61014 ; infill
G1 X141.980 Y231.876 E3.61466 ; infill
G1 X142.737 Y230.685 E3.61912 ; infill
G1 X143.257 Y229.946 E3.62197 ; infill
G1 X143.609 Y229.484 E3.62380 ; infill
G1 X144.358 Y228.545 E3.62759 ; infill
G1 X145.211 Y227.574 E3.63167 ; infill
G1 X146.307 Y226.423 E3.63669 ; infill
G1 X147.657 Y225.150 E3.64255 ; infill
G1 X148.910 Y224.079 E3.64775 ; infill
G1 X150.396 Y222.918 E3.65370 ; infill
G1 X151.481 Y222.139 E3.65791 ; infill
G1 X152.998 Y221.149 E3.66363 ; infill
G1 X154.611 Y220.207 E3.66952 ; infill
G1 X156.043 Y219.451 E3.67463 ; infill
G1 X156.274 Y219.335 E3.67545 ; infill
G1 X156.381 Y219.306 E3.67580 ; infill
G1 F1200.000
G1 X156.528 Y219.267 E3.67632 ; infill
M106 S219.3 ; enable fan
G1 Z12.950 F1800.000 ; move to next layer (7)
G1 X156.489 Y220.047 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X155.781 Y220.398 E3.67946 ; external perimeter
G1 X154.295 Y221.214 E3.68619 ; external perimeter
G1 X153.196 Y221.874 E3.69127 ; external perimeter
G1 X152.129 Y222.569 E3.69633 ; external perimeter
G1 X150.493 Y223.740 E3.70431 ; external perimeter
G1 X149.203 Y224.762 E3.71084 ; external perimeter
G1 X147.825 Y225.966 E3.71810 ; external perimeter
G1 X146.551 Y227.199 E3.72514 ; external perimeter
G1 X145.749 Y228.045 E3.72976 ; external perimeter
G1 X145.018 Y228.877 E3.73416 ; external perimeter
G1 X144.519 Y229.482 E3.73727 ; external perimeter
G1 X143.882 Y230.309 E3.74141 ; external perimeter
G1 X143.346 Y231.065 E3.74509 ; external perimeter
G1 X142.834 Y231.851 E3.74881 ; external perimeter
G1 X142.447 Y232.501 E3.75182 ; external perimeter
G1 X142.070 Y233.195 E3.75495 ; external perimeter
G1 X141.746 Y233.865 E3.75790 ; external perimeter
G1 X141.464 Y234.525 E3.76075 ; external perimeter
G1 X141.157 Y235.388 E3.76439 ; external perimeter
G1 X140.927 Y236.259 E3.76796 ; external perimeter
G1 X140.768 Y237.148 E3.77154 ; external perimeter
G1 X139.351 Y235.225 E3.78102 ; external perimeter
G1 X139.432 Y234.933 E3.78222 ; external perimeter
G1 X139.709 Y234.119 E3.78563 ; external perimeter
G1 X139.923 Y233.581 E3.78793 ; external perimeter
G1 X140.185 Y232.990 E3.79050 ; external perimeter
G1 X140.774 Y231.838 E3.79563 ; external perimeter
G1 X141.496 Y230.630 E3.80122 ; external perimeter
G1 X142.364 Y229.363 E3.80731 ; external perimeter
G1 X142.797 Y228.786 E3.81017 ; external perimeter
G1 X143.540 Y227.862 E3.81488 ; external perimeter
G1 X144.594 Y226.666 E3.82120 ; external perimeter
G1 X145.733 Y225.493 E3.82769 ; external perimeter
G1 X146.949 Y224.352 E3.83431 ; external perimeter
G1 X148.402 Y223.113 E3.84188 ; external perimeter
G1 X149.788 Y222.040 E3.84884 ; external perimeter
G1 X150.860 Y221.275 E3.85407 ; external perimeter
G1 X152.443 Y220.241 E3.86157 ; external perimeter
G1 X154.156 Y219.243 E3.86943 ; external perimeter
G1 X155.621 Y218.482 E3.87599 ; external perimeter
G1 X157.074 Y217.817 E3.88233 ; external perimeter
G1 X167.031 Y231.521 E3.94955 ; external perimeter
G1 X166.308 Y232.330 E3.95385 ; external perimeter
G1 X165.345 Y233.314 E3.95931 ; external perimeter
G1 X163.928 Y234.635 E3.96700 ; external perimeter
G1 X162.361 Y235.948 E3.97512 ; external perimeter
G1 X161.287 Y236.772 E3.98049 ; external perimeter
G1 X160.383 Y237.419 E3.98490 ; external perimeter
G1 X159.051 Y238.303 E3.99124 ; external perimeter
G1 X158.015 Y238.944 E3.99608 ; external perimeter
G1 X156.945 Y239.556 E4.00097 ; external perimeter
G1 X155.542 Y240.287 E4.00724 ; external perimeter
G1 X154.076 Y240.967 E4.01366 ; external perimeter
G1 X152.622 Y241.556 E4.01989 ; external perimeter
G1 X151.190 Y242.050 E4.02589 ; external perimeter
G1 X149.793 Y242.444 E4.03165 ; external perimeter
G1 X148.439 Y242.738 E4.03715 ; external perimeter
G1 X147.616 Y242.868 E4.04046 ; external perimeter
G1 X146.860 Y242.955 E4.04348 ; external perimeter
G1 X145.925 Y243.012 E4.04720 ; external perimeter
G1 X145.005 Y243.009 E4.05085 ; external perimeter
G1 X143.581 Y241.037 E4.06050 ; external perimeter
G1 X144.444 Y241.177 E4.06397 ; external perimeter
G1 X145.189 Y241.229 E4.06693 ; external perimeter
G1 X145.810 Y241.231 E4.06940 ; external perimeter
G1 X146.422 Y241.202 E4.07182 ; external perimeter
G1 X147.086 Y241.139 E4.07447 ; external perimeter
G1 X147.845 Y241.030 E4.07751 ; external perimeter
G1 X148.500 Y240.909 E4.08016 ; external perimeter
G1 X149.312 Y240.726 E4.08346 ; external perimeter
G1 X150.182 Y240.491 E4.08704 ; external perimeter
G1 X150.869 Y240.279 E4.08989 ; external perimeter
G1 X151.788 Y239.963 E4.09375 ; external perimeter
G1 X153.449 Y239.294 E4.10085 ; external perimeter
G1 X154.436 Y238.842 E4.10516 ; external perimeter
G1 X155.923 Y238.082 E4.11179 ; external perimeter
G1 X157.229 Y237.337 E4.11775 ; external perimeter
G1 X158.847 Y236.310 E4.12536 ; external perimeter
G1 X160.241 Y235.327 E4.13213 ; external perimeter
G1 X161.566 Y234.299 E4.13878 ; external perimeter
G1 X163.014 Y233.060 E4.14635 ; external perimeter
G1 X163.978 Y232.157 E4.15159 ; external perimeter
G1 X164.734 Y231.396 E4.15584 ; external perimeter
G1 X156.595 Y220.193 E4.21079 ; external perimeter
G1 X156.858 Y219.077 F1800.000 ; move to first infill point
G1 F1200.000
G1 X156.762 Y218.984 E4.21109 ; infill
G1 X156.578 Y219.033 E4.21150 ; infill
G1 F1200.000
G1 X156.486 Y219.058 E4.21169 ; infill
G1 X155.378 Y219.608 E4.21409 ; infill
G1 X153.860 Y220.441 E4.21745 ; infill
G1 X152.729 Y221.115 E4.22001 ; infill
G1 X151.370 Y222.012 E4.22317 ; infill
G1 X149.966 Y223.025 E4.22653 ; infill
G1 X148.642 Y224.075 E4.22981 ; infill
G1 X147.546 Y225.020 E4.23262 ; infill
G1 X146.362 Y226.133 E4.23577 ; infill
G1 X145.250 Y227.272 E4.23887 ; infill
G1 X144.224 Y228.437 E4.24188 ; infill
G1 X143.170 Y229.773 E4.24518 ; infill
G1 X142.609 Y230.573 E4.24708 ; infill
G1 X142.077 Y231.388 E4.24897 ; infill
G1 X141.556 Y232.271 E4.25096 ; infill
G1 X141.278 Y232.798 E4.25212 ; infill
G1 X140.939 Y233.487 E4.25361 ; infill
G1 X140.639 Y234.190 E4.25509 ; infill
G1 X140.331 Y235.054 E4.25687 ; infill
G1 X140.336 Y235.087 E4.25694 ; infill
G1 F1200.000
G1 X140.467 Y235.870 E4.25830 ; infill
G1 E2.25830 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X144.999 Y242.119 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F1200.000
G1 X145.899 Y242.120 E2.00165 ; infill
G1 X146.493 Y242.087 E2.00274 ; infill
G1 X147.200 Y242.021 E2.00404 ; infill
G1 X148.274 Y241.859 E2.00604 ; infill
G1 X149.577 Y241.578 E2.00848 ; infill
G1 X150.923 Y241.197 E2.01104 ; infill
G1 X152.308 Y240.720 E2.01373 ; infill
G1 X153.721 Y240.148 E2.01653 ; infill
G1 X155.147 Y239.484 E2.01941 ; infill
G1 X156.354 Y238.861 E2.02190 ; infill
G1 X157.696 Y238.095 E2.02473 ; infill
G1 X159.333 Y237.052 E2.02829 ; infill
G1 X160.764 Y236.049 E2.03150 ; infill
G1 X162.136 Y234.984 E2.03468 ; infill
G1 X163.600 Y233.727 E2.03822 ; infill
G1 X164.721 Y232.675 E2.04104 ; infill
G1 X165.660 Y231.723 E2.04349 ; infill
G1 X165.752 Y231.585 E2.04380 ; infill
G1 F1200.000
G1 X165.830 Y231.460 E2.04412 ; infill
G1 X165.714 Y231.227 E2.04468 ; infill
G1 F1200.000
G1 X156.955 Y219.171 E2.07218 ; infill
G1 X156.858 Y219.077 E2.07242 ; infill
M106 S229.5 ; enable fan
G1 Z14.150 F1800.000 ; move to next layer (8)
G1 X156.597 Y219.610 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X155.639 Y220.084 E2.07666 ; external perimeter
G1 X154.228 Y220.853 E2.08304 ; external perimeter
G1 X153.155 Y221.493 E2.08800 ; external perimeter
G1 X151.984 Y222.252 E2.09354 ; external perimeter
G1 X151.250 Y222.760 E2.09708 ; external perimeter
G1 X150.280 Y223.470 E2.10185 ; external perimeter
G1 X149.350 Y224.199 E2.10654 ; external perimeter
G1 X148.636 Y224.790 E2.11022 ; external perimeter
G1 X147.756 Y225.562 E2.11486 ; external perimeter
G1 X146.926 Y226.341 E2.11938 ; external perimeter
G1 X146.258 Y227.006 E2.12312 ; external perimeter
G1 X145.496 Y227.812 E2.12752 ; external perimeter
G1 X144.795 Y228.607 E2.13173 ; external perimeter
G1 X144.162 Y229.378 E2.13568 ; external perimeter
G1 X143.298 Y230.536 E2.14142 ; external perimeter
G1 X142.410 Y229.313 E2.14741 ; external perimeter
G1 X142.831 Y228.742 E2.15023 ; external perimeter
G1 X143.545 Y227.856 E2.15475 ; external perimeter
G1 X144.595 Y226.664 E2.16105 ; external perimeter
G1 X145.498 Y225.727 E2.16621 ; external perimeter
G1 X146.081 Y225.156 E2.16945 ; external perimeter
G1 X146.948 Y224.353 E2.17414 ; external perimeter
G1 X148.235 Y223.249 E2.18087 ; external perimeter
G1 X149.816 Y222.019 E2.18882 ; external perimeter
G1 X150.964 Y221.204 E2.19440 ; external perimeter
G1 X152.392 Y220.272 E2.20117 ; external perimeter
G1 X153.313 Y219.720 E2.20543 ; external perimeter
G1 X154.200 Y219.218 E2.20947 ; external perimeter
G1 X155.305 Y218.639 E2.21442 ; external perimeter
G1 X156.679 Y217.987 E2.22046 ; external perimeter
G1 X157.074 Y217.817 E2.22217 ; external perimeter
G1 X167.031 Y231.521 E2.28939 ; external perimeter
G1 X166.307 Y232.330 E2.29369 ; external perimeter
G1 X165.591 Y233.065 E2.29777 ; external perimeter
G1 X164.717 Y233.916 E2.30261 ; external perimeter
G1 X163.931 Y234.633 E2.30683 ; external perimeter
G1 X162.993 Y235.436 E2.31173 ; external perimeter
G1 X162.319 Y235.981 E2.31517 ; external perimeter
G1 X161.288 Y236.771 E2.32032 ; external perimeter
G1 X159.890 Y237.758 E2.32711 ; external perimeter
G1 X158.750 Y238.497 E2.33250 ; external perimeter
G1 X157.951 Y238.982 E2.33621 ; external perimeter
G1 X156.936 Y239.561 E2.34085 ; external perimeter
G1 X155.543 Y240.287 E2.34709 ; external perimeter
G1 X154.074 Y240.969 E2.35351 ; external perimeter
G1 X153.071 Y241.384 E2.35782 ; external perimeter
G1 X152.212 Y241.706 E2.36146 ; external perimeter
G1 X151.568 Y241.922 E2.36415 ; external perimeter
G1 X150.681 Y240.699 E2.37015 ; external perimeter
G1 X151.905 Y240.287 E2.37527 ; external perimeter
G1 X152.806 Y239.939 E2.37911 ; external perimeter
G1 X153.654 Y239.581 E2.38276 ; external perimeter
G1 X154.583 Y239.153 E2.38681 ; external perimeter
G1 X155.550 Y238.669 E2.39111 ; external perimeter
G1 X156.375 Y238.227 E2.39482 ; external perimeter
G1 X157.371 Y237.653 E2.39938 ; external perimeter
G1 X158.150 Y237.174 E2.40301 ; external perimeter
G1 X159.135 Y236.531 E2.40768 ; external perimeter
G1 X160.115 Y235.844 E2.41243 ; external perimeter
G1 X161.782 Y234.568 E2.42076 ; external perimeter
G1 X163.069 Y233.473 E2.42746 ; external perimeter
G1 X164.208 Y232.413 E2.43364 ; external perimeter
G1 X165.185 Y231.430 E2.43914 ; external perimeter
G1 X156.703 Y219.756 E2.49640 ; external perimeter
G1 E0.49640 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X143.174 Y229.487 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F1200.000
G1 X143.598 Y228.935 E2.00040 ; infill
G1 X144.251 Y228.140 E2.00099 ; infill
G1 X145.126 Y227.153 E2.00174 ; infill
G1 X146.010 Y226.235 E2.00247 ; infill
G1 X146.578 Y225.679 E2.00293 ; infill
G1 X147.428 Y224.891 E2.00359 ; infill
G1 X148.694 Y223.805 E2.00455 ; infill
G1 X149.603 Y223.084 E2.00521 ; infill
G1 X150.243 Y222.602 E2.00567 ; infill
G1 X151.370 Y221.800 E2.00647 ; infill
G1 X152.778 Y220.880 E2.00743 ; infill
G1 X153.875 Y220.227 E2.00816 ; infill
G1 X155.305 Y219.449 E2.00909 ; infill
G1 X156.672 Y218.778 E2.00997 ; infill
G1 X156.826 Y218.738 E2.01006 ; infill
G1 X156.923 Y218.834 E2.01014 ; infill
G1 X166.026 Y231.363 E2.01901 ; infill
G1 X166.083 Y231.473 E2.01908 ; infill
G1 X165.996 Y231.617 E2.01918 ; infill
G1 X164.708 Y232.925 E2.02023 ; infill
G1 X163.544 Y234.013 E2.02114 ; infill
G1 X162.530 Y234.880 E2.02191 ; infill
G1 X161.873 Y235.415 E2.02239 ; infill
G1 X160.860 Y236.189 E2.02312 ; infill
G1 X159.535 Y237.128 E2.02405 ; infill
G1 X158.532 Y237.782 E2.02474 ; infill
G1 X157.586 Y238.361 E2.02537 ; infill
G1 X156.591 Y238.929 E2.02603 ; infill
G1 X155.224 Y239.640 E2.02691 ; infill
G1 X153.941 Y240.239 E2.02772 ; infill
G1 X153.078 Y240.603 E2.02826 ; infill
G1 X152.153 Y240.961 E2.02883 ; infill
G1 X151.637 Y241.138 E2.02914 ; infill
M106 S244.8 ; enable fan
G1 Z15.350 F1800.000 ; move to next layer (9)
G1 E0.02914 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X156.704 Y219.173 F1800.000 ; move to first external perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X155.496 Y219.770 E2.00535 ; external perimeter
G1 X153.988 Y220.594 E2.01217 ; external perimeter
G1 X152.974 Y221.201 E2.01686 ; external perimeter
G1 X151.834 Y221.938 E2.02224 ; external perimeter
G1 X150.982 Y222.528 E2.02636 ; external perimeter
G1 X150.066 Y223.200 E2.03087 ; external perimeter
G1 X148.765 Y224.232 E2.03745 ; external perimeter
G1 X148.343 Y224.596 E2.03967 ; external perimeter
G1 X147.699 Y223.710 E2.04402 ; external perimeter
G1 X148.450 Y223.074 E2.04792 ; external perimeter
G1 X149.850 Y221.994 E2.05494 ; external perimeter
G1 X150.964 Y221.204 E2.06036 ; external perimeter
G1 X152.390 Y220.274 E2.06712 ; external perimeter
G1 X153.841 Y219.416 E2.07380 ; external perimeter
G1 X155.209 Y218.687 E2.07996 ; external perimeter
G1 X156.667 Y217.992 E2.08636 ; external perimeter
G1 X157.074 Y217.817 E2.08812 ; external perimeter
G1 X167.031 Y231.521 E2.15534 ; external perimeter
G1 X166.308 Y232.330 E2.15965 ; external perimeter
G1 X165.397 Y233.263 E2.16482 ; external perimeter
G1 X164.662 Y233.968 E2.16886 ; external perimeter
G1 X163.931 Y234.633 E2.17278 ; external perimeter
G1 X163.039 Y235.398 E2.17745 ; external perimeter
G1 X162.277 Y236.015 E2.18133 ; external perimeter
G1 X161.467 Y236.636 E2.18539 ; external perimeter
G1 X160.524 Y237.322 E2.19001 ; external perimeter
G1 X159.693 Y237.890 E2.19401 ; external perimeter
G1 X158.539 Y238.635 E2.19946 ; external perimeter
G1 X157.886 Y237.735 E2.20387 ; external perimeter
G1 X159.233 Y236.880 E2.21020 ; external perimeter
G1 X160.265 Y236.161 E2.21519 ; external perimeter
G1 X161.181 Y235.479 E2.21972 ; external perimeter
G1 X161.996 Y234.837 E2.22384 ; external perimeter
G1 X163.298 Y233.730 E2.23062 ; external perimeter
G1 X164.438 Y232.669 E2.23680 ; external perimeter
G1 X165.635 Y231.465 E2.24354 ; external perimeter
G1 X156.810 Y219.318 E2.30312 ; external perimeter
G1 E0.30312 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
M107 ; disable fan
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = 152.800342
; cog_y = 231.367256
; cog_z = 8.966913
; filament_length_m = 0.0089 
; filament_volume_cm3 = 0.0629
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.022
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 8
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 4.2
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
